# SPDX-License-Identifier: MIT
# Copyright (c) 2026 K. S. Ernest (iFire) Lee
"""
Fourth hand-authored batch. Targets the 6 tropes that stayed at the data
floor (33-38 positives) after rounds 1-3 -- all semantically fuzzy,
high-context tropes (no keyword to regex-match, no public corpus signal
strong enough to seed-label reliably) where a 66M-param classifier needs
the *most* data to generalize rather than memorize, yet had the *least*:
  Superficial Analyses, The Dead Metaphor, False Vulnerability,
  Grandiose Stakes Inflation, Invented Concept Labels,
  Quietly and Other Magic Adverbs
Each gets ~30 more pairs, in topic domains not used in rounds 1-3
(publishing, music, pets, weather, transportation, outdoor gear).

Also broadly tops up rewrite-pair coverage for every other trope (~12 more
each), since the rewriter (FLAN-T5-small, seq2seq) needs more examples per
trope than the classifier to generalize rather than memorize, and rounds
1-3 left it thinner across the board than the classifier's real-corpus-fed
positives.
"""
import sys
import uuid

sys.path.insert(0, __file__.rsplit("scripts", 1)[0])
from runtime.datalake import (
    SENTENCE_PATH, SENTENCE_REWRITE_PATH, SENTENCE_TROPE_LABEL_PATH,
    SOURCE_DOCUMENT_PATH, append_rows, read_table, read_tropes,
)
from scripts.synth_generate import REWRITE_NAMESPACE, _insert_document

FLOOR_PAIRS = {
"Superficial Analyses": [
    ("The publisher rushed the reprint, reflecting its urgent commitment to readers.",
     "The publisher rushed the reprint."),
    ("The band added a second drummer, deepening the album's rhythmic ambition.",
     "The band added a second drummer."),
    ("The shelter adopted out the whole litter, showcasing its efficient placement process.",
     "The shelter adopted out the whole litter."),
    ("The airline added a direct route, reflecting its broader push into the region.",
     "The airline added a direct route."),
    ("The hikers reached the summit before noon, underscoring their careful pacing.",
     "The hikers reached the summit before noon."),
    ("The editor cut two chapters, tightening the novel's already lean structure.",
     "The editor cut two chapters."),
    ("The kennel extended visiting hours, further advancing its mission of transparency.",
     "The kennel extended visiting hours."),
    ("The choir added a new soloist, enriching the ensemble's expanding range.",
     "The choir added a new soloist."),
    ("The airline upgraded its boarding process, reflecting a renewed focus on speed.",
     "The airline upgraded its boarding process."),
    ("The vet added weekend appointments, deepening the clinic's commitment to access.",
     "The vet added weekend appointments."),
    ("The trail crew cleared the fallen tree, restoring the path's original character.",
     "The trail crew cleared the fallen tree."),
    ("The label re-released the album on vinyl, honoring its enduring cultural weight.",
     "The label re-released the album on vinyl."),
    ("The airport added a new gate, signaling its long-term investment in growth.",
     "The airport added a new gate."),
    ("The shelter installed new kennels, extending its role as a refuge for strays.",
     "The shelter installed new kennels."),
    ("The author signed early copies, deepening fans' connection to the story.",
     "The author signed early copies."),
    ("The forecast called for snow, adding to the season's building intensity.",
     "The forecast called for snow."),
    ("The station added a new platform, reflecting the city's growing transit needs.",
     "The station added a new platform."),
    ("The campsite added new fire pits, enriching the shared evening ritual for visitors.",
     "The campsite added new fire pits."),
    ("The publisher moved up the release date, showcasing confidence in the book.",
     "The publisher moved up the release date."),
    ("The band extended the tour, reflecting the strength of ticket demand.",
     "The band extended the tour."),
    ("The shelter waived the adoption fee, deepening its outreach to first-time owners.",
     "The shelter waived the adoption fee."),
    ("The trail added new markers, further advancing its commitment to hiker safety.",
     "The trail added new markers."),
    ("The airline added extra legroom seats, reflecting shifting passenger preferences.",
     "The airline added extra legroom seats."),
    ("The vet clinic added a second exam room, deepening its capacity for care.",
     "The vet clinic added a second exam room."),
    ("The record store restocked the reissue, tying the shop to its collector roots.",
     "The record store restocked the reissue."),
    ("The airport extended runway lighting, signaling its focus on safety.",
     "The airport extended runway lighting."),
    ("The shelter hosted an adoption fair, deepening its ties to the local community.",
     "The shelter hosted an adoption fair."),
    ("The tour bus added a rest stop, reflecting the crew's attention to comfort.",
     "The tour bus added a rest stop."),
    ("The forecaster extended the watch, underscoring the storm's growing reach.",
     "The forecaster extended the watch."),
    ("The publisher added a foreword, deepening the book's historical context.",
     "The publisher added a foreword."),
],
"The Dead Metaphor": [
    ("The tour is a journey, and every stop on the journey continues the tour's journey.",
     "The tour includes several stops along the way."),
    ("The novel is a maze, and the maze's turns lead readers through the maze of the plot.",
     "The novel has a complex, winding plot."),
    ("The kennel is a family, and every dog in that family joins the kennel-family.",
     "The kennel cares for dogs like a family."),
    ("The airport is a hub, and the hub's spokes connect the hub to every hub-destination.",
     "The airport connects to many destinations."),
    ("The trail is a thread, stitching together every thread of the mountain's thread-like paths.",
     "The trail connects several paths through the mountains."),
    ("The album is a river, and the river's songs flow into the album's river of sound.",
     "The album's songs flow smoothly from one to the next."),
    ("The forecast is a puzzle, and every puzzle piece of weather fits the forecast's puzzle.",
     "The forecast combines several weather patterns."),
    ("The shelter is an anchor, holding the community steady like an anchor holds a ship.",
     "The shelter provides stability for the community."),
    ("The station is a heartbeat, pumping commuters through the city's heartbeat-veins.",
     "The station moves commuters through the city efficiently."),
    ("The campsite is a canvas, painted anew each season by the campsite's canvas of colors.",
     "The campsite looks different each season."),
    ("The publisher is a gardener, tending the manuscript-garden until it blooms into a book.",
     "The publisher develops manuscripts into finished books."),
    ("The choir is a tapestry, woven from voices that make up the choir's tapestry of sound.",
     "The choir blends many different voices."),
    ("The airline is a bridge, spanning the bridge-gap between distant bridge-cities.",
     "The airline connects distant cities."),
    ("The vet clinic is a lighthouse, guiding pet owners through the fog toward the lighthouse's care.",
     "The vet clinic helps guide pet owners toward good care."),
    ("The band is an engine, and the engine's rhythm drives the band-engine forward.",
     "The band's rhythm section drives the sound forward."),
    ("The trail crew is a shield, protecting hikers behind the shield of their trail work.",
     "The trail crew's work protects hikers."),
    ("The record label is a compass, pointing artists toward the compass heading of success.",
     "The record label helps guide artists toward success."),
    ("The forecast is a mirror, reflecting the mirror-image of last year's storm season.",
     "The forecast resembles last year's storm season."),
    ("The kennel is a ladder, and every rung of the ladder lifts a dog up the kennel-ladder.",
     "The kennel helps dogs move step by step toward adoption."),
    ("The tour bus is a vessel, carrying the band across the vessel's long vessel-road.",
     "The tour bus carries the band across long distances."),
    ("The airport is a puzzle, and the puzzle pieces of flights fit the airport's daily puzzle.",
     "The airport coordinates many flights each day."),
    ("The novel is a mirror, reflecting the mirror-truths of the author's own life.",
     "The novel reflects parts of the author's own life."),
    ("The shelter is a bridge, connecting strays across the bridge to their new bridge-homes.",
     "The shelter connects strays to new homes."),
    ("The trail is a story, and every step on the trail writes another line of the trail's story.",
     "The trail offers scenic views along the way."),
    ("The station is a gateway, opening the gateway to every gateway-destination in the region.",
     "The station connects to many destinations in the region."),
    ("The publisher is an engine, and the engine's momentum drives the publisher-engine's catalog.",
     "The publisher's catalog keeps growing steadily."),
    ("The choir is a garden, and the garden's voices bloom into the choir's garden of harmony.",
     "The choir's voices blend into rich harmony."),
    ("The airline is an anchor for the region, holding travel steady like an anchor holds a ship.",
     "The airline provides stable travel options for the region."),
    ("The kennel is a heartbeat, pumping new arrivals through the shelter's heartbeat-halls.",
     "The kennel processes new arrivals steadily."),
    ("The campsite is a thread, stitching together every thread of the forest's thread-like trails.",
     "The campsite connects to several trails through the forest."),
],
"False Vulnerability": [
    ("I'll admit it, I doubted the new flight route would fill seats, and it did.",
     "The new flight route filled seats despite my doubts."),
    ("I'm not too proud to say I misjudged how long the trail repair would take.",
     "The trail repair took longer than expected."),
    ("Honestly, I was nervous about the album's new sound, and it turned out fine.",
     "The album's new sound turned out fine despite initial concerns."),
    ("I'll be the first to admit I underestimated how popular the reissue would be.",
     "The reissue was more popular than expected."),
    ("Confession: I almost canceled the tour over the weather forecast.",
     "The tour was almost canceled over the weather forecast."),
    ("I used to think the shelter's new intake form was unnecessary, and I was wrong.",
     "The shelter's new intake form turned out to be useful."),
    ("I won't pretend the move to the new venue was smooth.",
     "The move to the new venue wasn't smooth."),
    ("I'll admit, I got emotional watching the shelter dog get adopted.",
     "I was emotional watching the shelter dog get adopted."),
    ("I'm not ashamed to say the first draft of the manuscript was rejected twice.",
     "The first draft of the manuscript was rejected twice."),
    ("Honestly, I was skeptical of the new gate assignment, and it worked out fine.",
     "The new gate assignment worked out fine despite initial skepticism."),
    ("I'll admit it: I nearly gave up on the novel in the second act.",
     "I nearly gave up on the novel in the second act."),
    ("I used to doubt the vet's new schedule would help, and it did.",
     "The vet's new schedule helped despite my doubts."),
    ("I'm not too proud to admit the tour budget had an error for weeks.",
     "The tour budget had an error for weeks."),
    ("I'll be honest, I didn't expect the album to chart this high.",
     "The album charted higher than expected."),
    ("I won't hide it: the first year running the kennel nearly overwhelmed me.",
     "The first year running the kennel was overwhelming."),
    ("I'll admit I doubted the new runway lighting would matter, and it did.",
     "The new runway lighting mattered more than expected."),
    ("Honestly, I was unsure the trail reroute would hold up, and it has.",
     "The trail reroute has held up despite early uncertainty."),
    ("I'm not too proud to say the first pressing of the record had a flaw.",
     "The first pressing of the record had a flaw."),
    ("I'll admit, I cried a little when the shelter hit zero strays for the first time.",
     "I was emotional when the shelter hit zero strays for the first time."),
    ("I used to doubt weekend vet hours would be worth it, and they have been.",
     "Weekend vet hours have been worth it despite early doubts."),
    ("Confession: I almost skipped the soundcheck, and I'm glad I didn't.",
     "The soundcheck turned out to be worthwhile."),
    ("I'll admit, the forecast scared me more than any storm this season.",
     "This storm's forecast was more concerning than others this season."),
    ("I'm not too proud to say the shelter's budget nearly ran out last winter.",
     "The shelter's budget nearly ran out last winter."),
    ("Honestly, I doubted the campsite upgrade was worth the cost, and it was.",
     "The campsite upgrade was worth the cost despite initial doubts."),
    ("I won't pretend the layover delay didn't stress the whole crew out.",
     "The layover delay stressed out the whole crew."),
    ("I'll admit it: I nearly rewrote the whole second half of the book.",
     "I nearly rewrote the whole second half of the book."),
    ("I used to think the new boarding process was overkill, and I was wrong.",
     "The new boarding process turned out to be useful."),
    ("I'm not ashamed to say the shelter's first fundraiser barely broke even.",
     "The shelter's first fundraiser barely broke even."),
    ("Honestly, I was doubtful about the vinyl reissue, and sales proved me wrong.",
     "Sales proved the vinyl reissue's doubters wrong."),
    ("I'll admit, the first night at the new venue nearly went wrong.",
     "The first night at the new venue nearly went wrong."),
],
"Grandiose Stakes Inflation": [
    ("This new bus route will change the entire future of how the region travels.",
     "This new bus route will make one commute easier."),
    ("This one dog's adoption marks a turning point for shelters everywhere.",
     "This dog's adoption made room for one more rescue."),
    ("This is more than an album; it's a movement that will redefine music itself.",
     "This album offers a new sound for the band."),
    ("This small trail crew will transform hiking as we know it.",
     "This trail crew will clear brush along one section of trail."),
    ("This is the moment that changes everything for every publisher everywhere.",
     "This deal will help one publisher expand its catalog."),
    ("This one soundcheck will revolutionize how the whole industry tours.",
     "This soundcheck will help the band prepare for one show."),
    ("This runway repaving isn't just maintenance; it's a rebirth for the entire airport.",
     "This runway repaving fixes cracks along one strip."),
    ("This youth music program will shape the destiny of an entire generation.",
     "This youth music program will teach twenty kids this summer."),
    ("This trail expansion redefines what it means to be an outdoor destination.",
     "This trail expansion adds a mile of new path."),
    ("This is the single decision that will determine the fate of the whole tour.",
     "This decision affects next month's tour schedule."),
    ("This vet visit isn't just a checkup; it's a life-altering intervention.",
     "This vet visit covers this month's checkup."),
    ("This record store will change the course of the entire neighborhood's culture.",
     "This record store offers a new option for local music fans."),
    ("This is bigger than one flight delay; it's a crisis for the whole airline.",
     "This flight delay affected one route today."),
    ("This new kennel wing will reshape the future of animal welfare nationwide.",
     "This new kennel wing adds space for a dozen more dogs."),
    ("This single lecture will change how humanity understands migration forever.",
     "This lecture covers recent findings about bird migration."),
    ("This weather warning isn't just a forecast; it's a wake-up call for the whole region.",
     "This weather warning covers expected rain this weekend."),
    ("This one campsite renovation will redefine outdoor recreation for the state.",
     "This campsite renovation adds new fire pits and tables."),
    ("This shelter fundraiser will determine the future of animal rescue everywhere.",
     "This fundraiser will support the shelter's budget this year."),
    ("This new gate isn't just an addition; it's a revolution in airport capacity.",
     "This new gate adds one more boarding area."),
    ("This tour stop marks the beginning of a new era for the band.",
     "This tour stop adds one more city to the schedule."),
    ("This trail marker system will transform how an entire generation of hikers navigates.",
     "This trail marker system helps hikers find their way on one trail."),
    ("This is more than a book signing; it's a cultural moment for readers everywhere.",
     "This book signing gives fans a chance to meet the author."),
    ("This vet clinic's new hours will reshape pet care across the whole county.",
     "This vet clinic's new hours add weekend appointments."),
    ("This is the single flight that will define the airline's whole future.",
     "This flight is the airline's first on this new route."),
    ("This one kennel renovation will change how the world sees shelter animals.",
     "This kennel renovation adds better lighting and larger runs."),
    ("This record deal isn't just a contract; it's a turning point for the entire genre.",
     "This record deal gives the band wider distribution."),
    ("This trail cleanup will define the legacy of outdoor stewardship for decades.",
     "This trail cleanup removes litter along one popular section."),
    ("This weather station upgrade will change how the whole coast prepares for storms.",
     "This weather station upgrade improves forecasts for one stretch of coast."),
    ("This is the tour stop that will be remembered as the turning point of the decade.",
     "This tour stop drew a bigger crowd than usual."),
    ("This shelter's new adoption event will reshape how the city thinks about rescue pets.",
     "This adoption event will place a dozen more pets this weekend."),
],
"Invented Concept Labels": [
    ("This is a textbook case of the layover trap: short connections create longer delays downstream.",
     "This shows how short layovers can create delays elsewhere in the schedule."),
    ("We're seeing the reissue effect: old albums sell better after a vinyl re-release.",
     "Old albums tend to sell better after a vinyl re-release."),
    ("This is what I call the shelter cliff, where intake spikes right after the holidays.",
     "Shelter intake tends to spike right after the holidays."),
    ("Call it the trailhead bottleneck: one narrow entrance slows the whole hike.",
     "One narrow entrance point slows down the whole hike."),
    ("This is the classic second-album slump every band eventually faces.",
     "Many bands face a difficult second album."),
    ("We're witnessing the forecast lag, where warnings arrive after the storm's already visible.",
     "Storm warnings sometimes arrive later than the storm becomes visible."),
    ("This is the runway debt nobody accounts for until maintenance season.",
     "This is the maintenance backlog that builds up on runways over time."),
    ("Call it the adoption fog: new pet owners rarely retain the first-day instructions.",
     "New pet owners rarely retain instructions given on the first day."),
    ("This is the classic manuscript spiral, where one edit reveals three more.",
     "One edit to a manuscript often reveals the need for more."),
    ("We're in what I'd call the ticket anxiety phase before the tour announcement.",
     "Fans are anxious before the tour announcement."),
    ("This is the seasonal dip nearly every kennel sees in early spring.",
     "Kennel intake typically dips for most shelters in early spring."),
    ("Call it the gate-change cascade: one delayed flight shifts three others.",
     "One delayed flight can shift the schedule for several others."),
    ("This is a clear case of the trail-erosion cliff after a wet winter.",
     "Trail erosion tends to worsen sharply after a wet winter."),
    ("We're seeing the fan-loyalty rebound now that the tour dates were announced.",
     "Fan engagement is recovering now that tour dates were announced."),
    ("This is the classic burnout curve among trail crews after a long summer season.",
     "Many trail crew members experience burnout after a long summer season."),
    ("Call it the intake cliff shelters see right before winter.",
     "Shelters typically see intake rise right before winter."),
    ("This is a textbook demand echo: album streams spike again after a tour date.",
     "Album streams tend to spike again after a tour date is announced."),
    ("We're witnessing the checkout drag every airport counter eventually hits.",
     "This is the point where airport check-in lines slow down during peak hours."),
    ("This is what I'd call the reissue ceiling, where remastered sales eventually plateau.",
     "This is the point where remastered album sales stop growing."),
    ("Call it the weather creep: each storm slightly extends the forecast window.",
     "Each storm has slightly extended how far ahead forecasts need to look."),
    ("This is the classic kennel plateau every shelter eventually hits with adoptions.",
     "This is the point where adoption rates level off for a shelter."),
    ("We're seeing the loyalty erosion effect after the ticket price increase.",
     "Fan loyalty declined somewhat after the ticket price increase."),
    ("This is a case of what I'd call the migration lag in the birding community.",
     "This shows how bird migration patterns are shifting later than expected."),
    ("Call it the trailhead crunch: parking fills before the trail itself gets busy.",
     "Trailhead parking tends to fill before the trail itself gets crowded."),
    ("This is the classic tour fatigue every band faces by the third month.",
     "Many bands experience fatigue by the third month of touring."),
    ("We're in what I'd call the recovery plateau phase of the shelter's rebuild.",
     "The shelter's rebuild has reached a slower phase of progress."),
    ("This is a textbook case of the gate lag: boarding starts later than announced.",
     "Boarding sometimes starts later than the announced time."),
    ("Call it the album afterglow: streams stay elevated for weeks after release.",
     "Streams tend to stay elevated for weeks after an album's release."),
    ("This is the classic staffing plateau every growing kennel eventually hits.",
     "This is the point where kennel staffing stops keeping up with growth."),
    ("We're seeing the ticket rebound now that refunds from the canceled show cleared.",
     "Ticket sales are recovering now that refunds from the canceled show cleared."),
],
"Quietly and Other Magic Adverbs": [
    ("The new boarding process is quietly cutting delays at the gate.",
     "The new boarding process cut delays at the gate."),
    ("Her mentorship is deeply shaping how new vets approach difficult cases.",
     "Her mentorship shaped how new vets approach difficult cases."),
    ("The trail reroute is fundamentally improving hiker safety on the ridge.",
     "The trail reroute improved hiker safety on the ridge."),
    ("The new setlist is quietly reshaping how fans experience the show.",
     "The new setlist changed how fans experience the show."),
    ("This small grant is remarkably transforming the shelter's intake process.",
     "This small grant changed the shelter's intake process."),
    ("The revised schedule is quietly cutting layover times across the network.",
     "The revised schedule cut layover times across the network."),
    ("Her editing style is deeply influencing how the imprint selects manuscripts.",
     "Her editing style changed how the imprint selects manuscripts."),
    ("The new forecast model is fundamentally altering how the region prepares for storms.",
     "The new forecast model changed how the region prepares for storms."),
    ("This policy is quietly reducing overcrowding at the shelter.",
     "This policy reduced overcrowding at the shelter."),
    ("The remaster is deeply changing how listeners experience the old album.",
     "The remaster changed how listeners experience the old album."),
    ("The new gear is remarkably boosting the crew's trail-clearing pace.",
     "The new gear boosted the crew's trail-clearing pace."),
    ("Her leadership is quietly transforming the kennel's volunteer culture.",
     "Her leadership changed the kennel's volunteer culture."),
    ("The updated forms are fundamentally simplifying pet intake at the clinic.",
     "The updated forms simplified pet intake at the clinic."),
    ("This new lighting is quietly improving safety along the runway.",
     "This new lighting improved safety along the runway."),
    ("The pilot program is deeply reshaping how the label scouts new artists.",
     "The pilot program changed how the label scouts new artists."),
    ("The new radar is remarkably improving storm-tracking accuracy this season.",
     "The new radar improved storm-tracking accuracy this season."),
    ("Her coaching is quietly transforming how the choir handles difficult passages.",
     "Her coaching changed how the choir handles difficult passages."),
    ("The updated intake form is fundamentally speeding up shelter admissions.",
     "The updated intake form sped up shelter admissions."),
    ("This new schedule is quietly easing the strain on the ground crew.",
     "This new schedule eased the strain on the ground crew."),
    ("The revised trail map is deeply changing how visitors plan their hikes.",
     "The revised trail map changed how visitors plan their hikes."),
    ("The new fertilizer mix is remarkably boosting the campsite's shade trees.",
     "The new fertilizer mix boosted the campsite's shade trees."),
    ("Her mentoring is quietly transforming how junior editors read submissions.",
     "Her mentoring changed how junior editors read submissions."),
    ("The updated boarding signs are fundamentally reducing confusion at the gate.",
     "The updated boarding signs reduced confusion at the gate."),
    ("This new vet rotation is quietly improving continuity of care for patients.",
     "This new vet rotation improved continuity of care for patients."),
    ("The remastered vinyl is deeply reshaping how collectors value the album.",
     "The remastered vinyl changed how collectors value the album."),
    ("The new signage is remarkably reducing wrong turns on the summit trail.",
     "The new signage reduced wrong turns on the summit trail."),
    ("Her scheduling changes are quietly easing overtime for the flight crew.",
     "Her scheduling changes eased overtime for the flight crew."),
    ("The new drainage system is fundamentally protecting the campsite from flooding.",
     "The new drainage system protected the campsite from flooding."),
    ("This grant is deeply expanding what the shelter's clinic can offer.",
     "This grant expanded what the shelter's clinic can offer."),
    ("The new perch design is quietly improving the aviary's bird welfare scores.",
     "The new perch design improved the aviary's bird welfare scores."),
],
}

# Broad rewrite-only top-up for every other trope, to close the gap between
# the classifier's real-corpus-fed positives and the rewriter's much thinner
# hand-authored-only pair count.
REWRITE_TOPUP = {
"Delve and Friends": [
    ("Let's delve into why the flight kept getting delayed.", "Here's why the flight kept getting delayed."),
    ("The kennel will utilize the new wing starting next month.", "The kennel will use the new wing starting next month."),
    ("The band wants to leverage streaming data to plan the setlist.", "The band wants to use streaming data to plan the setlist."),
    ("This is a robust plan that streamlines the shelter's intake.", "This plan simplifies the shelter's intake."),
    ("Let's delve into why the trail closed early this season.", "Here's why the trail closed early this season."),
],
"Tapestry and Landscape": [
    ("The rich tapestry of the music festival draws fans from across the state.",
     "The music festival draws fans from across the state."),
    ("Navigating the landscape of airline pricing took the family weeks.",
     "Understanding airline pricing took the family weeks."),
    ("The tour weaves together a tapestry of stops across three continents.",
     "The tour includes stops across three continents."),
    ("The zoning landscape shifted after the new airport rule passed.",
     "Zoning changed after the new airport rule passed."),
    ("Understanding the competitive landscape of local shelters took months.",
     "Understanding local shelter needs took months."),
],
"The Serves As Dodge": [
    ("The plaque serves as a reminder of the airport's founding year.",
     "The plaque is a reminder of the airport's founding year."),
    ("This manual serves as a starting point for new trail volunteers.",
     "This manual is a starting point for new trail volunteers."),
    ("The album serves as a tribute to the band's late drummer.",
     "The album is a tribute to the band's late drummer."),
    ("Her promotion marks a turning point for the shelter's clinic.",
     "Her promotion is a turning point for the shelter's clinic."),
    ("The badge serves as proof of completed trail-safety training.",
     "The badge is proof of completed trail-safety training."),
],
"Think of It As": [
    ("Think of the boarding groups like a queue system for the whole flight.",
     "The boarding groups work like a queue system for the whole flight."),
    ("Think of the trail markers as a cheat sheet for the whole hike.",
     "The trail markers summarize the whole hike."),
    ("Think of the intake form as a snapshot of the pet's whole history.",
     "The intake form captures a snapshot of the pet's whole history."),
    ("Think of the setlist as a roadmap for the whole show.",
     "The setlist is a roadmap for the whole show."),
    ("Think of the forecast model as a rehearsal for the real storm.",
     "The forecast model rehearses conditions before the real storm."),
],
"The Signposted Conclusion": [
    ("In conclusion, the new gate assignments reduced boarding delays.",
     "The new gate assignments reduced boarding delays."),
    ("To sum up, the tour ended with the best attendance in years.",
     "The tour ended with the best attendance in years."),
    ("In summary, the shelter's new intake process cut wait times.",
     "The shelter's new intake process cut wait times."),
    ("In conclusion, the trail crew should prioritize erosion control next season.",
     "The trail crew should prioritize erosion control next season."),
    ("To conclude, the pilot vet schedule met all of its goals.",
     "The pilot vet schedule met all of its goals."),
],
"Tricolon Abuse": [
    ("The shelter rescues, the shelter heals, the shelter rehomes.",
     "The shelter rescues, heals, and rehomes animals."),
    ("Good pilots plan; good pilots communicate; good pilots adapt.",
     "Good pilots plan, communicate, and adapt."),
    ("It's faster. It's safer. It's simpler.",
     "It's faster, safer, and simpler."),
    ("The band tours hard; the band tours often; the band tours well.",
     "The band tours hard, often, and well."),
    ("Good forecasts are timely, accurate, and clear.",
     "Good forecasts are timely, accurate, and clear."),
],
"Unicode Decoration": [
    ("The tour goes City A → City B → City C.", "The tour visits City A, then City B, then City C."),
    ("Recovery moved Injured → Rehab → Cleared.", "Recovery moved from injured to rehab to cleared."),
    ("The flight path is Gate → Runway → Cruise.", "The flight path goes from the gate to the runway to cruise."),
],
"It's Worth Noting": [
    ("It's worth noting that the shelter's new hours only apply on weekends.",
     "The shelter's new hours only apply on weekends."),
    ("Importantly, the vet requires records from the pet's last clinic.",
     "The vet requires records from the pet's last clinic."),
    ("Interestingly, the smaller venues sold out faster than the arena.",
     "The smaller venues sold out faster than the arena."),
    ("Notably, none of the volunteers had trail-building experience.",
     "None of the volunteers had trail-building experience."),
],
"Vague Attributions": [
    ("Experts say the storm season will be milder this year.",
     "The regional weather service says the storm season will be milder this year."),
    ("Observers note ticket demand has cooled for smaller venues.",
     "Concert promoters note ticket demand has cooled for smaller venues."),
    ("Reports suggest the airline may add more direct routes next year.",
     "An internal memo suggests the airline may add more direct routes next year."),
    ("Some say the new kennel layout is calmer for the dogs.",
     "The shelter's staff say the new kennel layout is calmer for the dogs."),
],
"One-Point Dilution": [
    ("The tour was exhausting. The schedule was packed. There was no rest. Travel dragged on. Everyone was worn out.",
     "The tour was exhausting."),
    ("The shelter was overwhelmed. Intake spiked. Staff were stretched thin. Space ran out. Everything piled up.",
     "The shelter was overwhelmed."),
],
"False Ranges": [
    ("The tour covers everything from small clubs to massive stadiums.",
     "The tour includes small clubs and, separately, stadium shows."),
    ("The clinic's services range from vaccinations to grief counseling.",
     "The clinic offers vaccinations and, separately, grief counseling."),
    ("The workshop spans from basic trail maintenance to wilderness survival.",
     "The workshop covers basic trail maintenance and, separately, survival skills."),
],
"Short Punchy Fragments": [
    ("The flight landed. Late. Without an announcement.",
     "The flight landed late, without an announcement."),
    ("The shelter filled up. Fast. Within a single day.",
     "The shelter filled up fast, within a single day."),
    ("The storm passed. Suddenly. Just after midnight.",
     "The storm passed suddenly, just after midnight."),
],
"Listicle in a Trench Coat": [
    ("The first stop is the overlook. The second stop is the waterfall.",
     "The tour passes the overlook and the waterfall."),
    ("The first issue is staffing. The second issue is space. The third issue is funding.",
     "The main issues are staffing, space, and funding."),
],
"Historical Analogy Stacking": [
    ("The old runway closed in the 90s. The new one opened in the 2000s. This one just opened.",
     "The airport has had several runways since the 1990s."),
    ("The label started with vinyl. It added CDs. It added streaming.",
     "The label expanded from vinyl into CDs and streaming over time."),
],
"Content Duplication": [
    ("The airline added two new routes this spring. The airline added two new routes this spring.",
     "The airline added two new routes this spring."),
    ("The shelter placed a record number of pets this month. The shelter placed a record number of pets this month.",
     "The shelter placed a record number of pets this month."),
],
"Fractal Summaries": [
    ("This section covers the tour schedule. As we've seen, the tour schedule was covered above.",
     "This section covers the tour schedule."),
    ("We'll review the shelter's new intake steps below. As reviewed above, intake now has three steps.",
     "The shelter's intake process, reviewed below, now has three steps."),
],
"Negative Parallelism": [
    ("It's not the weather delaying the flight. It's a mechanical check.",
     "A mechanical check delayed the flight, not the weather."),
    ("It's not overcrowding at the shelter. It's understaffing.",
     "Understaffing caused this, not overcrowding."),
],
"Not X. Not Y. Just Z.": [
    ("Not a delay. Not a diversion. A full cancellation.",
     "This is a full cancellation."),
    ("Not neglect. Not carelessness. Just an outdated vet schedule.",
     "An outdated vet schedule caused this."),
],
"The X? A Y.": [
    ("The cause? A cracked runway light.", "A cracked runway light caused it."),
    ("The outcome? A record adoption weekend.", "The weekend saw a record number of adoptions."),
],
"Here's the Kicker": [
    ("Here's the kicker: the smallest venue had the loudest crowd.",
     "The smallest venue had the loudest crowd."),
    ("Here's the thing about the shelter: intake dropped after the fee waiver.",
     "Intake dropped at the shelter after the fee waiver."),
],
"Let's Break This Down": [
    ("Let's break this down step by step, starting with the flight delay.",
     "Here is what caused the flight delay."),
    ("Let's walk through the intake steps together, one at a time.",
     "Here are the intake steps."),
],
"Despite Its Challenges": [
    ("Despite the storm, the flight landed only twenty minutes late.",
     "The storm delayed the flight by only twenty minutes."),
    ("Despite the shortage, the shelter placed every dog by winter.",
     "The shortage delayed several placements at the shelter until winter."),
],
"Anaphora Abuse": [
    ("They assume the flight leaves on time. They assume the gate stays open. They assume the weather holds.",
     "They assume the flight leaves on time, the gate stays open, and the weather holds."),
    ("We believe in safe trails. We believe in clear signage. We believe in careful stewardship.",
     "We believe in safe trails, clear signage, and careful stewardship."),
],
"Bold-First Bullets": [
    ("- **Attendance:** the tour drew record crowds.\n- **Weather:** clear skies most nights.",
     "- The tour drew record crowds.\n- The weather was clear most nights."),
    ("- **Placements:** the shelter found homes for a record number of pets.\n- **Costs:** adoption fees stayed the same.",
     "- The shelter found homes for a record number of pets.\n- Adoption fees stayed the same."),
],
}


def _insert_pairs(pairs_by_trope, name_to_id, doc_rows, sent_rows, label_rows, rewrite_rows):
    for name, pairs in pairs_by_trope.items():
        trope_id = name_to_id[name]
        for positive, rewrite in pairs:
            pos_ids = _insert_document(positive, True, True, doc_rows, sent_rows)
            rewrite_ids = _insert_document(rewrite, True, False, doc_rows, sent_rows)
            for sid in pos_ids:
                label_rows.append({
                    "sentence_id": sid, "trope_id": trope_id,
                    "label_source": "synthetic-gen", "confidence": 1.0,
                })
            if pos_ids and rewrite_ids:
                rewrite_rows.append({
                    "rewrite_id": str(uuid.uuid5(REWRITE_NAMESPACE, pos_ids[0])),
                    "sentence_id": pos_ids[0], "trope_id": trope_id,
                    "rewritten_text": rewrite.strip(), "source": "synthetic-gen",
                })


def main():
    tropes = read_tropes()
    name_to_id = dict(zip(tropes.column("name").to_pylist(), tropes.column("trope_id").to_pylist()))

    doc_rows, sent_rows, label_rows, rewrite_rows = [], [], [], []
    _insert_pairs(FLOOR_PAIRS, name_to_id, doc_rows, sent_rows, label_rows, rewrite_rows)
    _insert_pairs(REWRITE_TOPUP, name_to_id, doc_rows, sent_rows, label_rows, rewrite_rows)

    append_rows(SOURCE_DOCUMENT_PATH, doc_rows)
    append_rows(SENTENCE_PATH, sent_rows)
    append_rows(SENTENCE_TROPE_LABEL_PATH, label_rows)
    append_rows(SENTENCE_REWRITE_PATH, rewrite_rows)
    print(f"round 4: {len(doc_rows)} docs, {len(label_rows)} labels, {len(rewrite_rows)} rewrite pairs")


if __name__ == "__main__":
    main()
