# SPDX-License-Identifier: MIT
# Copyright (c) 2026 K. S. Ernest (iFire) Lee
"""
Third hand-authored batch, additive to rounds 1 and 2. The real corpora
(HC3 + artem9k/ai-text-detection-pile) gave every trope real classifier
coverage, but they're unpaired text -- they can't supply rewrite
supervision (a sentence next to its trope-free rewrite of the *same
meaning*), which only comes from hand-authoring or an LLM call this
environment doesn't have access to. This batch exists to close that gap:
every trope gets ~12 more pairs, in topic domains rounds 1-2 didn't use
(retail, travel, home repair, sports training, civic services), pushing
rewrite-pair coverage from a 12-26/trope floor toward the high 20s-30s.

Still short of a truly "capacity-filled" rewrite set (a few hundred pairs
per trope) -- see the per-trope counts this script prints on exit.
"""
import sys
import uuid

sys.path.insert(0, __file__.rsplit("scripts", 1)[0])
from runtime.datalake import (
    SENTENCE_PATH, SENTENCE_REWRITE_PATH, SENTENCE_TROPE_LABEL_PATH,
    SOURCE_DOCUMENT_PATH, append_rows, read_table, read_tropes,
)
from scripts.synth_generate import REWRITE_NAMESPACE, _insert_document

PAIRS = {
"Quietly and Other Magic Adverbs": [
    ("The new checkout kiosks are quietly cutting wait times at the store.",
     "The new checkout kiosks cut wait times at the store."),
    ("Her coaching is fundamentally changing how the swim team starts races.",
     "Her coaching changed how the swim team starts races."),
    ("The repaved lot is remarkably reducing complaints about potholes.",
     "The repaved lot reduced complaints about potholes."),
    ("The new booking system is quietly easing the front desk's workload.",
     "The new booking system eased the front desk's workload."),
    ("This small policy is deeply reshaping how the rec league schedules games.",
     "This policy changed how the rec league schedules games."),
    ("The insulation upgrade is quietly lowering the store's energy bill.",
     "The insulation upgrade lowered the store's energy bill."),
    ("Her drills are fundamentally improving the team's free-throw percentage.",
     "Her drills improved the team's free-throw percentage."),
    ("The new signage is quietly reducing wrong turns at the rest stop.",
     "The new signage reduced wrong turns at the rest stop."),
    ("This training plan is deeply changing how new hires learn the register.",
     "This training plan changed how new hires learn the register."),
    ("The extra lane is remarkably easing weekend traffic downtown.",
     "The extra lane eased weekend traffic downtown."),
    ("The new locker layout is quietly speeding up practice changeovers.",
     "The new locker layout sped up practice changeovers."),
    ("This grant is fundamentally expanding what the rec center can offer.",
     "This grant expanded what the rec center can offer."),
],
"Delve and Friends": [
    ("Let's delve into why the rink's ice keeps cracking.",
     "Here's why the rink's ice keeps cracking."),
    ("The store plans to utilize the back lot for overflow parking.",
     "The store plans to use the back lot for overflow parking."),
    ("The coach wants to leverage the new scoreboard for stat tracking.",
     "The coach wants to use the new scoreboard for stat tracking."),
    ("This is a robust plan that streamlines the return process.",
     "This plan simplifies the return process."),
    ("To delve deeper into the complaint, staff reviewed the camera footage.",
     "To understand the complaint better, staff reviewed the camera footage."),
    ("The gym harnesses off-peak hours to schedule maintenance.",
     "The gym uses off-peak hours to schedule maintenance."),
    ("Certainly, the renovation will require closing two lanes for a month.",
     "The renovation will require closing two lanes for a month."),
    ("We should utilize the extra freezer space during the holiday rush.",
     "We should use the extra freezer space during the holiday rush."),
    ("Let's delve into why ticket sales dropped this month.",
     "Here's why ticket sales dropped this month."),
    ("The new app leverages loyalty points to streamline checkout.",
     "The new app uses loyalty points to speed up checkout."),
    ("The clinic wants to leverage the new intake kiosk to cut wait times.",
     "The clinic wants to use the new intake kiosk to cut wait times."),
    ("Let's delve into the reasons the shuttle route keeps changing.",
     "Here are the reasons the shuttle route keeps changing."),
],
"Tapestry and Landscape": [
    ("The rich tapestry of the farmers market reflects the whole county's produce.",
     "The farmers market reflects the whole county's produce."),
    ("Navigating the landscape of youth sports leagues took the family two seasons.",
     "Understanding youth sports leagues took the family two seasons."),
    ("The gym's pitch leaned on the paradigm of community fitness.",
     "The gym's pitch focused on community fitness."),
    ("Our retail ecosystem now spans four storefronts downtown.",
     "Our stores now span four storefronts downtown."),
    ("The tour weaves together a tapestry of local history stops.",
     "The tour includes several local history stops."),
    ("The zoning landscape shifted after the new ordinance passed.",
     "Zoning changed after the new ordinance passed."),
    ("This checkout system fits into our broader retail ecosystem.",
     "This checkout system fits into our stores' setup."),
    ("The workshop explored the shifting paradigm of neighborhood commerce.",
     "The workshop discussed how neighborhood commerce is changing."),
    ("The park's tapestry of trails peaks in early October.",
     "The park's trails are busiest in early October."),
    ("Understanding the competitive landscape of local gyms took months.",
     "Understanding local gym competitors took months."),
    ("The mural's tapestry of colors tells the town's founding story.",
     "The mural's colors tell the town's founding story."),
    ("The renovation plan considers the whole retail landscape downtown.",
     "The renovation plan considers the downtown stores as a whole."),
],
"The Serves As Dodge": [
    ("The plaque serves as a reminder of the old cannery.",
     "The plaque is a reminder of the old cannery."),
    ("This checklist serves as a starting point for new hires.",
     "This checklist is a starting point for new hires."),
    ("The scoreboard stands as a tribute to the league's founders.",
     "The scoreboard is a tribute to the league's founders."),
    ("Her promotion marks a turning point for the store's night shift.",
     "Her promotion is a turning point for the store's night shift."),
    ("The warranty serves as protection against manufacturing defects.",
     "The warranty protects against manufacturing defects."),
    ("The trophy serves as recognition of the team's undefeated season.",
     "The trophy recognizes the team's undefeated season."),
    ("This intro class serves as a primer for the rest of the season.",
     "This intro class introduces the rest of the season."),
    ("The curb serves as a boundary between the lot and the sidewalk.",
     "The curb is the boundary between the lot and the sidewalk."),
    ("The trial run serves as a test case for the store's new hours.",
     "The trial run is a test case for the store's new hours."),
    ("This check-in serves as a milestone before the tournament.",
     "This check-in is a milestone before the tournament."),
    ("The banner serves as a marker for the finish line.",
     "The banner marks the finish line."),
    ("The badge serves as proof of completed training.",
     "The badge is proof of completed training."),
],
"Negative Parallelism": [
    ("It's not a shortage of parking. It's poor signage.",
     "Poor signage caused this, not a shortage of parking."),
    ("It's not the weather delaying the shipment. It's customs.",
     "Customs delayed the shipment, not the weather."),
    ("It's not bad service. It's an understaffed weekend shift.",
     "An understaffed weekend shift caused this, not bad service."),
    ("It's not a small update. It's a full rebuild of the loyalty app.",
     "This is a full rebuild of the loyalty app."),
    ("It's not overbooking. It's a scheduling bug.",
     "A scheduling bug caused this, not overbooking."),
    ("It's not a delay. It's a cancellation of the tournament.",
     "This is a cancellation of the tournament."),
    ("It's not the recipe failing. It's the walk-in freezer.",
     "The walk-in freezer caused this, not the recipe."),
    ("It's not luck that attendance rose. It's the new schedule.",
     "The new schedule raised attendance."),
    ("It's not carelessness. It's an outdated training manual.",
     "An outdated training manual caused this, not carelessness."),
    ("It's not a minor issue. It's a broken drainage pipe.",
     "This is a broken drainage pipe."),
    ("It's not the coach's fault. It's the injury list.",
     "The injury list caused this, not the coach."),
    ("It's not timing. It's a supplier shortage.",
     "A supplier shortage caused this, not timing."),
],
"Not X. Not Y. Just Z.": [
    ("Not a delay. Not a rain check. A full cancellation.",
     "This is a full cancellation."),
    ("Not slow checkout. Not rude staff. Just one broken register.",
     "One broken register caused this, not slow checkout or rude staff."),
    ("Not a fad. Not a phase. A permanent change in store hours.",
     "This is a permanent change in store hours."),
    ("Not carelessness. Not laziness. Just a missing part.",
     "A missing part caused this, not carelessness or laziness."),
    ("Not a suggestion. Not a guideline. A league requirement.",
     "This is a league requirement."),
    ("Not luck. Not favoritism. Just years of practice.",
     "Years of practice explain this, not luck or favoritism."),
    ("Not a maybe. Not a someday. A decision made this week.",
     "This decision was made this week."),
    ("Not an accident. Not a glitch. A deliberate price change.",
     "This was a deliberate price change."),
    ("Not optional. Not a nice-to-have. Required for certification.",
     "This is required for certification."),
    ("Not a rumor. Not speculation. Confirmed by the league office.",
     "This is confirmed by the league office."),
    ("Not exhaustion. Not overtraining. Just a pulled muscle.",
     "A pulled muscle caused this, not exhaustion or overtraining."),
    ("Not a small dent. Not cosmetic damage. A safety issue.",
     "This is a safety issue."),
],
"The X? A Y.": [
    ("The cause? A jammed conveyor belt.",
     "A jammed conveyor belt caused it."),
    ("The verdict? Full refund issued.",
     "A full refund was issued."),
    ("The fix? A new belt, nothing more.",
     "The fix was a new belt, nothing more."),
    ("The outcome? A sellout crowd despite the rain.",
     "The crowd sold out despite the rain."),
    ("The reason? A missed shipment two weeks ago.",
     "A missed shipment two weeks ago explains it."),
    ("The plan? Restock every Tuesday instead of Friday.",
     "The plan is to restock every Tuesday instead of Friday."),
    ("The response? A quiet refund and an apology email.",
     "The response was a quiet refund and an apology email."),
    ("The upside? Shipping costs dropped by a third.",
     "Shipping costs dropped by a third."),
    ("The risk? One supplier for the whole product line.",
     "One supplier for the whole product line is the risk."),
    ("The result? A gym that finally has enough parking.",
     "The gym finally has enough parking."),
    ("The delay? A permit stuck at city hall.",
     "A permit stuck at city hall caused the delay."),
    ("The surprise? The smallest store had the best sales.",
     "The smallest store had the best sales."),
],
"Here's the Kicker": [
    ("Here's the kicker: the discount code worked better than the sale itself.",
     "The discount code worked better than the sale itself."),
    ("Here's the thing: nobody read the return policy before complaining.",
     "Nobody read the return policy before complaining."),
    ("Here's where it gets interesting: the smallest gym had the highest retention.",
     "The smallest gym had the highest retention."),
    ("Here's the kicker: the backup register was the one that broke.",
     "The backup register was the one that broke."),
    ("Here's the thing about the schedule: it changed twice in one week.",
     "The schedule changed twice in one week."),
    ("Here's where it gets interesting: both stores restocked the same day.",
     "Both stores restocked the same day."),
    ("Here's the kicker: the delay actually boosted weekend sales.",
     "The delay actually boosted weekend sales."),
    ("Here's the thing about the numbers: they exclude online orders.",
     "The numbers exclude online orders."),
    ("Here's where it gets interesting: the cheapest vendor was also the fastest.",
     "The cheapest vendor was also the fastest."),
    ("Here's the kicker: the new hire found the pricing error in an hour.",
     "The new hire found the pricing error in an hour."),
    ("Here's the thing: the quietest league had the biggest turnout.",
     "The quietest league had the biggest turnout."),
    ("Here's where it gets interesting: the rain actually helped weekend traffic.",
     "The rain actually helped weekend traffic."),
],
"Think of It As": [
    ("Think of the loyalty program like a punch card for the whole store.",
     "The loyalty program works like a punch card for the whole store."),
    ("Think of the return counter as a safety net for bad purchases.",
     "The return counter is a safety net for bad purchases."),
    ("Think of the warm-up drill as a rehearsal before the real game.",
     "The warm-up drill is a rehearsal before the real game."),
    ("Think of onboarding as planting seeds for long-term staff retention.",
     "Good onboarding improves long-term staff retention."),
    ("Think of the front desk as the store's first impression.",
     "The front desk shapes the store's first impression."),
    ("Think of inventory counts like a checkup for the whole store.",
     "Inventory counts work like a checkup for the whole store."),
    ("Think of the budget as a leash that keeps overtime in check.",
     "The budget keeps overtime in check."),
    ("Think of the practice log as a diary of the season's progress.",
     "The practice log tracks the season's progress."),
    ("Think of the new signage as a map for first-time visitors.",
     "The new signage helps guide first-time visitors."),
    ("Think of the maintenance schedule as insurance against breakdowns.",
     "The maintenance schedule reduces the risk of breakdowns."),
    ("Think of the trial membership as a test drive for the gym.",
     "The trial membership lets people try the gym first."),
    ("Think of restocking day as a reset button for the shelves.",
     "Restocking day resets the shelves."),
],
"Imagine a World Where": [
    ("Imagine a world where every store restocks the same day items sell out.",
     "Same-day restocking could become standard for stores."),
    ("Imagine a world where returns never require a receipt.",
     "Receipt-free returns could become standard."),
    ("Imagine a world where every gym membership adjusts to how often you go.",
     "Gym memberships could eventually adjust to usage."),
    ("Imagine a world where no shipment ever misses its delivery window.",
     "Better logistics could reduce missed delivery windows."),
    ("Imagine a world where every league schedule avoided rainouts.",
     "Better scheduling could reduce weather-related cancellations."),
    ("Imagine a world where checkout never takes more than a minute.",
     "Faster checkout systems could reduce wait times."),
    ("Imagine a world where every rec center had enough court time for everyone.",
     "More court time could become available at rec centers."),
    ("Imagine a world where price tags always matched what's at checkout.",
     "Better systems could keep price tags accurate."),
    ("Imagine a world where every warehouse ran without a single misship.",
     "Better tracking could reduce misshipments."),
    ("Imagine a world where practice never got rained out.",
     "Indoor facilities could reduce rained-out practices."),
    ("Imagine a world where every customer complaint got resolved same day.",
     "Faster response times could resolve complaints sooner."),
    ("Imagine a world where inventory counts took an hour, not a week.",
     "Better tools could speed up inventory counts."),
],
"False Vulnerability": [
    ("I'll admit it, I doubted the new schedule would work, and it did.",
     "The new schedule worked despite my doubts."),
    ("I'm not too proud to say I misjudged how busy the holiday rush would be.",
     "The holiday rush was busier than expected."),
    ("Honestly, I was nervous about the new register system, and it turned out fine.",
     "The new register system turned out fine despite initial concerns."),
    ("I'll be the first to admit I underestimated how long inventory would take.",
     "Inventory took longer than expected."),
    ("Confession: I almost canceled the tournament over the weather forecast.",
     "The tournament was almost canceled over the weather forecast."),
    ("I used to think the loyalty program was a waste, and I was wrong.",
     "The loyalty program turned out to be worthwhile."),
    ("I won't pretend the move to the new location was smooth.",
     "The move to the new location wasn't smooth."),
    ("I'll admit, I got emotional when the team won the league title.",
     "I was emotional when the team won the league title."),
    ("I'm not ashamed to say the first budget draft had a big error.",
     "The first budget draft had a big error."),
    ("Honestly, I was skeptical of the new supplier, and they proved reliable.",
     "The new supplier proved reliable despite initial skepticism."),
    ("I'll admit it: I nearly closed the shop during the slow season.",
     "The shop was nearly closed during the slow season."),
    ("I used to doubt online orders would matter, and this quarter proved me wrong.",
     "Online orders mattered more than expected this quarter."),
],
"The Truth Is Simple": [
    ("The truth is simple: the store ran out of staff, not stock.",
     "The store ran out of staff, not stock."),
    ("The reality is simpler than people admit: the delay was a paperwork issue.",
     "The delay was a paperwork issue."),
    ("The truth is simple: most complaints are about parking, not service.",
     "Most complaints are about parking, not service."),
    ("The reality is simple: the field closed because of drainage, not budget.",
     "The field closed because of drainage, not budget."),
    ("The truth is simple: the team lost because of fouls, not skill.",
     "The team lost because of fouls, not skill."),
    ("The reality is simpler than the report suggests: the delay was one late truck.",
     "The delay was one late truck."),
    ("The truth is simple: fewer people signed up this season than last.",
     "Fewer people signed up this season than last."),
    ("The reality is simple: the register glitch was a software update.",
     "The register glitch was a software update."),
    ("The truth is simple: attendance dropped because of ticket prices.",
     "Attendance dropped because of ticket prices."),
    ("The reality is simpler than it sounds: the shop needs paint, not renovation.",
     "The shop needs paint, not renovation."),
    ("The truth is simple: the warehouse struggled because of one broken forklift.",
     "The warehouse struggled because of one broken forklift."),
    ("The reality is simple: wait times grew because two clerks quit.",
     "Wait times grew because two clerks quit."),
],
"Grandiose Stakes Inflation": [
    ("This new loyalty card will change the entire future of local retail.",
     "This new loyalty card offers a small discount to regular shoppers."),
    ("This one repaved lot marks a turning point for the whole downtown.",
     "This repaved lot fixed one parking issue downtown."),
    ("This is more than a bake sale; it's a movement that will redefine the block.",
     "This bake sale raised money for the block association."),
    ("This small shop will transform retail as we know it.",
     "This shop offers a new option for local shoppers."),
    ("This is the moment that changes everything for every small business here.",
     "This program will help a few small businesses this year."),
    ("This one drill will revolutionize how the whole league trains.",
     "This drill offers one new training option for the league."),
    ("This gym renovation isn't just a remodel; it's a rebirth for the whole town.",
     "This gym renovation adds new equipment and better lighting."),
    ("This youth clinic will shape the destiny of an entire generation of athletes.",
     "This youth clinic will coach twenty kids this summer."),
    ("This new trail redefines what it means to be an outdoor community.",
     "This new trail adds a mile of path near downtown."),
    ("This is the single decision that will determine the fate of the whole season.",
     "This decision affects next month's schedule."),
    ("This tutoring hour isn't just help with homework; it's a life-altering intervention.",
     "This tutoring hour covers this week's homework."),
    ("This community garden will change the course of the entire neighborhood's food supply.",
     "This community garden supplies vegetables to a few nearby households."),
],
"Let's Break This Down": [
    ("Let's break this down step by step, starting with the delivery schedule.",
     "Here is the delivery schedule."),
    ("Let's unpack this a bit: first the injury, then the recovery plan.",
     "Here is the injury and the recovery plan."),
    ("Let's walk through the return policy together, one step at a time.",
     "Here is the return policy."),
    ("To make this simple, let's go through the inventory count slowly.",
     "Here is the inventory count."),
    ("Let's break this down so the tournament bracket is easier to follow.",
     "Here is the tournament bracket."),
    ("Let's take a moment to break down what caused the register error.",
     "Here is what caused the register error."),
    ("Let's break the drill into smaller, easier pieces.",
     "Here is the drill, broken into smaller pieces."),
    ("Let's simplify this and go through the shipping schedule one step at a time.",
     "Here is the shipping schedule."),
    ("Let's break down exactly why sales dipped this month.",
     "Here is why sales dipped this month."),
    ("Let's walk through the checkout form together, field by field.",
     "Here is the checkout form, field by field."),
    ("Let's break this down: first the symptoms, then the treatment.",
     "Here are the symptoms and the treatment."),
    ("Let's unpack the new schedule and what it means for staff.",
     "Here is the new schedule and what it means for staff."),
],
"Vague Attributions": [
    ("Experts say the shortage will ease by next quarter.",
     "The state retail association says the shortage will ease by next quarter."),
    ("Observers note foot traffic has fallen downtown this year.",
     "The downtown merchants' group notes foot traffic has fallen this year."),
    ("Reports suggest the store may extend hours next season.",
     "An internal memo suggests the store may extend hours next season."),
    ("Some say the new layout is easier to shop.",
     "Three customer surveys say the new layout is easier to shop."),
    ("Critics argue the new fee will hurt small vendors.",
     "The vendors' association argues the new fee will hurt small vendors."),
    ("It is widely believed that the loyalty program boosts repeat visits.",
     "A 2024 internal study found the loyalty program boosts repeat visits."),
    ("Many experts warn of a slow holiday season this year.",
     "Retail analysts warn of a slow holiday season this year."),
    ("Sources close to the league say the schedule may change again.",
     "Two coaches say the schedule may change again."),
    ("Analysts believe the new store location will do well.",
     "Local market analysts believe the new store location will do well."),
    ("Some researchers claim the new checkout flow improves satisfaction.",
     "A university study claims the new checkout flow improves satisfaction."),
    ("Officials say the road closure will last through the season.",
     "The city's public works office says the road closure will last through the season."),
    ("People believe the market's prices are lower than the chain store's.",
     "A price comparison by the local paper found the market's prices are lower."),
],
"Invented Concept Labels": [
    ("This is a textbook case of the discount trap: markdowns train customers to wait for sales.",
     "This shows how markdowns can train customers to wait for sales."),
    ("We're witnessing the restock lag play out again this month.",
     "We're seeing how restocking delays are affecting sales again this month."),
    ("This is what I call the loyalty ceiling every rewards program eventually hits.",
     "This is the point where a rewards program stops driving more visits."),
    ("Call it the checkout drift: each new step slightly slows the line.",
     "Each new checkout step has slightly slowed the line."),
    ("This is the classic staffing cliff every seasonal business eventually hits.",
     "This is the point where seasonal staffing stops keeping up with demand."),
    ("We're seeing the complaint spiral: one bad review draws three more.",
     "One bad review seems to draw more complaints."),
    ("This is the return debt nobody accounts for until the holidays.",
     "This is the extra workload returns create after the holidays."),
    ("Call it the onboarding cliff: new clerks drop off after the first week.",
     "New clerks tend to drop off after the first week."),
    ("This is the classic complexity tax of adding one more product line.",
     "Each new product line adds more work to manage."),
    ("We're in what I'd call the trust deficit phase after the recall.",
     "Customers currently distrust the store after the recall."),
    ("This is a clear case of the referral cliff after the ad campaign ended.",
     "Referrals dropped sharply after the ad campaign ended."),
    ("Call it the second-season slump every new coach seems to hit.",
     "Many new coaches experience a difficult second season."),
],
"Em-Dash Addiction": [
    ("The delay -- and this is the part nobody mentions -- came from customs.",
     "The delay, which nobody mentions, came from customs."),
    ("The fix was simple -- almost too simple -- a replaced fuse.",
     "The fix was a replaced fuse."),
    ("She didn't hesitate -- not even for a second -- before refunding it.",
     "She refunded it without hesitation."),
    ("The opening went well -- better than expected -- despite the rain.",
     "The opening went better than expected despite the rain."),
    ("The budget -- already tight -- shrank further after the price hike.",
     "The already tight budget shrank further after the price hike."),
    ("He rebuilt the display -- twice -- before the manager approved it.",
     "He rebuilt the display twice before the manager approved it."),
    ("The outage -- brief but costly -- forced the store to close early.",
     "The brief but costly outage forced the store to close early."),
    ("The plan -- ambitious to say the least -- needed two more clerks.",
     "The ambitious plan needed two more clerks."),
    ("The customer -- understandably frustrated -- asked for a manager.",
     "The frustrated customer asked for a manager."),
    ("The results -- surprising to everyone -- reversed the earlier decision.",
     "The surprising results reversed the earlier decision."),
    ("The shipment -- delayed twice already -- finally arrived Friday.",
     "The twice-delayed shipment finally arrived Friday."),
    ("The register -- old but reliable -- finally gave out this week.",
     "The old but reliable register finally gave out this week."),
],
"Bold-First Bullets": [
    ("- **Turnout:** the tournament drew a record crowd.\n- **Weather:** clear skies all weekend.",
     "- The tournament drew a record crowd.\n- The weather was clear all weekend."),
    ("- **Sales:** holiday revenue beat last year's.\n- **Returns:** fewer than usual this season.",
     "- Holiday revenue beat last year's.\n- Returns were fewer than usual this season."),
    ("- **Speed:** checkout lines moved faster with the new registers.\n- **Cost:** the upgrade paid for itself in two months.",
     "- Checkout lines moved faster with the new registers.\n- The upgrade paid for itself in two months."),
    ("- **Attendance:** the clinic saw more walk-ins this month.\n- **Wait times:** average wait dropped by ten minutes.",
     "- The clinic saw more walk-ins this month.\n- Average wait dropped by ten minutes."),
    ("- **Yield:** the greenhouse produced more tomatoes than last year.\n- **Quality:** fewer were damaged in shipping.",
     "- The greenhouse produced more tomatoes than last year.\n- Fewer were damaged in shipping."),
    ("- **Turnout:** more kids joined the swim team this year.\n- **Results:** the team set two new records.",
     "- More kids joined the swim team this year.\n- The team set two new records."),
    ("- **Savings:** the new lights cut the store's power bill.\n- **Comfort:** customers noticed the brighter aisles.",
     "- The new lights cut the store's power bill.\n- Customers noticed the brighter aisles."),
    ("- **Freshness:** the deli restocks twice a day.\n- **Variety:** three new items were added this month.",
     "- The deli restocks twice a day.\n- Three new items were added this month."),
    ("- **Enrollment:** the workshop filled up in a day.\n- **Feedback:** most attendees rated it highly.",
     "- The workshop filled up in a day.\n- Most attendees rated it highly."),
    ("- **Recovery:** patients left the clinic sooner on average.\n- **Satisfaction:** survey scores rose.",
     "- Patients left the clinic sooner on average.\n- Survey scores rose."),
    ("- **Traffic:** the new crosswalk cut wait times at the corner.\n- **Safety:** incidents there dropped to zero.",
     "- The new crosswalk cut wait times at the corner.\n- Incidents there dropped to zero."),
    ("- **Turnaround:** repairs now take a day instead of three.\n- **Cost:** parts spending dropped.",
     "- Repairs now take a day instead of three.\n- Parts spending dropped."),
],
"Unicode Decoration": [
    ("The order goes Pick → Pack → Ship.", "The order process has three steps: pick, pack, then ship."),
    ("Membership tiers go Bronze → Silver → Gold.", "Membership tiers go from Bronze to Silver to Gold."),
    ("Revenue moved $500K → $1.2M this year.", "Revenue moved from $500K to $1.2M this year."),
    ("The pipeline runs Scan → Sort → Shelve.", "The pipeline scans, sorts, then shelves items."),
    ("Their process is Idea → Sample → Shelf.", "Their process moves from idea to sample to shelf."),
    ("Requests flow Counter → Stockroom → Truck.", "Requests flow from the counter through the stockroom to the truck."),
    ("The funnel is Browse → Cart → Checkout.", "The funnel moves from browsing to cart to checkout."),
    ("Status changed from Ordered → Packed → Delivered.", "The status changed from ordered to packed to delivered."),
    ("The upgrade path is Basic → Plus → Pro.", "The upgrade path goes from Basic to Plus to Pro."),
    ("Feedback loop: Stock → Sell → Restock.", "The feedback loop is stock, sell, then restock."),
    ("The route goes Warehouse → Dock → Store.", "The route goes from the warehouse to the dock to the store."),
    ("Season progress: Practice → Scrimmage → Playoffs.", "The season moves from practice to scrimmage to playoffs."),
],
"The Signposted Conclusion": [
    ("In conclusion, the new registers cut checkout time significantly.",
     "The new registers cut checkout time significantly."),
    ("To sum up, the season ended with the best record in five years.",
     "The season ended with the best record in five years."),
    ("In summary, the renovation improved foot traffic by 15%.",
     "The renovation improved foot traffic by 15%."),
    ("In conclusion, the store should prioritize restocking over new displays next quarter.",
     "The store should prioritize restocking over new displays next quarter."),
    ("To conclude, the trial program met all of its goals.",
     "The trial program met all of its goals."),
    ("In summary, the vendor switch saved the shop $8,000 a year.",
     "The vendor switch saved the shop $8,000 a year."),
    ("In conclusion, more testing is needed before the wider rollout.",
     "More testing is needed before the wider rollout."),
    ("To wrap up, the survey results support the new layout.",
     "The survey results support the new layout."),
    ("In conclusion, the new schedule reduced overtime significantly.",
     "The new schedule reduced overtime significantly."),
    ("In summary, both vendors have merit depending on the season.",
     "Both vendors have merit depending on the season."),
    ("In conclusion, the loyalty program drove repeat visits this quarter.",
     "The loyalty program drove repeat visits this quarter."),
    ("To sum up, the new hours improved staff morale.",
     "The new hours improved staff morale."),
],
"Despite Its Challenges": [
    ("Despite the supply shortage, the store kept shelves stocked.",
     "The supply shortage left some shelves under-stocked."),
    ("Despite the staffing gap, the shop kept its weekend hours.",
     "The staffing gap forced the shop to cut its weekend hours."),
    ("Despite the budget cuts, the league expanded its youth program.",
     "The budget cuts forced the league to scale back its youth program."),
    ("Despite the delays, the store opened on schedule.",
     "The delays pushed the store's opening back by a month."),
    ("Despite the criticism, the new pricing has strong support.",
     "The criticism reflects real concerns from customers about the new pricing."),
    ("Despite the setbacks, the tournament drew a record crowd.",
     "The setbacks reduced turnout at the tournament."),
    ("Despite its cost, the new register system improved checkout speed.",
     "The new register system's cost strained the store's budget."),
    ("Despite the frost, the greenhouse yield held steady.",
     "The frost reduced the greenhouse yield this year."),
    ("Despite early resistance, the loyalty app is now widely used.",
     "Early resistance to the loyalty app has kept adoption low."),
    ("Despite the setback, the team made the playoffs.",
     "The setback ended the team's chances of making the playoffs."),
    ("Despite the flooding, the shop reopened within a week.",
     "The flooding kept the shop closed for over a month."),
    ("Despite the shortage, the store restocked everyone's order on time.",
     "The shortage delayed several customer orders by weeks."),
],
"One-Point Dilution": [
    ("The store was understaffed. There weren't enough clerks. Shifts went uncovered. People were stretched thin. Coverage gaps appeared weekly.",
     "The store was understaffed."),
    ("The shipment was late. The route ran long. Weather delayed it. Timing was off. Everything shifted back.",
     "The shipment was late."),
    ("Communication failed at the warehouse. Nobody updated the manifest. Shifts overlapped. Workers were confused. Nothing was tracked.",
     "Communication failed at the warehouse."),
    ("The budget fell short. Funding was cut. Sponsorships didn't come through. Donations dropped. Money ran out.",
     "The budget fell short."),
    ("The store layout was confusing. Customers got lost. Signage wasn't clear. Aisles were cluttered. People couldn't find what they needed.",
     "The store layout was confusing."),
    ("Quality checks were skipped. Inspectors didn't have time. Defects went unnoticed. Nothing was verified. Checks were rushed.",
     "Quality checks were skipped."),
    ("The onboarding was too long. New clerks felt overwhelmed. There was too much to learn. The process dragged on. People lost momentum.",
     "The onboarding was too long."),
    ("Expectations weren't set. Nobody knew the sales targets. Priorities were unclear. Direction was missing. The team lacked focus.",
     "Expectations weren't set."),
    ("The vendor was unreliable. Deliveries were late. Quality was inconsistent. Support was slow. Communication was poor.",
     "The vendor was unreliable."),
    ("The season opener was chaotic. Timing was off. Coordination failed. Staff weren't aligned. Nothing went as planned.",
     "The season opener was chaotic."),
    ("The checkout line moved slowly. Registers glitched. Staff were confused. Customers waited. Nothing was tested beforehand.",
     "The checkout line moved slowly."),
    ("The rollout was chaotic. Timing slipped. Vendors weren't coordinated. Staff weren't briefed. Nothing ran on schedule.",
     "The rollout was chaotic."),
],
"False Ranges": [
    ("The workshop covers everything from budgeting to conflict resolution.",
     "The workshop covers budgeting and conflict resolution."),
    ("Our services range from bike repair to grief counseling.",
     "We offer bike repair and grief counseling."),
    ("The exhibit spans from vintage cash registers to modern self-checkout.",
     "The exhibit includes vintage cash registers and a modern self-checkout display."),
    ("The course goes from basic first aid to advanced leadership.",
     "The course covers basic first aid and, separately, leadership skills."),
    ("Their offerings range from gift wrapping to financial planning.",
     "They offer gift wrapping and financial planning services."),
    ("The talk moved from supply chains to personal branding.",
     "The talk covered supply chains and, separately, personal branding."),
    ("The app handles everything from inventory tracking to therapy sessions.",
     "The app tracks inventory and connects users to therapists."),
    ("The curriculum spans from basic math to leadership philosophy.",
     "The curriculum covers basic math and, separately, leadership."),
    ("Solutions range from minor fixes to complete store redesigns.",
     "Solutions include minor fixes and, in some cases, full store redesigns."),
    ("The clinic's services range from checkups to career counseling.",
     "The clinic offers checkups and, separately, career counseling."),
    ("The festival covers everything from crafts to tax advice.",
     "The festival features crafts and, separately, a tax-advice booth."),
    ("The program spans from register training to retirement planning.",
     "The program covers register training and, separately, retirement planning."),
],
"Short Punchy Fragments": [
    ("The line moved. Slowly. For an hour.",
     "The line moved slowly for an hour."),
    ("The shipment arrived. Late. Without notice.",
     "The shipment arrived late, without notice."),
    ("She quit. On the spot. Mid-shift.",
     "She quit on the spot, mid-shift."),
    ("The register broke. At noon. During the rush.",
     "The register broke at noon, during the rush."),
    ("He said no. Twice. In writing.",
     "He said no twice, in writing."),
    ("The roof held. Barely. Through the storm.",
     "The roof held, barely, through the storm."),
    ("They rebuilt the display. Overnight. Before opening.",
     "They rebuilt the display overnight, before opening."),
    ("The sale ended. Early. Without warning.",
     "The sale ended early, without warning."),
    ("She won. Again. Three seasons running.",
     "She won again, for the third season running."),
    ("The data synced. Finally. After two failed attempts.",
     "The data finally synced, after two failed attempts."),
    ("He apologized. Publicly. The next morning.",
     "He apologized publicly the next morning."),
    ("The truck arrived. Early. Ahead of schedule.",
     "The truck arrived early, ahead of schedule."),
],
"Listicle in a Trench Coat": [
    ("The first issue is staffing. The second issue is inventory. The third issue is space.",
     "The main issues are staffing, inventory, and space."),
    ("The first mistake was understocking. The second mistake was ignoring complaints.",
     "The two mistakes were understocking and ignoring complaints."),
    ("The first step is counting inventory. The second step is placing orders. The third step is restocking shelves.",
     "The process involves counting inventory, placing orders, and restocking shelves."),
    ("The first reason is cost. The second reason is space. The third reason is staffing.",
     "The reasons are cost, space, and staffing."),
    ("The first sign was slower checkout. The second sign was longer lines.",
     "The warning signs were slower checkout and longer lines."),
    ("The first option is to wait. The second option is to expedite. The third option is to cancel.",
     "The options are to wait, expedite, or cancel."),
    ("The first phase focuses on cleanup. The second phase focuses on restocking.",
     "The project has a cleanup phase and a restocking phase."),
    ("The first challenge is the old register system. The second challenge is limited training time.",
     "The challenges are the old register system and limited training time."),
    ("The first group prefers morning shifts. The second group prefers evenings.",
     "Preferences split between morning and evening shifts."),
    ("The first benefit is speed. The second benefit is lower cost.",
     "The benefits are speed and lower cost."),
    ("The first vendor offers lower prices. The second vendor offers faster delivery.",
     "The vendors differ on price and delivery speed."),
    ("The first store opened downtown. The second store opened at the mall.",
     "One store opened downtown and another opened at the mall."),
],
"Historical Analogy Stacking": [
    ("The old five-and-dime closed. The hardware store closed. The bakery closed.",
     "Several local shops, including the five-and-dime, hardware store, and bakery, have closed over the years."),
    ("The 1980s brought the mall. The 2000s brought big-box stores. The 2010s brought online orders.",
     "New shopping options arrived in each of the last few decades."),
    ("The flood hit in 1985. It hit again in 2005. It hit again in 2019.",
     "The area has flooded roughly every couple of decades."),
    ("The shop started as a stall. It became a storefront. It became a chain.",
     "The shop grew over time from a stall into a small chain."),
    ("The farm started with corn. It added livestock. It added a farm stand.",
     "The farm expanded from corn into livestock and a farm stand over time."),
    ("The old dock flooded in 1990. The new one flooded in 2010. This one hasn't yet.",
     "Earlier docks at this site flooded in 1990 and 2010."),
    ("The union formed in the 1950s. It grew in the 1970s. It shrank in the 2000s.",
     "The union's membership has changed significantly since the 1950s."),
    ("The cinema opened as a single screen. It became a multiplex. It's now a community theater.",
     "The cinema has served several different purposes since it opened."),
    ("The league started with two teams. Then eight. Now over twenty.",
     "The league grew from two teams to over twenty."),
    ("The market began as a single truck. Then a row of stalls. Now a full building.",
     "The market grew from a single truck into a full building."),
    ("The store began with cash only. Then checks. Now none at all.",
     "The store's payment options have changed significantly over the years."),
    ("The shop survived the recession in '08. It survived the closures in '20. This year tested it again.",
     "The shop has survived a recession, closures, and other challenges over the years."),
],
"Content Duplication": [
    ("The store added self-checkout lanes this spring. The store added self-checkout lanes this spring.",
     "The store added self-checkout lanes this spring."),
    ("Sales grew 15% this quarter due to the new loyalty program. Sales grew 15% this quarter due to the new loyalty program.",
     "Sales grew 15% this quarter due to the new loyalty program."),
    ("The outage lasted an hour and affected online orders. The outage lasted an hour and affected online orders.",
     "The outage lasted an hour and affected online orders."),
    ("Our new membership tiers start at $15 a month. Our new membership tiers start at $15 a month.",
     "Our new membership tiers start at $15 a month."),
    ("The survey found most shoppers prefer curbside pickup. The survey found most shoppers prefer curbside pickup.",
     "The survey found most shoppers prefer curbside pickup."),
    ("The team clinched the division title two weeks early. The team clinched the division title two weeks early.",
     "The team clinched the division title two weeks early."),
    ("The new warehouse opens next spring. The new warehouse opens next spring.",
     "The new warehouse opens next spring."),
    ("The report covers Q3 sales and returns in detail. The report covers Q3 sales and returns in detail.",
     "The report covers Q3 sales and returns in detail."),
    ("The gym added weekend classes starting this month. The gym added weekend classes starting this month.",
     "The gym added weekend classes starting this month."),
    ("The update fixes the checkout bug reported last week. The update fixes the checkout bug reported last week.",
     "The update fixes the checkout bug reported last week."),
    ("The shop extended its return window to sixty days. The shop extended its return window to sixty days.",
     "The shop extended its return window to sixty days."),
    ("The league added a new division this season. The league added a new division this season.",
     "The league added a new division this season."),
],
"Fractal Summaries": [
    ("This section covers the restocking schedule. As we've seen, the restocking schedule was covered above.",
     "This section covers the restocking schedule."),
    ("We'll review the store's new hours below. As reviewed above, the store added new hours.",
     "The store added new hours, reviewed below."),
    ("This chapter explains the three checkout lanes. As explained, there are three lanes as covered here.",
     "This chapter explains the three checkout lanes."),
    ("The next part covers vendor requirements. As covered next, vendor requirements are detailed below.",
     "The next part covers vendor requirements."),
    ("This guide explains intake in four steps. As we've just seen, intake takes four steps as explained.",
     "This guide explains the four-step intake process."),
    ("Below we summarize this quarter's sales. As summarized above, sales were strong this quarter.",
     "Sales were strong this quarter, summarized below."),
    ("This section outlines the new delivery routes. As outlined above, three new routes were added.",
     "This section outlines the three new delivery routes."),
    ("We will now review the season timeline. As reviewed, the season ran twelve weeks as noted.",
     "The season timeline, reviewed below, ran twelve weeks."),
    ("This part covers shift schedules. As covered, shifts run in four-hour blocks as detailed here.",
     "This part covers the four-hour shift blocks."),
    ("The following section explains the return policy. As explained above, returns are accepted within sixty days.",
     "The following section explains the sixty-day return policy."),
    ("This chapter introduces the store's referral process. As introduced, referrals go through the loyalty app.",
     "This chapter introduces the store's referral process, which goes through the loyalty app."),
    ("Below we cover the store's restock schedule. As covered above, restocks happen every Tuesday.",
     "The store's restock schedule, covered below, happens every Tuesday."),
],
"Anaphora Abuse": [
    ("They assume the shipment will arrive on time. They assume the staff will cover the shift. They assume the weather will hold.",
     "They assume the shipment will arrive on time, the staff will cover the shift, and the weather will hold."),
    ("We believe in fair prices. We believe in honest service. We believe in local sourcing.",
     "We believe in fair prices, honest service, and local sourcing."),
    ("This is a story about a small shop. This is a story about hard times. This is a story about rebuilding.",
     "This is a story about a small shop, hard times, and rebuilding."),
    ("Every store wants more staff. Every store wants more space. Every store wants more inventory.",
     "Every store wants more staff, space, and inventory."),
    ("She checked the shelves alone. She restocked them alone. She reported the shortage alone.",
     "She checked, restocked, and reported on the shelves alone."),
    ("The report ignores the delays. The report ignores the shortages. The report ignores the complaints.",
     "The report ignores the delays, shortages, and complaints."),
    ("We need better signage. We need better lighting. We need better parking.",
     "We need better signage, lighting, and parking."),
    ("He checked the registers twice. He checked the registers three times. He still found the discrepancy.",
     "He checked the registers several times and still found the discrepancy."),
    ("The store promised faster checkout. The store promised lower prices. The store promised better service.",
     "The store promised faster checkout, lower prices, and better service."),
    ("This changes how we order. This changes how we restock. This changes how we sell.",
     "This changes how we order, restock, and sell."),
    ("They wanted more staff. They wanted less overtime. They wanted a longer holiday season.",
     "They wanted more staff, less overtime, and a longer holiday season."),
    ("She trained every morning. She trained every evening. She trained on weekends too.",
     "She trained every morning, evening, and weekend."),
],
"It's Worth Noting": [
    ("It's worth noting that the store's new hours only apply on weekdays.",
     "The store's new hours only apply on weekdays."),
    ("Importantly, the warranty requires the original receipt.",
     "The warranty requires the original receipt."),
    ("Interestingly, the smaller stores had higher customer satisfaction.",
     "The smaller stores had higher customer satisfaction."),
    ("Notably, none of the new hires had prior retail experience.",
     "None of the new hires had prior retail experience."),
    ("It's worth noting that the register upgrade is temporary.",
     "The register upgrade is temporary."),
    ("Importantly, this promotion requires a minimum purchase.",
     "This promotion requires a minimum purchase."),
    ("It's worth mentioning that the shipment was tested just last week.",
     "The shipment was tested just last week."),
    ("Interestingly, the two stores reached the same pricing independently.",
     "The two stores reached the same pricing independently."),
    ("Notably, the restock finished faster than any week on record.",
     "The restock finished faster than any week on record."),
    ("It's worth noting that the survey only reached half the customers.",
     "The survey only reached half the customers."),
    ("Importantly, the store's new return form takes half the time.",
     "The store's new return form takes half the time."),
    ("It's worth noting the lot closes early during the holiday season.",
     "The lot closes early during the holiday season."),
],
"Tricolon Abuse": [
    ("The shop restocks, the shop delivers, the shop repairs.",
     "The shop restocks, delivers, and repairs."),
    ("Good staff greet, good staff assist, good staff follow up.",
     "Good staff greet, assist, and follow up with customers."),
    ("It's faster. It's cheaper. It's easier.",
     "It's faster, cheaper, and easier."),
    ("Great teams communicate; great teams collaborate; great teams commit; great teams deliver.",
     "Great teams communicate, collaborate, and commit to what they deliver."),
    ("The season failed because of injuries, because of scheduling, because of budget, because of morale.",
     "The season failed because of injuries, scheduling, and budget."),
    ("Speed matters. Price matters. Trust matters.",
     "Speed, price, and trust all matter."),
    ("She led with patience, with clarity, with humor, and with grit.",
     "She led with patience, clarity, and grit."),
    ("This system automates, accelerates, simplifies, and standardizes checkout.",
     "This system automates and simplifies checkout."),
    ("The bridge connects towns, connects markets, connects families.",
     "The bridge connects towns and markets."),
    ("Good inventory tracking is accurate, timely, and clear.",
     "Good inventory tracking is accurate, timely, and clear."),
    ("The store restocks daily, delivers weekly, repairs monthly.",
     "The store restocks daily and delivers weekly."),
    ("The plan improves speed, improves cost, improves reliability.",
     "The plan improves speed, cost, and reliability."),
],
"Superficial Analyses": [
    ("The bakery opened a second location, extending its role in the block's daily rhythm.",
     "The bakery opened a second location."),
    ("The clerk finished the count early, reflecting her efficient approach to inventory.",
     "The clerk finished the count early."),
    ("The farmer rotated the crops this season, deepening the soil's long-term fertility.",
     "The farmer rotated the crops this season."),
    ("The team practiced an extra hour, underscoring their dedication to the championship.",
     "The team practiced an extra hour."),
    ("The shop added a new scanner, further advancing its commitment to modern service.",
     "The shop added a new scanner."),
    ("The choir rehearsed on Sunday, reinforcing the community's shared love of music.",
     "The choir rehearsed on Sunday."),
    ("The store extended its hours, reflecting a broader dedication to customer convenience.",
     "The store extended its hours."),
    ("The runner logged an extra mile, showcasing her disciplined training regimen.",
     "The runner logged an extra mile."),
    ("The council repaved the lot, signaling a renewed investment in local infrastructure.",
     "The council repaved the lot."),
    ("The manager stayed late, further demonstrating her commitment to the team.",
     "The manager stayed late."),
    ("The store added recycling bins, enriching its role in the community's sustainability efforts.",
     "The store added recycling bins."),
    ("The shop hired a translator, reflecting its broader mission of accessible service.",
     "The shop hired a translator."),
],
"The Dead Metaphor": [
    ("The store is an engine, and the engine's parts keep the store-engine running.",
     "The store operates efficiently this season."),
    ("The season is a marathon, and every mile of the marathon tests the season's runners.",
     "The season is long and tests the team's endurance."),
    ("The shop is a garden, and the garden's seeds sprout into the garden of customers.",
     "The shop attracts new customers over time."),
    ("The budget is a ship, and the ship's crew steers the budget-ship through rough seas.",
     "The finance team manages the budget carefully."),
    ("The warehouse is a river, and the river's current carries the warehouse's flow of goods.",
     "The warehouse handles a steady flow of goods."),
    ("The team is a puzzle, and the puzzle pieces of the team finally fit the puzzle together.",
     "The team's roles finally work well together."),
    ("The store is a stage, and every sale performed on that stage tells the store's story.",
     "The store handles a variety of sales each day."),
    ("The program is a ladder, and every rung of the ladder lifts customers up the ladder.",
     "The program helps customers advance step by step."),
    ("The festival is a tapestry, woven from threads that make up the festival's tapestry.",
     "The festival brings together many different local vendors."),
    ("The shop is a compass, pointing customers toward the compass heading of good deals.",
     "The shop helps guide customers toward good deals."),
    ("The season is a journey, and every step of the journey continues the season's journey.",
     "The season progresses step by step."),
    ("The store is a foundation, resting on the foundation of that same foundation.",
     "The store relies on decisions made early on."),
],
}


def main():
    tropes = read_tropes()
    name_to_id = dict(zip(tropes.column("name").to_pylist(), tropes.column("trope_id").to_pylist()))

    doc_rows, sent_rows, label_rows, rewrite_rows = [], [], [], []

    for name, pairs in PAIRS.items():
        trope_id = name_to_id[name]
        for positive, rewrite in pairs:
            pos_ids = _insert_document(positive, True, True, doc_rows, sent_rows)
            rewrite_ids = _insert_document(rewrite, True, False, doc_rows, sent_rows)
            for sid in pos_ids:
                label_rows.append({
                    "sentence_id": sid, "trope_id": trope_id,
                    "label_source": "synthetic-gen", "confidence": 1.0,
                })
            if pos_ids and rewrite_ids:
                rewrite_rows.append({
                    "rewrite_id": str(uuid.uuid5(REWRITE_NAMESPACE, pos_ids[0])),
                    "sentence_id": pos_ids[0], "trope_id": trope_id,
                    "rewritten_text": rewrite.strip(), "source": "synthetic-gen",
                })

    append_rows(SOURCE_DOCUMENT_PATH, doc_rows)
    append_rows(SENTENCE_PATH, sent_rows)
    append_rows(SENTENCE_TROPE_LABEL_PATH, label_rows)
    append_rows(SENTENCE_REWRITE_PATH, rewrite_rows)
    print(f"round 3: {len(doc_rows)} docs, {len(label_rows)} labels, {len(rewrite_rows)} rewrite pairs")

    rw = read_table(SENTENCE_REWRITE_PATH).to_pandas().merge(tropes.to_pandas(), on="trope_id")
    print(rw.groupby("name").size().sort_values())


if __name__ == "__main__":
    main()
