# SPDX-License-Identifier: MIT
# Copyright (c) 2026 K. S. Ernest (iFire) Lee
"""
Hand-authored synthetic (trope-positive, clean-rewrite) pairs for all 33
tropes, plus clean negatives -- written directly rather than generated via
scripts/synth_generate.py's LLM call, since that script needs a live
ANTHROPIC_API_KEY this environment doesn't have. This is the same shape of
output synth_generate.py would produce (same tables, same label_source=
"synthetic-gen"), just authored inline so the datalake has real per-trope
coverage without requiring an API key to build.

Covers every trope with 10+ pairs, prioritizing the 16 tropes seed_labels.py
found zero examples for (composition/tone patterns that aren't regex-
matchable) plus the handful of others seed-regex only found 2-6 of.

Re-running is idempotent: documents are keyed by sha256 of their text, same
as fetch_corpus.py and synth_generate.py.
"""
import sys

sys.path.insert(0, __file__.rsplit("scripts", 1)[0])
from runtime.datalake import (
    SENTENCE_PATH, SENTENCE_REWRITE_PATH, SENTENCE_TROPE_LABEL_PATH,
    SOURCE_DOCUMENT_PATH, append_rows, read_tropes,
)
from scripts.synth_generate import DOC_NAMESPACE, SENT_NAMESPACE, REWRITE_NAMESPACE, _insert_document
import uuid

# name -> list of (positive_text, rewrite_text)
PAIRS = {
"Quietly and Other Magic Adverbs": [
    ("The new caching layer is quietly transforming how the service handles peak traffic.",
     "The new caching layer changed how the service handles peak traffic."),
    ("Beneath the surface, the algorithm is quietly reshaping which articles readers see first.",
     "The algorithm changed which articles readers see first."),
    ("The committee's decision fundamentally altered the trajectory of the program.",
     "The committee's decision changed the program's direction."),
    ("Her feedback deeply influenced how the team approached the redesign.",
     "Her feedback changed how the team approached the redesign."),
    ("The update is quietly reworking the recommendation engine behind the scenes.",
     "The update changed the recommendation engine."),
    ("This small policy shift is remarkably reshaping how residents commute downtown.",
     "This policy shift changed how residents commute downtown."),
    ("The new irrigation schedule is quietly improving crop yields across the valley.",
     "The new irrigation schedule improved crop yields across the valley."),
    ("Their mentorship program is fundamentally changing how new hires ramp up.",
     "Their mentorship program changed how new hires ramp up."),
    ("The library's late-night hours are quietly becoming a lifeline for students.",
     "Students increasingly rely on the library's late-night hours."),
    ("A single line of code was quietly rewriting how the whole pipeline behaved.",
     "A single line of code changed how the whole pipeline behaved."),
    ("The city's bike-lane expansion is deeply reshaping weekday traffic patterns.",
     "The city's bike-lane expansion changed weekday traffic patterns."),
],
"Delve and Friends": [
    ("Let's delve into the reasons behind the server outage.",
     "Here are the reasons behind the server outage."),
    ("We need to utilize the existing infrastructure before building anything new.",
     "We need to use the existing infrastructure before building anything new."),
    ("The team plans to leverage customer feedback to prioritize the roadmap.",
     "The team plans to use customer feedback to prioritize the roadmap."),
    ("This is a robust solution that streamlines the entire onboarding process.",
     "This solution simplifies the entire onboarding process."),
    ("To delve deeper into the data, we ran a cohort analysis.",
     "To understand the data better, we ran a cohort analysis."),
    ("The framework harnesses parallel processing to cut build times in half.",
     "The framework uses parallel processing to cut build times in half."),
    ("Certainly, the migration will require careful planning across every team.",
     "The migration will require careful planning across every team."),
    ("We should utilize the spare capacity on the weekend servers.",
     "We should use the spare capacity on the weekend servers."),
    ("Let's delve into why the quarterly numbers missed target.",
     "Here's why the quarterly numbers missed target."),
    ("The new API leverages caching to streamline repeated lookups.",
     "The new API uses caching to speed up repeated lookups."),
],
"Tapestry and Landscape": [
    ("The rich tapestry of the city's food scene reflects decades of immigration.",
     "The city's food scene reflects decades of immigration."),
    ("Navigating the landscape of modern payment systems requires understanding a few key protocols.",
     "Understanding modern payment systems requires knowing a few key protocols."),
    ("The startup's pitch leaned heavily on the paradigm of platform synergy.",
     "The startup's pitch focused on combining its products."),
    ("Our marketing ecosystem now spans five different channels.",
     "Our marketing now spans five different channels."),
    ("The novel weaves together a tapestry of voices from three generations.",
     "The novel follows voices from three generations."),
    ("The regulatory landscape shifted after the new law passed.",
     "Regulations changed after the new law passed."),
    ("This tool fits neatly into our broader data ecosystem.",
     "This tool fits neatly into our data tools."),
    ("The conference explored the shifting paradigm of remote work.",
     "The conference discussed how remote work is changing."),
    ("The garden's tapestry of colors peaks in late April.",
     "The garden's colors peak in late April."),
    ("Understanding the competitive landscape took the team three weeks.",
     "Understanding the competitors took the team three weeks."),
],
"The Serves As Dodge": [
    ("The old bridge serves as a reminder of the town's industrial past.",
     "The old bridge is a reminder of the town's industrial past."),
    ("This report serves as a starting point for next quarter's budget.",
     "This report is a starting point for next quarter's budget."),
    ("The mural stands as a tribute to the neighborhood's history.",
     "The mural is a tribute to the neighborhood's history."),
    ("Her promotion marks a turning point for the department.",
     "Her promotion is a turning point for the department."),
    ("The clause serves as protection against late payments.",
     "The clause protects against late payments."),
    ("The award serves as recognition of years of volunteer work.",
     "The award recognizes years of volunteer work."),
    ("This chapter serves as an introduction to the rest of the book.",
     "This chapter introduces the rest of the book."),
    ("The fence serves as a boundary between the two properties.",
     "The fence is the boundary between the two properties."),
    ("The pilot program serves as a test case for the citywide rollout.",
     "The pilot program is a test case for the citywide rollout."),
    ("This meeting serves as a checkpoint before the launch.",
     "This meeting is a checkpoint before the launch."),
],
"Negative Parallelism": [
    ("It's not bold. It's backwards.",
     "This isn't bold; it's backwards."),
    ("It's not a bug. It's a symptom of a deeper design flaw.",
     "This bug is a symptom of a deeper design flaw."),
    ("It's not about speed. It's about reliability.",
     "Reliability matters here more than speed."),
    ("It's not a redesign. It's a rebuild from scratch.",
     "This is a rebuild from scratch, not a redesign."),
    ("It's not luck. It's years of preparation.",
     "This came from years of preparation, not luck."),
    ("It's not a small tweak. It's a complete rewrite of the checkout flow.",
     "This is a complete rewrite of the checkout flow."),
    ("It's not that the team failed. It's that the deadline was unrealistic.",
     "The deadline was unrealistic, not the team's performance."),
    ("It's not innovation. It's imitation with a new coat of paint.",
     "This is imitation with a new coat of paint."),
    ("It's not a coincidence. It's the result of careful planning.",
     "This is the result of careful planning."),
    ("It's not a minor delay. It's a six-month setback.",
     "This is a six-month setback."),
],
"Not X. Not Y. Just Z.": [
    ("Not a bug. Not a feature. A fundamental design flaw.",
     "This is a fundamental design flaw, not a bug or a feature."),
    ("Not slow. Not broken. Just poorly documented.",
     "The tool is poorly documented, not slow or broken."),
    ("Not a trend. Not a fad. A permanent shift in how people shop.",
     "This is a permanent shift in how people shop."),
    ("Not carelessness. Not incompetence. Just an unrealistic deadline.",
     "An unrealistic deadline caused this, not carelessness or incompetence."),
    ("Not a warning. Not a suggestion. A requirement.",
     "This is a requirement."),
    ("Not luck. Not timing. Just years of practice.",
     "Years of practice explain this, not luck or timing."),
    ("Not a maybe. Not a someday. A decision made this week.",
     "This decision was made this week."),
    ("Not an accident. Not a glitch. A deliberate design choice.",
     "This was a deliberate design choice."),
    ("Not optional. Not a nice-to-have. Core to the release.",
     "This is core to the release."),
    ("Not a rumor. Not speculation. Confirmed in the filing.",
     "This is confirmed in the filing."),
],
"The X? A Y.": [
    ("The result? Devastating.",
     "The result was devastating."),
    ("The fix? A single line of configuration.",
     "The fix was a single line of configuration."),
    ("The cause? A misconfigured load balancer.",
     "A misconfigured load balancer caused it."),
    ("The outcome? A record quarter for the sales team.",
     "The sales team had a record quarter."),
    ("The verdict? Not guilty on all counts.",
     "The jury found the defendant not guilty on all counts."),
    ("The plan? Ship weekly instead of monthly.",
     "The plan is to ship weekly instead of monthly."),
    ("The reason? Nobody had tested the rollback path.",
     "Nobody had tested the rollback path."),
    ("The response? Silence from the vendor for two weeks.",
     "The vendor stayed silent for two weeks."),
    ("The upside? Costs dropped by a third.",
     "Costs dropped by a third."),
    ("The risk? A single point of failure in the payments service.",
     "The payments service has a single point of failure."),
],
"Anaphora Abuse": [
    ("They assume that users will read the docs. They assume that users will follow the setup guide. They assume that users have time to spare.",
     "They assume users will read the docs, follow the setup guide, and have time to spare."),
    ("We believe in shipping fast. We believe in listening to users. We believe in fixing bugs quickly.",
     "We believe in shipping fast, listening to users, and fixing bugs quickly."),
    ("This is a story about ambition. This is a story about failure. This is a story about starting over.",
     "This is a story about ambition, failure, and starting over."),
    ("Every team wants more headcount. Every team wants more budget. Every team wants more time.",
     "Every team wants more headcount, budget, and time."),
    ("She built the prototype alone. She tested it alone. She pitched it alone.",
     "She built, tested, and pitched the prototype alone."),
    ("The report ignores the delays. The report ignores the cost overruns. The report ignores the complaints.",
     "The report ignores the delays, cost overruns, and complaints."),
    ("We need better tools. We need better training. We need better support.",
     "We need better tools, training, and support."),
    ("He checked the logs twice. He checked the logs three times. He still found nothing.",
     "He checked the logs several times and still found nothing."),
    ("The city promised faster buses. The city promised cleaner stations. The city promised lower fares.",
     "The city promised faster buses, cleaner stations, and lower fares."),
    ("This changes how we hire. This changes how we onboard. This changes how we retain people.",
     "This changes how we hire, onboard, and retain people."),
],
"Tricolon Abuse": [
    ("Products impress; platforms empower. Products solve; platforms create. Products ship; platforms scale.",
     "Products solve individual problems, while platforms create the tools to scale those solutions."),
    ("We plan, we build, we ship, we learn, we repeat.",
     "We plan, build, and ship, then repeat based on what we learn."),
    ("It's faster. It's cheaper. It's simpler. It's better.",
     "It's faster, cheaper, and simpler."),
    ("Great teams communicate; great teams collaborate; great teams commit; great teams deliver.",
     "Great teams communicate, collaborate, and commit to what they deliver."),
    ("The plan failed because of poor timing, poor communication, poor budgeting, and poor follow-through.",
     "The plan failed because of poor timing, communication, and budgeting."),
    ("Speed matters. Quality matters. Cost matters. Trust matters.",
     "Speed, quality, and cost all matter."),
    ("She led with clarity, with confidence, with patience, and with humor.",
     "She led with clarity, confidence, and patience."),
    ("This tool automates, accelerates, simplifies, and standardizes the workflow.",
     "This tool automates and simplifies the workflow."),
    ("The bridge connects neighborhoods, connects generations, connects economies.",
     "The bridge connects neighborhoods and generations."),
    ("Good code is readable, testable, maintainable, and fast.",
     "Good code is readable, testable, and fast."),
],
"It's Worth Noting": [
    ("It's worth noting that this approach has limitations.",
     "This approach has limitations."),
    ("Importantly, the update only affects paid accounts.",
     "The update only affects paid accounts."),
    ("Interestingly, the bug only appears on Tuesdays.",
     "The bug only appears on Tuesdays."),
    ("Notably, none of the affected users filed a complaint.",
     "None of the affected users filed a complaint."),
    ("It's worth noting that the migration is reversible.",
     "The migration is reversible."),
    ("Importantly, this change requires a database backup first.",
     "This change requires a database backup first."),
    ("It's worth mentioning that the vendor changed their pricing last month.",
     "The vendor changed their pricing last month."),
    ("Interestingly, the two teams reached the same conclusion independently.",
     "The two teams reached the same conclusion independently."),
    ("Notably, the fix took less time than the investigation.",
     "The fix took less time than the investigation."),
    ("It's worth noting that the survey had a small sample size.",
     "The survey had a small sample size."),
],
"Superficial Analyses": [
    ("The festival draws thousands each year, contributing to the region's rich cultural heritage.",
     "The festival draws thousands of visitors to the region each year."),
    ("The bridge was completed on schedule, reflecting the contractor's strong project management.",
     "The bridge was completed on schedule."),
    ("The school added a new lab, further enriching the students' hands-on learning experience.",
     "The school added a new lab for hands-on learning."),
    ("She finished the marathon in under four hours, showcasing her months of disciplined training.",
     "She finished the marathon in under four hours."),
    ("The company opened a second office, signaling its growing confidence in the market.",
     "The company opened a second office."),
    ("The park added new trails, offering visitors a deeper connection to nature.",
     "The park added new trails."),
    ("The team shipped the feature a week early, demonstrating their commitment to excellence.",
     "The team shipped the feature a week early."),
    ("The museum extended its hours, reflecting a broader push toward accessibility.",
     "The museum extended its hours."),
    ("The recipe uses local produce, tying the dish to the region's agricultural roots.",
     "The recipe uses local produce."),
    ("The startup raised a new round, underscoring investor confidence in its long-term vision.",
     "The startup raised a new funding round."),
],
"False Ranges": [
    ("From innovation to implementation to cultural transformation, the project touched everything.",
     "The project touched product design, engineering, and company culture."),
    ("The workshop covers everything from cooking to career planning.",
     "The workshop covers cooking and career planning."),
    ("Our services range from web design to emotional wellness.",
     "We offer web design and wellness coaching."),
    ("The exhibit spans from ancient pottery to quantum computing.",
     "The exhibit includes ancient pottery and a quantum computing display."),
    ("The course goes from basic grammar to advanced diplomacy.",
     "The course covers basic grammar and, separately, negotiation skills."),
    ("Their product line ranges from kitchen tools to financial planning.",
     "They sell kitchen tools and offer financial planning services."),
    ("The talk moved from climate policy to personal branding.",
     "The talk covered climate policy and, separately, personal branding."),
    ("The app handles everything from grocery lists to therapy sessions.",
     "The app handles grocery lists and connects users to therapists."),
    ("The curriculum spans from coding basics to leadership philosophy.",
     "The curriculum covers coding basics and, separately, leadership."),
    ("Solutions range from small tweaks to complete organizational overhauls.",
     "Solutions include small tweaks and, in some cases, full reorganizations."),
],
"Short Punchy Fragments": [
    ("He published this. Openly. In a book. As a priest.",
     "He published this openly, in a book, as a priest."),
    ("She quit. On the spot. No notice.",
     "She quit on the spot, without notice."),
    ("The server crashed. At 3 a.m. During the sale.",
     "The server crashed at 3 a.m., during the sale."),
    ("He said no. Twice. In writing.",
     "He said no twice, in writing."),
    ("The bridge held. Barely. For now.",
     "The bridge held, barely, for now."),
    ("They rebuilt it. From scratch. In six weeks.",
     "They rebuilt it from scratch in six weeks."),
    ("The offer expired. Yesterday. Without warning.",
     "The offer expired yesterday, without warning."),
    ("She won. Again. Undefeated.",
     "She won again, remaining undefeated."),
    ("The data leaked. Internally. Before the announcement.",
     "The data leaked internally before the announcement."),
    ("He apologized. Publicly. Immediately.",
     "He apologized publicly and immediately."),
],
"Listicle in a Trench Coat": [
    ("The first wall is budget. The second wall is staffing. The third wall is time.",
     "The three main obstacles are budget, staffing, and time."),
    ("The first mistake was underestimating demand. The second mistake was ignoring early complaints.",
     "The two mistakes were underestimating demand and ignoring early complaints."),
    ("The first step is gathering requirements. The second step is drafting a proposal. The third step is getting sign-off.",
     "The process involves gathering requirements, drafting a proposal, and getting sign-off."),
    ("The first reason is cost. The second reason is complexity. The third reason is risk.",
     "The reasons are cost, complexity, and risk."),
    ("The first sign was slower load times. The second sign was rising error rates.",
     "The warning signs were slower load times and rising error rates."),
    ("The first option is to wait. The second option is to escalate. The third option is to cancel.",
     "The options are to wait, escalate, or cancel."),
    ("The first phase focuses on discovery. The second phase focuses on delivery.",
     "The project has a discovery phase and a delivery phase."),
    ("The first challenge is legacy code. The second challenge is limited documentation.",
     "The challenges are legacy code and limited documentation."),
    ("The first group prefers email. The second group prefers chat. The third group prefers calls.",
     "Preferences split across email, chat, and calls."),
    ("The first benefit is speed. The second benefit is lower cost.",
     "The benefits are speed and lower cost."),
],
"Here's the Kicker": [
    ("Here's the kicker: the fix took less time than the meeting about the fix.",
     "The fix took less time than the meeting about the fix."),
    ("Here's the thing: nobody actually read the proposal before approving it.",
     "Nobody actually read the proposal before approving it."),
    ("Here's where it gets interesting: the outage was caused by a routine backup.",
     "A routine backup caused the outage."),
    ("Here's the kicker: the winning bid was the lowest one submitted.",
     "The winning bid was the lowest one submitted."),
    ("Here's the thing: the bug had been reported a year earlier.",
     "The bug had been reported a year earlier."),
    ("Here's where it gets interesting: both teams built the same feature independently.",
     "Both teams built the same feature independently."),
    ("Here's the kicker: the delay saved the project from a worse launch.",
     "The delay actually saved the project from a worse launch."),
    ("Here's the thing about the numbers: they don't include returns.",
     "The numbers don't include returns."),
    ("Here's where it gets interesting: the cheapest supplier was also the fastest.",
     "The cheapest supplier was also the fastest."),
    ("Here's the kicker: the intern found the bug in an hour.",
     "The intern found the bug in an hour."),
],
"Think of It As": [
    ("Think of it like a highway system for data.",
     "The system routes data much like roads route traffic."),
    ("Think of it as a Swiss Army knife for your finances.",
     "The app combines several financial tools in one place."),
    ("Think of the cache as a shortcut that skips the slow database lookup.",
     "The cache skips the slow database lookup."),
    ("Think of onboarding as planting seeds that grow into long-term retention.",
     "Good onboarding improves long-term retention."),
    ("Think of the API gateway as a bouncer checking every request at the door.",
     "The API gateway checks every incoming request."),
    ("Think of a index like the table of contents in a book.",
     "An index works like a book's table of contents."),
    ("Think of the budget as a leash that keeps spending in check.",
     "The budget keeps spending in check."),
    ("Think of version control as a time machine for your code.",
     "Version control lets you recover earlier versions of your code."),
    ("Think of the firewall as a security guard screening visitors.",
     "The firewall screens incoming traffic."),
    ("Think of compound interest as a snowball rolling downhill.",
     "Compound interest grows an investment increasingly quickly over time."),
],
"Imagine a World Where": [
    ("Imagine a world where every tool you use has quiet, invisible intelligence.",
     "Future tools may quietly incorporate more built-in intelligence."),
    ("Imagine a world where commuting no longer costs you an hour a day.",
     "Shorter commutes could save people an hour a day."),
    ("Imagine a world where every hospital shares patient records instantly.",
     "Hospitals could share patient records instantly."),
    ("Imagine a world where small businesses never worry about cash flow again.",
     "Better tools could ease cash-flow worries for small businesses."),
    ("Imagine a world where software updates never break anything.",
     "More reliable testing could prevent updates from breaking things."),
    ("Imagine a world where every student gets a personalized tutor.",
     "Personalized tutoring could become available to every student."),
    ("Imagine a world where cities never run out of clean water.",
     "Better infrastructure could prevent water shortages in cities."),
    ("Imagine a world where meetings actually start on time.",
     "Meetings could start on time with better scheduling habits."),
    ("Imagine a world where every contract is written in plain language.",
     "Contracts could be written in plainer language."),
    ("Imagine a world where deploying code never requires downtime.",
     "Better deployment tools can reduce downtime."),
],
"False Vulnerability": [
    ("And yes, I'm openly in love with the platform model, flaws and all.",
     "I prefer the platform model, though it has flaws."),
    ("I'll admit it: I used to doubt this approach, but the results won me over.",
     "This approach initially seemed doubtful, but the results won me over."),
    ("I'm not afraid to say it: this launch scared me more than any before it.",
     "This launch was more stressful than previous ones."),
    ("Full disclosure, I was wrong about the timeline, and I own that.",
     "The timeline estimate was wrong."),
    ("I'll be honest, I didn't expect this feature to matter this much.",
     "This feature mattered more than expected."),
    ("I used to be skeptical, but I'm not too proud to admit I changed my mind.",
     "This approach changed my initial view."),
    ("Confession time: I almost cut this feature before launch.",
     "This feature was almost cut before launch."),
    ("I'll admit, this wasn't my idea, and I'm fine saying so.",
     "This wasn't my idea."),
    ("I'm not going to pretend this was easy; it nearly broke the team.",
     "This was difficult and nearly broke the team."),
    ("Honestly, I doubted this would work, and I was glad to be wrong.",
     "This worked better than expected."),
],
"The Truth Is Simple": [
    ("The truth is simple: nobody tested the rollback path.",
     "Nobody tested the rollback path."),
    ("The reality is simpler and less flattering: the team missed the deadline.",
     "The team missed the deadline."),
    ("The truth is simple: the plan never accounted for churn.",
     "The plan never accounted for churn."),
    ("The reality is simple: fewer people read the changelog than assumed.",
     "Fewer people read the changelog than assumed."),
    ("The truth is simple: the budget was too small from the start.",
     "The budget was too small from the start."),
    ("The reality is simpler than the excuses suggest: the vendor was late.",
     "The vendor was late."),
    ("The truth is simple: most users never open the settings page.",
     "Most users never open the settings page."),
    ("The reality is simple: the migration took longer because of missing tests.",
     "The migration took longer because tests were missing."),
    ("The truth is simple: the feature launched before it was ready.",
     "The feature launched before it was ready."),
    ("The reality is simpler than it looks: the outage was one bad config value.",
     "The outage was caused by one bad config value."),
],
"Grandiose Stakes Inflation": [
    ("This will fundamentally reshape how we think about everything.",
     "This will change how the team approaches similar problems."),
    ("This update redefines what it means to build software.",
     "This update changes how the team builds software."),
    ("This decision will echo across the industry for years to come.",
     "This decision will affect the team's roadmap for a while."),
    ("This isn't just a feature; it's a revolution in how people work.",
     "This feature changes a small part of how people work."),
    ("This partnership will transform the entire market overnight.",
     "This partnership will change the product's position in the market."),
    ("This single change alters the trajectory of the whole company.",
     "This change affects one part of the company's roadmap."),
    ("The launch marks the dawn of a new era for the platform.",
     "The launch adds a new capability to the platform."),
    ("This is bigger than any of us; it's a movement.",
     "This project has broader support than expected."),
    ("This tool doesn't just help you code; it changes what coding means.",
     "This tool makes a specific part of coding faster."),
    ("This decision will be remembered as the turning point of the decade.",
     "This decision changed the team's direction this year."),
],
"Let's Break This Down": [
    ("Let's break this down step by step.",
     "Here are the steps."),
    ("Let's break it down: first the cause, then the fix, then the prevention.",
     "The cause, fix, and prevention are described below."),
    ("Let's unpack this a bit, starting with the basics.",
     "Here are the basics."),
    ("Let's walk through this together, one piece at a time.",
     "Here is each piece in order."),
    ("Let's break this down so it's easier to follow.",
     "Here it is, organized for clarity."),
    ("To make this simple, let's go through it slowly.",
     "Here it is, briefly."),
    ("Let's take a moment to break down what actually happened.",
     "Here is what actually happened."),
    ("Let's break this into smaller, more digestible pieces.",
     "Here are the smaller pieces."),
    ("Let's simplify this and go one step at a time.",
     "Here are the steps, simplified."),
    ("Let's break down exactly why the numbers don't add up.",
     "Here is why the numbers don't add up."),
],
"Vague Attributions": [
    ("Experts argue that this approach has significant drawbacks.",
     "Dr. Elena Ruiz's 2024 study found this approach has significant drawbacks."),
    ("Observers note that the market has cooled in recent months.",
     "Industry analysts at CB Insights note the market has cooled in recent months."),
    ("Reports suggest the merger could close by year end.",
     "A Reuters report suggests the merger could close by year end."),
    ("Some say the redesign missed the mark.",
     "Three user-testing participants said the redesign missed the mark."),
    ("Critics argue the policy will raise costs for small businesses.",
     "The National Small Business Association argues the policy will raise costs."),
    ("It is widely believed that remote work increased productivity.",
     "A 2023 Stanford study found remote work increased productivity."),
    ("Many experts warn of a slowdown next quarter.",
     "Economists at Goldman Sachs warn of a slowdown next quarter."),
    ("Sources close to the deal say talks broke down over pricing.",
     "Two people involved in the negotiations say talks broke down over pricing."),
    ("Analysts believe the stock is undervalued.",
     "Morningstar analysts believe the stock is undervalued."),
    ("Some researchers claim the results don't replicate.",
     "A 2022 replication study found the original results didn't hold up."),
],
"Invented Concept Labels": [
    ("This is a textbook case of the supervision paradox.",
     "This shows how more oversight can sometimes reduce accountability."),
    ("We're witnessing the acceleration trap play out in real time.",
     "We're seeing how rushing a launch created new delays."),
    ("This is what I call the visibility tax teams pay for transparency.",
     "This is the extra coordination cost that comes with more transparency."),
    ("Call it the convenience spiral: each shortcut creates the need for another.",
     "Each shortcut created the need for another shortcut."),
    ("This is the classic scaling ceiling every startup eventually hits.",
     "This is the point where the current approach stops working as the company grows."),
    ("We're seeing the feedback trap: more data, less clarity.",
     "More data made the decision less clear, not more."),
    ("This is the automation debt nobody accounts for until it's due.",
     "This is the maintenance cost automation creates over time."),
    ("Call it the onboarding cliff: users drop off right after signup.",
     "Users tend to drop off right after signup."),
    ("This is the classic complexity tax of adding one more integration.",
     "Each new integration adds maintenance work."),
    ("We're in what I'd call the trust deficit phase of the rollout.",
     "Users currently distrust the rollout."),
],
"Em-Dash Addiction": [
    ("The problem -- and this is the part nobody talks about -- is scale.",
     "The problem, which nobody talks about, is scale."),
    ("The fix was simple -- almost too simple -- a single config change.",
     "The fix was a simple config change."),
    ("She didn't hesitate -- not even for a second -- before signing.",
     "She signed without hesitation."),
    ("The launch went well -- better than expected -- despite the delays.",
     "The launch went better than expected despite the delays."),
    ("The budget -- already tight -- shrank further after the audit.",
     "The already tight budget shrank further after the audit."),
    ("He rewrote the whole module -- twice -- before it passed review.",
     "He rewrote the whole module twice before it passed review."),
    ("The outage -- brief but costly -- triggered a full incident review.",
     "The brief but costly outage triggered a full incident review."),
    ("The plan -- ambitious to say the least -- needed three more engineers.",
     "The ambitious plan needed three more engineers."),
    ("The client -- understandably frustrated -- asked for a refund.",
     "The frustrated client asked for a refund."),
    ("The results -- surprising to everyone -- reversed the earlier decision.",
     "The surprising results reversed the earlier decision."),
],
"Bold-First Bullets": [
    ("- **Speed:** the new build finishes in under a minute.\n- **Cost:** the change saves about $200 a month.",
     "- The new build finishes in under a minute.\n- The change saves about $200 a month."),
    ("- **Reliability:** uptime improved to 99.9%.\n- **Simplicity:** fewer moving parts to maintain.",
     "- Uptime improved to 99.9%.\n- There are fewer moving parts to maintain."),
    ("- **Security:** all traffic is now encrypted.\n- **Compliance:** the change satisfies the new audit rules.",
     "- All traffic is now encrypted.\n- The change satisfies the new audit rules."),
    ("- **Flexibility:** teams can now deploy independently.\n- **Visibility:** every deploy is logged automatically.",
     "- Teams can now deploy independently.\n- Every deploy is logged automatically."),
    ("- **Accuracy:** the model's error rate dropped by half.\n- **Speed:** inference time dropped too.",
     "- The model's error rate dropped by half.\n- Inference time dropped too."),
    ("- **Clarity:** the new docs cut support tickets by a third.\n- **Coverage:** every endpoint is now documented.",
     "- The new docs cut support tickets by a third.\n- Every endpoint is now documented."),
    ("- **Scalability:** the service now handles 10x the traffic.\n- **Cost:** infrastructure spend stayed flat.",
     "- The service now handles 10x the traffic.\n- Infrastructure spend stayed flat."),
    ("- **Consistency:** every team now follows the same style guide.\n- **Speed:** reviews finish faster.",
     "- Every team now follows the same style guide.\n- Reviews finish faster."),
    ("- **Transparency:** the dashboard shows real-time status.\n- **Trust:** customers check it before contacting support.",
     "- The dashboard shows real-time status.\n- Customers check it before contacting support."),
    ("- **Efficiency:** the new form takes half the time to fill out.\n- **Completion:** more users finish signup.",
     "- The new form takes half the time to fill out.\n- More users finish signup."),
],
"Unicode Decoration": [
    ("Input → Processing → Output.",
     "Input goes through processing, then produces output."),
    ("The workflow is simple: Draft → Review → Publish.",
     "The workflow has three steps: draft, review, then publish."),
    ("Sales grew from $2M → $5M in a year.",
     "Sales grew from $2M to $5M in a year."),
    ("The pipeline runs Fetch → Clean → Load → Analyze.",
     "The pipeline fetches, cleans, loads, then analyzes the data."),
    ("Their process is Idea → Prototype → Launch.",
     "Their process moves from idea to prototype to launch."),
    ("Requests flow Client → Gateway → Service → Database.",
     "Requests flow from the client through the gateway and service to the database."),
    ("The funnel is Awareness → Interest → Purchase.",
     "The funnel moves from awareness to interest to purchase."),
    ("Status changed from Pending → Approved → Shipped.",
     "The status changed from pending to approved to shipped."),
    ("The upgrade path is v1 → v2 → v3.",
     "The upgrade path goes from version 1 to version 2 to version 3."),
    ("Feedback loop: Build → Measure → Learn.",
     "The feedback loop is build, measure, then learn."),
],
"Fractal Summaries": [
    ("In this section, we'll explore three causes of the outage. As we've seen, three causes led to the outage, which we covered above.",
     "This section covers three causes of the outage."),
    ("This report will cover Q3 results. As discussed, Q3 results were covered in detail above.",
     "This report covers Q3 results."),
    ("We'll walk through the migration plan below. As shown above, the migration plan involves four stages.",
     "The migration plan involves four stages, covered below."),
    ("This guide explains setup in three steps. As we've just seen, setup takes three steps as explained.",
     "This guide explains setup in three steps."),
    ("The following section outlines the new pricing tiers. As covered above, there are three new pricing tiers.",
     "The following section outlines the three new pricing tiers."),
    ("We will now review the incident timeline. As reviewed, the incident timeline spanned six hours.",
     "The incident timeline spanned six hours, reviewed below."),
    ("This chapter introduces the API's core concepts. As introduced, the core concepts are endpoints and auth.",
     "This chapter introduces the API's core concepts: endpoints and auth."),
    ("Below we summarize the survey results. As summarized above, most respondents preferred option B.",
     "Most respondents preferred option B, summarized below."),
    ("The next section explains the rollback procedure. As explained, rollback takes under ten minutes.",
     "The next section explains that rollback takes under ten minutes."),
    ("This part covers onboarding steps. As covered, onboarding has five steps as detailed here.",
     "This part covers the five onboarding steps."),
],
"The Dead Metaphor": [
    ("The ecosystem needs ecosystems to build ecosystem value across the whole ecosystem.",
     "The platform's value depends on the tools and partners built around it."),
    ("The journey of our journey began with a single step on our journey together.",
     "Our progress started with a single decision."),
    ("We're building bridges to bridge the gap between bridges and more bridges.",
     "We're connecting teams that previously worked separately."),
    ("The garden of ideas needs tending so the garden's ideas can grow in the garden.",
     "Good ideas need support and time to develop."),
    ("Our engine of growth powers the growth engine that drives our growth.",
     "Our growth comes from reinvesting in the product."),
    ("The puzzle pieces of the puzzle finally fit the puzzle together.",
     "The plan's separate parts finally worked together."),
    ("We planted the seeds of change so change could grow from those seeds.",
     "We started several small initiatives that led to change."),
    ("The tapestry we're weaving weaves together every thread of the tapestry.",
     "The project combines contributions from every team."),
    ("Our compass points us toward the compass heading we set with our compass.",
     "We're following the plan we originally set."),
    ("The foundation we built rests on the foundation of that same foundation.",
     "The project relies on decisions made early on."),
],
"Historical Analogy Stacking": [
    ("Apple didn't build Uber. Facebook didn't build Spotify. Google didn't build Airbnb.",
     "Large companies don't always build the products that define the next wave of the market."),
    ("Netflix disrupted Blockbuster. Amazon disrupted bookstores. Airbnb disrupted hotels.",
     "New entrants have repeatedly disrupted established industries."),
    ("Kodak missed digital. Nokia missed smartphones. Blockbuster missed streaming.",
     "Established companies have repeatedly missed major technology shifts."),
    ("Tesla wasn't the first car company. Apple wasn't the first phone maker. Amazon wasn't the first store.",
     "Being first to market isn't required to eventually lead it."),
    ("PayPal started with a niche. Instagram started with a niche. Slack started with a niche.",
     "Several successful companies started by serving a narrow niche."),
    ("IBM adapted to PCs. Microsoft adapted to the web. Adobe adapted to subscriptions.",
     "Established companies have adapted to major shifts before."),
    ("Xerox invented the GUI but Apple shipped it. Fairchild invented microchips but Intel scaled them.",
     "Invention and commercialization are often done by different companies."),
    ("Friendster came first. MySpace came next. Facebook came last and won.",
     "Being last to a market doesn't prevent eventually winning it."),
    ("Yahoo tried search. Google perfected it. Bing still competes.",
     "Several companies have competed in search with different levels of success."),
    ("Napster started file sharing. iTunes monetized it. Spotify streamed it.",
     "Digital music distribution evolved through several different companies."),
],
"One-Point Dilution": [
    ("The team was overworked. Workloads were too high. People had too much on their plate. The pace was unsustainable. Everyone was stretched thin.",
     "The team was overworked."),
    ("The launch was rushed. There wasn't enough time. The schedule was too tight. Deadlines were unrealistic. Everything moved too fast.",
     "The launch was rushed."),
    ("Communication broke down. Nobody was talking. Updates weren't shared. People worked in silos. Information didn't flow.",
     "Communication broke down."),
    ("The budget was too small. Funding fell short. Resources were limited. Money ran out. The project was underfunded.",
     "The budget was too small."),
    ("The design was confusing. Users got lost. Navigation wasn't clear. The layout was cluttered. People couldn't find what they needed.",
     "The design was confusing."),
    ("Testing was skipped. QA didn't have time. Bugs went unnoticed. Nothing was verified. Quality checks were rushed.",
     "Testing was skipped."),
    ("The onboarding was too long. New hires felt overwhelmed. There was too much to learn. The process dragged on. People lost momentum.",
     "The onboarding was too long."),
    ("Expectations weren't set. Nobody knew the goals. Priorities were unclear. Direction was missing. The team lacked focus.",
     "Expectations weren't set."),
    ("The vendor was unreliable. Deliveries were late. Quality was inconsistent. Support was slow. Communication was poor.",
     "The vendor was unreliable."),
    ("The rollout was chaotic. Timing was off. Coordination failed. Teams weren't aligned. Nothing went as planned.",
     "The rollout was chaotic."),
],
"Content Duplication": [
    ("The migration takes four steps: backup, test, deploy, verify. The migration takes four steps: backup, test, deploy, verify.",
     "The migration takes four steps: backup, test, deploy, verify."),
    ("Sales grew 20% this quarter due to the new campaign. Sales grew 20% this quarter due to the new campaign.",
     "Sales grew 20% this quarter due to the new campaign."),
    ("The outage lasted two hours and affected the checkout flow. The outage lasted two hours and affected the checkout flow.",
     "The outage lasted two hours and affected the checkout flow."),
    ("Our new pricing tiers start at $10 a month. Our new pricing tiers start at $10 a month.",
     "Our new pricing tiers start at $10 a month."),
    ("The survey found most users prefer dark mode. The survey found most users prefer dark mode.",
     "The survey found most users prefer dark mode."),
    ("The team shipped the redesign two weeks early. The team shipped the redesign two weeks early.",
     "The team shipped the redesign two weeks early."),
    ("The new office opens downtown next spring. The new office opens downtown next spring.",
     "The new office opens downtown next spring."),
    ("The report covers Q3 revenue and expenses in detail. The report covers Q3 revenue and expenses in detail.",
     "The report covers Q3 revenue and expenses in detail."),
    ("The library added weekend hours starting this month. The library added weekend hours starting this month.",
     "The library added weekend hours starting this month."),
    ("The update fixes the login bug reported last week. The update fixes the login bug reported last week.",
     "The update fixes the login bug reported last week."),
],
"The Signposted Conclusion": [
    ("In conclusion, the future of AI depends on responsible deployment.",
     "Responsible deployment will shape the future of AI."),
    ("To sum up, the migration succeeded with minimal downtime.",
     "The migration succeeded with minimal downtime."),
    ("In summary, the redesign improved conversion by 15%.",
     "The redesign improved conversion by 15%."),
    ("In conclusion, the team should prioritize reliability over new features next quarter.",
     "The team should prioritize reliability over new features next quarter."),
    ("To conclude, the pilot program met all of its goals.",
     "The pilot program met all of its goals."),
    ("In summary, the vendor switch saved the company $40,000 a year.",
     "The vendor switch saved the company $40,000 a year."),
    ("In conclusion, further testing is needed before the wider rollout.",
     "Further testing is needed before the wider rollout."),
    ("To wrap up, the survey results support the proposed changes.",
     "The survey results support the proposed changes."),
    ("In conclusion, the new policy reduced onboarding time significantly.",
     "The new policy reduced onboarding time significantly."),
    ("In summary, both approaches have merit depending on the use case.",
     "Both approaches have merit depending on the use case."),
],
"Despite Its Challenges": [
    ("Despite these challenges, the initiative continues to thrive.",
     "Despite these challenges, the initiative is still struggling to gain traction."),
    ("Despite the setbacks, the project remains on track.",
     "The setbacks pushed the project's timeline back by a month."),
    ("Despite its flaws, the system works well enough for now.",
     "The system's flaws still cause occasional outages."),
    ("Despite the criticism, the policy has broad support.",
     "The criticism reflects real concerns from a significant portion of users."),
    ("Despite early struggles, the team hit every deadline this quarter.",
     "After early struggles, the team missed two deadlines this quarter."),
    ("Despite the budget cuts, the department improved service quality.",
     "The budget cuts reduced service quality noticeably."),
    ("Despite the delays, customers remained loyal to the brand.",
     "The delays caused several long-time customers to leave."),
    ("Despite its complexity, the new tool is intuitive to use.",
     "The new tool's complexity makes it hard to learn."),
    ("Despite the risks, the company pressed ahead with the launch.",
     "The company launched anyway, and two of the risks materialized."),
    ("Despite the resistance, the reorganization went smoothly.",
     "The resistance to the reorganization slowed the rollout by weeks."),
],
}

NEGATIVES = [
    "The bus was fifteen minutes late this morning.",
    "She fixed the leaking faucet with a new washer.",
    "The recipe calls for two cups of flour and one egg.",
    "He parked the car in the garage before it started raining.",
    "The meeting moved to 3 p.m. because the room was booked.",
    "The dog needs a walk before dinner.",
    "The invoice is due on the fifteenth of next month.",
    "She replaced the broken tile in the kitchen last weekend.",
    "The flight was delayed by forty minutes because of weather.",
    "He submitted the report before the Friday deadline.",
    "The store closes at nine on weekdays and six on Sundays.",
    "The team met on Tuesday to review the budget.",
    "The printer ran out of toner halfway through the job.",
    "She planted tomatoes and basil in the backyard garden.",
    "The library extended its hours during exam week.",
    "He changed the oil in his car over the weekend.",
    "The package arrived two days earlier than expected.",
    "The class starts at nine and ends at eleven.",
    "She paid the electric bill online this morning.",
    "The bridge closes for maintenance every third Sunday.",
    "The bakery sells out of croissants by ten most days.",
    "He replaced the batteries in the smoke detector.",
    "The train departs from platform four at noon.",
    "She scheduled the dentist appointment for next Thursday.",
    "The warehouse restocks shelves every Monday morning.",
    "He mowed the lawn before the storm arrived.",
    "The clinic requires appointments for flu shots this year.",
    "She backed up her files before reinstalling the operating system.",
    "The parking garage charges five dollars for the first hour.",
    "He returned the library books a day before they were due.",
]

def main():
    tropes = read_tropes()
    name_to_id = dict(zip(tropes.column("name").to_pylist(), tropes.column("trope_id").to_pylist()))

    doc_rows, sent_rows, label_rows, rewrite_rows = [], [], [], []

    for name, pairs in PAIRS.items():
        trope_id = name_to_id[name]
        for positive, rewrite in pairs:
            pos_ids = _insert_document(positive, True, True, doc_rows, sent_rows)
            rewrite_ids = _insert_document(rewrite, True, False, doc_rows, sent_rows)
            for sid in pos_ids:
                label_rows.append({
                    "sentence_id": sid, "trope_id": trope_id,
                    "label_source": "synthetic-gen", "confidence": 1.0,
                })
            if pos_ids and rewrite_ids:
                rewrite_rows.append({
                    "rewrite_id": str(uuid.uuid5(REWRITE_NAMESPACE, pos_ids[0])),
                    "sentence_id": pos_ids[0], "trope_id": trope_id,
                    "rewritten_text": rewrite.strip(), "source": "synthetic-gen",
                })

    for neg in NEGATIVES:
        _insert_document(neg, True, False, doc_rows, sent_rows)

    append_rows(SOURCE_DOCUMENT_PATH, doc_rows)
    append_rows(SENTENCE_PATH, sent_rows)
    append_rows(SENTENCE_TROPE_LABEL_PATH, label_rows)
    append_rows(SENTENCE_REWRITE_PATH, rewrite_rows)
    print(f"hand-authored synthetic: {len(doc_rows)} docs, {len(label_rows)} labels, "
          f"{len(rewrite_rows)} rewrite pairs, {len(NEGATIVES)} negatives")


if __name__ == "__main__":
    main()
