# SPDX-License-Identifier: MIT
# Copyright (c) 2026 K. S. Ernest (iFire) Lee
"""
Fifth hand-authored batch. Targets whatever remained lowest after round 4:

  Classifier floor (54-68 positives): Let's Break This Down, Superficial
  Analyses, The Dead Metaphor, False Vulnerability, Grandiose Stakes
  Inflation, Invented Concept Labels, Quietly and Other Magic Adverbs.

  Rewrite-pair floor (23-36 pairs): Em-Dash Addiction, Unicode Decoration,
  Tricolon Abuse, Delve and Friends, The Serves As Dodge, Tapestry and
  Landscape, Think of It As, The Signposted Conclusion, Anaphora Abuse,
  Imagine a World Where, Listicle in a Trench Coat, One-Point Dilution,
  Not X. Not Y. Just Z., Despite Its Challenges, Fractal Summaries.

New topic domains (crafts, gardening, libraries, software/tech, theater,
remote work) to keep variety up across five rounds of the same 33 tropes.
"""
import sys
import uuid

sys.path.insert(0, __file__.rsplit("scripts", 1)[0])
from runtime.datalake import (
    SENTENCE_PATH, SENTENCE_REWRITE_PATH, SENTENCE_TROPE_LABEL_PATH,
    SOURCE_DOCUMENT_PATH, append_rows, read_table, read_tropes,
)
from scripts.synth_generate import REWRITE_NAMESPACE, _insert_document

CLASSIFIER_FLOOR = {
"Let's Break This Down": [
    ("Let's break this down step by step, starting with the git conflict.",
     "Here is the git conflict."),
    ("Let's unpack this a bit: first the bug, then the patch.",
     "Here is the bug and the patch."),
    ("Let's walk through the loom setup together, one step at a time.",
     "Here are the loom setup steps."),
    ("To make this simple, let's go through the library's late fees slowly.",
     "Here are the library's late fees."),
    ("Let's break this down so the standup agenda is easier to follow.",
     "Here is the standup agenda."),
    ("Let's take a moment to break down what caused the deploy failure.",
     "Here is what caused the deploy failure."),
    ("Let's break the pattern into smaller, easier pieces for the quilt.",
     "Here is the quilt pattern, broken into smaller pieces."),
    ("Let's simplify this and go through the seating chart one step at a time.",
     "Here is the seating chart."),
    ("Let's break down exactly why the compost pile stopped heating up.",
     "Here is why the compost pile stopped heating up."),
    ("Let's walk through the rehearsal schedule together, scene by scene.",
     "Here is the rehearsal schedule, scene by scene."),
    ("Let's break this down: first the symptoms, then the root cause.",
     "Here are the symptoms and the root cause."),
    ("Let's unpack the new remote policy and what it means for the team.",
     "Here is the new remote policy and what it means for the team."),
    ("Let's break this down slowly so nobody misses a step in the build.",
     "Here are the build steps."),
    ("Let's walk through the seed-starting schedule together.",
     "Here is the seed-starting schedule."),
    ("Let's break this down into the three acts of the play.",
     "Here are the three acts of the play."),
    ("Let's break down the pull request review process step by step.",
     "Here is the pull request review process."),
    ("Let's unpack the library's new checkout limits together.",
     "Here are the library's new checkout limits."),
    ("Let's walk through the greenhouse watering schedule, day by day.",
     "Here is the greenhouse watering schedule, day by day."),
    ("Let's break this down: first the audition, then the callback.",
     "Here is the audition process and the callback."),
    ("Let's simplify the sprint plan and go through it one ticket at a time.",
     "Here is the sprint plan, one ticket at a time."),
    ("Let's break down why the sourdough starter stopped rising.",
     "Here is why the sourdough starter stopped rising."),
    ("Let's walk through the costume fitting schedule together.",
     "Here is the costume fitting schedule."),
    ("Let's break this down so the onboarding checklist is easier to follow.",
     "Here is the onboarding checklist."),
    ("Let's take a moment to break down what caused the yarn to tangle.",
     "Here is what caused the yarn to tangle."),
    ("Let's break down the library's new digital lending steps.",
     "Here are the library's new digital lending steps."),
],
"Superficial Analyses": [
    ("The library added a maker space, extending its role in the community's creative life.",
     "The library added a maker space."),
    ("The gardener rotated the beds this season, deepening the soil's long-term health.",
     "The gardener rotated the beds this season."),
    ("The theater added a matinee, reflecting its broader push toward accessibility.",
     "The theater added a matinee."),
    ("The team adopted a new linter, underscoring their commitment to code quality.",
     "The team adopted a new linter."),
    ("The knitting circle added a Thursday session, deepening the group's weekly rhythm.",
     "The knitting circle added a Thursday session."),
    ("The office added standing desks, reflecting a renewed focus on wellness.",
     "The office added standing desks."),
    ("The librarian extended story hour, further advancing outreach to families.",
     "The librarian extended story hour."),
    ("The director added a rehearsal, showcasing the cast's growing dedication.",
     "The director added a rehearsal."),
    ("The team migrated to a new framework, signaling its long-term technical vision.",
     "The team migrated to a new framework."),
    ("The greenhouse added shade cloth, enriching its capacity to protect seedlings.",
     "The greenhouse added shade cloth."),
    ("The quilters donated the finished blanket, deepening their tie to the shelter.",
     "The quilters donated the finished blanket."),
    ("The theater repainted the lobby, reflecting a renewed investment in the space.",
     "The theater repainted the lobby."),
    ("The library extended Wi-Fi access, further advancing its commitment to equity.",
     "The library extended Wi-Fi access."),
    ("The team added code review checklists, underscoring their focus on reliability.",
     "The team added code review checklists."),
    ("The garden club planted a pollinator strip, deepening its ecological mission.",
     "The garden club planted a pollinator strip."),
    ("The stage crew rebuilt the set overnight, showcasing their tireless dedication.",
     "The stage crew rebuilt the set overnight."),
    ("The office adopted flexible hours, reflecting a broader shift in workplace culture.",
     "The office adopted flexible hours."),
    ("The library digitized the archive, further advancing its preservation mission.",
     "The library digitized the archive."),
    ("The team added integration tests, underscoring their focus on stability.",
     "The team added integration tests."),
    ("The garden added a rain barrel, deepening its commitment to sustainability.",
     "The garden added a rain barrel."),
    ("The costume team dyed the fabric by hand, honoring the production's period detail.",
     "The costume team dyed the fabric by hand."),
    ("The library added a repair cafe, extending its role as a community hub.",
     "The library added a repair cafe."),
    ("The team wrote a runbook, reflecting their commitment to on-call readiness.",
     "The team wrote a runbook."),
    ("The knitting circle donated scarves, deepening its ties to the winter shelter drive.",
     "The knitting circle donated scarves."),
    ("The greenhouse added a drip line, further advancing its water-saving efforts.",
     "The greenhouse added a drip line."),
],
"The Dead Metaphor": [
    ("The library is a garden, and the garden's shelves bloom into the library's garden of ideas.",
     "The library offers a wide range of ideas and resources."),
    ("The codebase is a maze, and the maze's turns lead engineers through the maze of dependencies.",
     "The codebase has complex, tangled dependencies."),
    ("The theater is a heartbeat, pumping energy through the heartbeat-halls of the stage.",
     "The theater brings energy to the stage."),
    ("The garden is a canvas, painted anew each season by the garden's canvas of blooms.",
     "The garden looks different each season."),
    ("The team is an engine, and the engine's gears keep the team-engine running smoothly.",
     "The team works well together this quarter."),
    ("The quilt is a story, and every patch on the quilt writes another line of the quilt's story.",
     "The quilt tells a story through its patches."),
    ("The office is a hive, and the hive's workers buzz through the office-hive all day.",
     "The office stays busy with activity all day."),
    ("The rehearsal is a rehearsal-river, and the river's current carries the cast downstream.",
     "The rehearsal moves the cast steadily toward opening night."),
    ("The greenhouse is a lung, breathing life into the greenhouse-lung's seedlings.",
     "The greenhouse nurtures seedlings into healthy plants."),
    ("The sprint is a marathon, and every mile of the sprint-marathon tests the team's runners.",
     "The sprint is demanding and tests the team's endurance."),
    ("The library is a bridge, connecting readers across the bridge to new bridge-worlds.",
     "The library connects readers to new books and ideas."),
    ("The codebase is a tapestry, woven from threads that make up the codebase's tapestry.",
     "The codebase combines contributions from many different developers."),
    ("The stage is a compass, pointing the cast toward the compass heading of opening night.",
     "The stage rehearsals guide the cast toward opening night."),
    ("The garden club is a ladder, and every rung of the ladder lifts a member up the ladder.",
     "The garden club helps members learn step by step."),
    ("The office is a ship, and the ship's crew steers the office-ship through busy quarters.",
     "The office team manages busy quarters carefully."),
    ("The knitting circle is a thread, stitching together every thread of the group's thread-bond.",
     "The knitting circle connects its members closely."),
    ("The deploy pipeline is a river, and the river's code flows into the pipeline's river of releases.",
     "The deploy pipeline releases code steadily."),
    ("The theater is a mirror, reflecting the mirror-truths of the audience's own lives.",
     "The theater reflects parts of the audience's own lives."),
    ("The greenhouse is a nursery, cradling every seedling in the greenhouse-nursery's warmth.",
     "The greenhouse provides a warm start for seedlings."),
    ("The library is an anchor, holding the neighborhood steady like an anchor holds a ship.",
     "The library provides stability for the neighborhood."),
    ("The rehearsal room is a forge, tempering the cast in the forge's rehearsal-heat.",
     "The rehearsal room sharpens the cast's performance."),
    ("The garden is a heartbeat, pumping color through the garden's heartbeat-beds each spring.",
     "The garden bursts with color each spring."),
    ("The codebase is a puzzle, and the puzzle pieces of modules fit the codebase's puzzle.",
     "The codebase's modules fit together well."),
    ("The office is a garden, and the garden's ideas bloom into the office-garden's projects.",
     "The office nurtures new project ideas."),
    ("The theater is an engine, and the engine's momentum drives the theater-engine's season.",
     "The theater's season builds momentum show after show."),
],
"False Vulnerability": [
    ("I'll admit it, I doubted the new linter would help, and it did.",
     "The new linter helped despite my doubts."),
    ("I'm not too proud to say I misjudged how long the migration would take.",
     "The migration took longer than expected."),
    ("Honestly, I was nervous about the play's new ending, and it landed well.",
     "The play's new ending landed well despite initial concerns."),
    ("I'll be the first to admit I underestimated how popular the maker space would be.",
     "The maker space was more popular than expected."),
    ("Confession: I almost skipped the dress rehearsal, and I'm glad I didn't.",
     "The dress rehearsal turned out to be worthwhile."),
    ("I used to think the standing desks were a gimmick, and I was wrong.",
     "The standing desks turned out to be worthwhile."),
    ("I won't pretend the garden's first season was easy.",
     "The garden's first season wasn't easy."),
    ("I'll admit, I got emotional at the library's closing-night reading.",
     "I was emotional at the library's closing-night reading."),
    ("I'm not ashamed to say the first draft of the script was rejected.",
     "The first draft of the script was rejected."),
    ("Honestly, I was skeptical of the new remote policy, and it worked out fine.",
     "The new remote policy worked out fine despite initial skepticism."),
    ("I'll admit it: I nearly quit the quilting project halfway through.",
     "I nearly quit the quilting project halfway through."),
    ("I used to doubt the compost bin would work, and it proved me wrong.",
     "The compost bin proved effective despite early doubts."),
    ("I'm not too proud to admit the sprint plan had an error for weeks.",
     "The sprint plan had an error for weeks."),
    ("I'll be honest, I didn't expect the show to sell out this fast.",
     "The show sold out faster than expected."),
    ("I won't hide it: the first year running the garden club nearly overwhelmed me.",
     "The first year running the garden club was overwhelming."),
    ("I'll admit I doubted the new build pipeline would matter, and it did.",
     "The new build pipeline mattered more than expected."),
    ("Honestly, I was unsure the costume redesign would work, and it has.",
     "The costume redesign has worked despite early uncertainty."),
    ("I'm not too proud to say the first library grant application was rejected.",
     "The first library grant application was rejected."),
    ("I'll admit, I cried a little at the cast's final bow.",
     "I was emotional at the cast's final bow."),
    ("I used to doubt the new code review process would help, and it has.",
     "The new code review process has helped despite early doubts."),
    ("Confession: I almost canceled the seed swap, and I'm glad I didn't.",
     "The seed swap turned out to be worthwhile."),
    ("I'll admit, the deploy scared me more than any release this year.",
     "This deploy was more stressful than others this year."),
    ("I'm not too proud to say the theater's budget nearly ran short last season.",
     "The theater's budget nearly ran short last season."),
    ("Honestly, I doubted the raised beds were worth the cost, and they were.",
     "The raised beds were worth the cost despite initial doubts."),
    ("I won't pretend the on-call rotation didn't stress the whole team out.",
     "The on-call rotation stressed out the whole team."),
],
"Grandiose Stakes Inflation": [
    ("This new linter will change the entire future of how the team writes code.",
     "This new linter will catch a few common mistakes."),
    ("This one library card marks a turning point for literacy everywhere.",
     "This library card gives one more resident access to books."),
    ("This is more than a play; it's a movement that will redefine the whole town's culture.",
     "This play offers a new production for the local theater."),
    ("This small garden club will transform how the whole city grows food.",
     "This garden club will help a dozen neighbors grow vegetables."),
    ("This is the moment that changes everything for every developer everywhere.",
     "This fix will help the team ship faster this week."),
    ("This one rehearsal will revolutionize how the whole company approaches theater.",
     "This rehearsal will help the cast prepare for one scene."),
    ("This maker space renovation isn't just a remodel; it's a rebirth for the entire library.",
     "This maker space renovation adds new tools and better lighting."),
    ("This youth coding class will shape the destiny of an entire generation.",
     "This youth coding class will teach twenty kids this summer."),
    ("This garden expansion redefines what it means to be a sustainable community.",
     "This garden expansion adds a few new raised beds."),
    ("This is the single decision that will determine the fate of the whole season.",
     "This decision affects next month's rehearsal schedule."),
    ("This code review isn't just feedback; it's a life-altering intervention.",
     "This code review covers this week's pull request."),
    ("This library will change the course of the entire neighborhood's future.",
     "This library offers a new option for local readers."),
    ("This is bigger than one bug fix; it's a revolution in how the team ships software.",
     "This bug fix improved one part of the checkout flow."),
    ("This new greenhouse wing will reshape the future of urban farming nationwide.",
     "This new greenhouse wing adds space for a dozen more plants."),
    ("This single lecture will change how humanity understands theater forever.",
     "This lecture covers recent trends in community theater."),
    ("This standup meeting isn't just a check-in; it's a wake-up call for the whole company.",
     "This standup meeting covers today's tasks."),
    ("This one compost bin will redefine sustainability for the entire block.",
     "This compost bin reduces one household's food waste."),
    ("This library fundraiser will determine the future of literacy everywhere.",
     "This fundraiser will support the library's budget this year."),
    ("This new API isn't just an update; it's a revolution in how the team builds products.",
     "This new API adds one useful feature."),
    ("This costume design marks the beginning of a new era for the theater.",
     "This costume design adds new detail to one production."),
    ("This raised-bed system will transform how an entire generation of gardeners grows food.",
     "This raised-bed system helps one garden grow vegetables more easily."),
    ("This is more than a book club meeting; it's a cultural moment for readers everywhere.",
     "This book club meeting gives members a chance to discuss the novel."),
    ("This library's new hours will reshape access to books across the whole county.",
     "This library's new hours add weekend access for residents."),
    ("This is the single release that will define the whole product's future.",
     "This release adds a small new feature."),
    ("This one quilt will change how the world sees handmade craft.",
     "This quilt will be donated to one family in need."),
],
"Invented Concept Labels": [
    ("This is a textbook case of the standup drift: meetings run longer every week.",
     "Standup meetings have been running longer each week."),
    ("We're seeing the merge conflict spiral: one late rebase creates three more conflicts.",
     "One late rebase tends to create more merge conflicts."),
    ("This is what I call the library lull, where checkouts dip every August.",
     "Library checkouts tend to dip every August."),
    ("Call it the rehearsal fatigue every cast eventually faces by week six.",
     "Many casts experience fatigue by the sixth week of rehearsal."),
    ("This is the classic second-act slump every playwright eventually hits.",
     "Many playwrights face a difficult second act."),
    ("We're witnessing the garden lag, where the harvest arrives weeks after the planting rush.",
     "The harvest tends to arrive weeks after the planting rush."),
    ("This is the technical debt nobody accounts for until the sprint after next.",
     "This is the maintenance work that builds up over several sprints."),
    ("Call it the onboarding fog: new hires rarely retain the first-week training.",
     "New hires rarely retain training given in the first week."),
    ("This is the classic quilt spiral, where one pattern change reveals three more.",
     "One pattern change in a quilt often reveals the need for more."),
    ("We're in what I'd call the ticket anxiety phase before the show announcement.",
     "Audiences are anxious before the show announcement."),
    ("This is the seasonal dip nearly every garden club sees in late fall.",
     "Garden club attendance typically dips for most groups in late fall."),
    ("Call it the deploy cascade: one delayed release shifts three others.",
     "One delayed release can shift the schedule for several others."),
    ("This is a clear case of the readership cliff after the library's grant ended.",
     "Readership dropped sharply after the library's grant ended."),
    ("We're seeing the audience-loyalty rebound now that ticket prices dropped.",
     "Audience engagement is recovering now that ticket prices dropped."),
    ("This is the classic burnout curve among stage crews after a long tech week.",
     "Many stage crew members experience burnout after a long tech week."),
    ("Call it the intake cliff libraries see right before finals season.",
     "Libraries typically see intake rise right before finals season."),
    ("This is a textbook demand echo: ticket sales spike again after a good review.",
     "Ticket sales tend to spike again after a good review."),
    ("We're witnessing the checkout drag every self-service kiosk eventually hits.",
     "This is the point where self-service kiosks slow down during peak hours."),
    ("This is what I'd call the compost ceiling, where decomposition eventually plateaus.",
     "This is the point where decomposition slows down in a compost pile."),
    ("Call it the code creep: each small patch slightly slows the whole build.",
     "Each small patch has slightly slowed down the whole build."),
    ("This is the classic library plateau every branch eventually hits with membership.",
     "This is the point where membership growth levels off for a branch."),
    ("We're seeing the loyalty erosion effect after the theater's price increase.",
     "Audience loyalty declined somewhat after the theater's price increase."),
    ("This is a case of what I'd call the germination lag in the greenhouse.",
     "This shows how germination is taking longer than expected in the greenhouse."),
    ("Call it the rehearsal crunch: blocking takes longer than the schedule allows.",
     "Blocking rehearsals tend to take longer than scheduled."),
    ("This is the classic sprint fatigue every dev team faces by the third quarter.",
     "Many dev teams experience fatigue by the third quarter."),
],
"Quietly and Other Magic Adverbs": [
    ("The new linter is quietly cutting down on style-review comments.",
     "The new linter cut down on style-review comments."),
    ("Her direction is deeply shaping how the cast approaches the final scene.",
     "Her direction shaped how the cast approaches the final scene."),
    ("The bed rotation is fundamentally improving the garden's soil health.",
     "The bed rotation improved the garden's soil health."),
    ("The new checkout kiosk is quietly reshaping how patrons use the library.",
     "The new checkout kiosk changed how patrons use the library."),
    ("This small grant is remarkably transforming the theater's set-building budget.",
     "This small grant changed the theater's set-building budget."),
    ("The revised sprint plan is quietly cutting overtime across the team.",
     "The revised sprint plan cut overtime across the team."),
    ("Her mentoring is deeply influencing how new gardeners plan their beds.",
     "Her mentoring changed how new gardeners plan their beds."),
    ("The new watering schedule is fundamentally altering the greenhouse's yield.",
     "The new watering schedule changed the greenhouse's yield."),
    ("This policy is quietly reducing wait times at the reference desk.",
     "This policy reduced wait times at the reference desk."),
    ("The lighting redesign is deeply changing how audiences experience the stage.",
     "The lighting redesign changed how audiences experience the stage."),
    ("The new soil mix is remarkably boosting this season's tomato yield.",
     "The new soil mix boosted this season's tomato yield."),
    ("Her leadership is quietly transforming the volunteer culture at the library.",
     "Her leadership changed the volunteer culture at the library."),
    ("The updated code review checklist is fundamentally simplifying onboarding.",
     "The updated code review checklist simplified onboarding."),
    ("This new signage is quietly improving wayfinding in the stacks.",
     "This new signage improved wayfinding in the stacks."),
    ("The pilot rehearsal schedule is deeply reshaping how the company plans its season.",
     "The pilot rehearsal schedule changed how the company plans its season."),
    ("The new trellis design is remarkably improving airflow for the tomato beds.",
     "The new trellis design improved airflow for the tomato beds."),
    ("Her coaching is quietly transforming how the ensemble handles difficult blocking.",
     "Her coaching changed how the ensemble handles difficult blocking."),
    ("The updated intake form is fundamentally speeding up library card signups.",
     "The updated intake form sped up library card signups."),
    ("This new schedule is quietly easing the strain on the stage crew.",
     "This new schedule eased the strain on the stage crew."),
    ("The revised seed catalog is deeply changing how the garden club plans spring.",
     "The revised seed catalog changed how the garden club plans spring."),
    ("The new deploy checklist is remarkably reducing production incidents.",
     "The new deploy checklist reduced production incidents."),
    ("Her mentoring is quietly transforming how junior developers approach reviews.",
     "Her mentoring changed how junior developers approach reviews."),
    ("The updated set design is fundamentally reducing scene-change time.",
     "The updated set design reduced scene-change time."),
    ("This new rotation is quietly improving continuity for the on-call team.",
     "This new rotation improved continuity for the on-call team."),
    ("The remastered lighting cues are deeply reshaping the show's final act.",
     "The remastered lighting cues changed the show's final act."),
],
}

REWRITE_TOPUP = {
"Em-Dash Addiction": [
    ("The rehearsal -- against all odds -- finished ahead of schedule.",
     "The rehearsal finished ahead of schedule, against all odds."),
    ("The garden -- neglected all winter -- came back strong in spring.",
     "The neglected garden came back strong in spring."),
    ("The deploy -- risky but necessary -- went off without a hitch.",
     "The risky but necessary deploy went off without a hitch."),
    ("The library -- short-staffed but determined -- kept its hours.",
     "The short-staffed library kept its hours."),
    ("The quilt -- painstaking but worth it -- finally came together.",
     "The painstaking quilt finally came together."),
],
"Unicode Decoration": [
    ("The rehearsal goes Read-through → Blocking → Tech.",
     "The rehearsal has three stages: read-through, blocking, then tech."),
    ("The garden bed moved from Weeds → Soil → Seedlings.",
     "The garden bed moved from weeds to soil to seedlings."),
    ("The build pipeline runs Lint → Test → Deploy.",
     "The build pipeline lints, tests, then deploys."),
    ("The book's journey: Draft → Edit → Print.",
     "The book moved from draft to edit to print."),
    ("Progress went Idea → Prototype → Launch.",
     "Progress moved from idea to prototype to launch."),
],
"Tricolon Abuse": [
    ("The library informs, the library connects, the library empowers.",
     "The library informs, connects, and empowers the community."),
    ("Good code is clear; good code is tested; good code is maintained.",
     "Good code is clear, tested, and maintained."),
    ("The garden feeds us. The garden grounds us. The garden teaches us.",
     "The garden feeds, grounds, and teaches us."),
    ("The play moves you, the play challenges you, the play stays with you.",
     "The play moves, challenges, and stays with you."),
    ("It's simple. It's honest. It's effective.",
     "It's simple, honest, and effective."),
],
"Delve and Friends": [
    ("Let's delve into why the build kept failing overnight.",
     "Here's why the build kept failing overnight."),
    ("The library plans to utilize the back room for the maker space.",
     "The library plans to use the back room for the maker space."),
    ("The director wants to leverage the new lighting rig for the finale.",
     "The director wants to use the new lighting rig for the finale."),
    ("This is a robust plan that streamlines the checkout process.",
     "This plan simplifies the checkout process."),
    ("Let's delve into why the tomatoes didn't ripen this year.",
     "Here's why the tomatoes didn't ripen this year."),
],
"The Serves As Dodge": [
    ("The plaque serves as a reminder of the library's founding year.",
     "The plaque is a reminder of the library's founding year."),
    ("This checklist serves as a starting point for new volunteers.",
     "This checklist is a starting point for new volunteers."),
    ("The mural serves as a tribute to the garden club's founders.",
     "The mural is a tribute to the garden club's founders."),
    ("Her promotion marks a turning point for the theater's marketing team.",
     "Her promotion is a turning point for the theater's marketing team."),
    ("The badge serves as proof of completed safety training.",
     "The badge is proof of completed safety training."),
],
"Tapestry and Landscape": [
    ("The rich tapestry of the community garden reflects the whole block's effort.",
     "The community garden reflects the whole block's effort."),
    ("Navigating the landscape of open-source licensing took the team weeks.",
     "Understanding open-source licensing took the team weeks."),
    ("The play weaves together a tapestry of voices from the whole town.",
     "The play includes voices from the whole town."),
    ("The zoning landscape shifted after the new library ordinance passed.",
     "Zoning changed after the new library ordinance passed."),
    ("Understanding the competitive landscape of local theaters took months.",
     "Understanding local theater competitors took months."),
],
"Think of It As": [
    ("Think of the linter as a spellchecker for code.",
     "The linter works like a spellchecker for code."),
    ("Think of the compost bin as a slow-motion recycling plant.",
     "The compost bin works like a slow-motion recycling plant."),
    ("Think of the dress rehearsal as a final exam before opening night.",
     "The dress rehearsal is a final exam before opening night."),
    ("Think of the library card as a passport to every book in the system.",
     "The library card gives access to every book in the system."),
    ("Think of code review as a second pair of eyes on every change.",
     "Code review provides a second pair of eyes on every change."),
],
"The Signposted Conclusion": [
    ("In conclusion, the new linter cut review time significantly.",
     "The new linter cut review time significantly."),
    ("To sum up, the garden's harvest exceeded last year's by a wide margin.",
     "The garden's harvest exceeded last year's by a wide margin."),
    ("In summary, the play's run outperformed the theater's expectations.",
     "The play's run outperformed the theater's expectations."),
    ("In conclusion, the team should prioritize testing over new features next sprint.",
     "The team should prioritize testing over new features next sprint."),
    ("To conclude, the pilot maker space met all of its goals.",
     "The pilot maker space met all of its goals."),
],
"Anaphora Abuse": [
    ("They assume the build will pass. They assume the tests will hold. They assume the deploy will go smoothly.",
     "They assume the build will pass, the tests will hold, and the deploy will go smoothly."),
    ("We believe in clean code. We believe in honest reviews. We believe in shared ownership.",
     "We believe in clean code, honest reviews, and shared ownership."),
    ("This is a story about a small garden. This is a story about patience. This is a story about growth.",
     "This is a story about a small garden, patience, and growth."),
    ("Every cast wants more rehearsal time. Every cast wants better lighting. Every cast wants a bigger budget.",
     "Every cast wants more rehearsal time, better lighting, and a bigger budget."),
    ("She checked the beds alone. She weeded them alone. She watered them alone.",
     "She checked, weeded, and watered the beds alone."),
],
"Imagine a World Where": [
    ("Imagine a world where every library had a maker space.",
     "Maker spaces could become common in libraries."),
    ("Imagine a world where every garden bed watered itself.",
     "Self-watering garden beds could become common."),
    ("Imagine a world where every deploy shipped without a single bug.",
     "Better testing could reduce bugs in every deploy."),
    ("Imagine a world where every play sold out its opening night.",
     "Stronger marketing could help more plays sell out opening night."),
    ("Imagine a world where every commute took half the time.",
     "Faster transit could cut commute times significantly."),
],
"Listicle in a Trench Coat": [
    ("The first bug is in the parser. The second bug is in the renderer.",
     "The bugs are in the parser and the renderer."),
    ("The first bed grows tomatoes. The second bed grows peppers.",
     "The beds grow tomatoes and peppers."),
    ("The first act sets up the conflict. The second act resolves it.",
     "The play's structure sets up and resolves the conflict across two acts."),
    ("The first step is drafting. The second step is editing. The third step is publishing.",
     "The process involves drafting, editing, and publishing."),
    ("The first volunteer waters. The second volunteer weeds. The third volunteer harvests.",
     "Volunteers water, weed, and harvest in turn."),
],
"One-Point Dilution": [
    ("The build was flaky. Tests failed randomly. CI kept timing out. Nobody trusted the pipeline. Deploys were delayed for days.",
     "The build was flaky."),
    ("The garden struggled this year. The soil was poor. Pests got in. Watering was inconsistent. Yields dropped across every bed.",
     "The garden struggled this year."),
    ("The rehearsal ran long. Blocking took forever. Lines weren't memorized. Cues were missed. Everyone left exhausted.",
     "The rehearsal ran long."),
    ("The library's grant fell through. Funding was cut. The maker space stalled. Staff hours shrank. Programs were paused.",
     "The library's grant fell through."),
    ("The sprint slipped. Scope crept. Reviews stalled. Bugs piled up. The release date moved twice.",
     "The sprint slipped."),
],
"Not X. Not Y. Just Z.": [
    ("Not a bug. Not a feature. A missing test case.",
     "This is a missing test case, not a bug or a feature."),
    ("Not neglect. Not carelessness. Just an outdated watering schedule.",
     "An outdated watering schedule caused this, not neglect or carelessness."),
    ("Not a delay. Not a cancellation. A full postponement of the show.",
     "This is a full postponement of the show."),
    ("Not a suggestion. Not a guideline. A requirement for every pull request.",
     "This is a requirement for every pull request."),
    ("Not luck. Not timing. Just a decade of careful pruning.",
     "A decade of careful pruning explains this, not luck or timing."),
],
"Despite Its Challenges": [
    ("Despite the flaky tests, the release shipped on time.",
     "The flaky tests delayed the release by a week."),
    ("Despite the drought, the garden produced a full harvest.",
     "The drought reduced the garden's harvest this year."),
    ("Despite the budget cuts, the library expanded its maker space.",
     "The budget cuts forced the library to scale back its maker space plans."),
    ("Despite the delays, the play opened on schedule.",
     "The delays pushed the play's opening back by two weeks."),
    ("Despite the criticism, the new code style guide has broad support.",
     "The criticism reflects real concerns from developers about the new style guide."),
],
"Fractal Summaries": [
    ("This section covers the deploy checklist. As we've seen, the deploy checklist was covered above.",
     "This section covers the deploy checklist."),
    ("We'll review the garden's watering schedule below. As reviewed above, watering happens twice daily.",
     "The garden's watering schedule, reviewed below, happens twice daily."),
    ("This chapter explains the three rehearsal stages. As explained, there are three stages as covered here.",
     "This chapter explains the three rehearsal stages."),
    ("The next part covers library card requirements. As covered next, requirements are detailed below.",
     "The next part covers library card requirements."),
    ("Below we summarize this season's harvest. As summarized above, the harvest was strong this season.",
     "The harvest was strong this season, summarized below."),
],
}


def _insert_pairs(pairs_by_trope, name_to_id, doc_rows, sent_rows, label_rows, rewrite_rows):
    for name, pairs in pairs_by_trope.items():
        trope_id = name_to_id[name]
        for positive, rewrite in pairs:
            pos_ids = _insert_document(positive, True, True, doc_rows, sent_rows)
            rewrite_ids = _insert_document(rewrite, True, False, doc_rows, sent_rows)
            for sid in pos_ids:
                label_rows.append({
                    "sentence_id": sid, "trope_id": trope_id,
                    "label_source": "synthetic-gen", "confidence": 1.0,
                })
            if pos_ids and rewrite_ids:
                rewrite_rows.append({
                    "rewrite_id": str(uuid.uuid5(REWRITE_NAMESPACE, pos_ids[0])),
                    "sentence_id": pos_ids[0], "trope_id": trope_id,
                    "rewritten_text": rewrite.strip(), "source": "synthetic-gen",
                })


def main():
    tropes = read_tropes()
    name_to_id = dict(zip(tropes.column("name").to_pylist(), tropes.column("trope_id").to_pylist()))

    doc_rows, sent_rows, label_rows, rewrite_rows = [], [], [], []
    _insert_pairs(CLASSIFIER_FLOOR, name_to_id, doc_rows, sent_rows, label_rows, rewrite_rows)
    _insert_pairs(REWRITE_TOPUP, name_to_id, doc_rows, sent_rows, label_rows, rewrite_rows)

    append_rows(SOURCE_DOCUMENT_PATH, doc_rows)
    append_rows(SENTENCE_PATH, sent_rows)
    append_rows(SENTENCE_TROPE_LABEL_PATH, label_rows)
    append_rows(SENTENCE_REWRITE_PATH, rewrite_rows)
    print(f"round 5: {len(doc_rows)} docs, {len(label_rows)} labels, {len(rewrite_rows)} rewrite pairs")


if __name__ == "__main__":
    main()
