# SPDX-License-Identifier: MIT
# Copyright (c) 2026 K. S. Ernest (iFire) Lee
"""Hand-authored STE violation + rewrite pairs for the FLAN-T5 rewriter.

Written directly rather than generated via scripts/synth_generate.py's LLM
call, since that script needs a live ANTHROPIC_API_KEY. Each pair is a
sentence that violates ASD-STE100 rules and its STE-compliant rewrite.

Covers all 28 STE violation categories. Re-running is idempotent.
"""
import hashlib
import sys
import uuid
from datetime import datetime, timezone

import sys
sys.path.insert(0, __file__.rsplit("scripts", 1)[0])

from runtime.datalake import (
    SENTENCE_PATH, SENTENCE_REWRITE_PATH, SENTENCE_TROPE_LABEL_PATH,
    SOURCE_DOCUMENT_PATH, append_rows, read_tropes,
)
from scripts.synth_generate import REWRITE_NAMESPACE

DOC_NS = uuid.UUID("6f1a6f2e-6d0a-4c2e-8e2f-2c9b5b7b6a22")
SENT_NS = uuid.UUID("7a2b7f3e-7e0a-4c2e-8e2f-2c9b5b7b6a33")

# violation_name -> list of (ste_violation_text, ste_compliant_rewrite)
PAIRS = {
    "Passive Voice": [
        ("The file is read by the parser.", "The parser reads the file."),
        ("The screws must be removed by the mechanic.", "The mechanic removes the screws."),
        ("The temperature was adjusted by the operator.", "The operator adjusts the temperature."),
        ("The results are displayed on the screen.", "The screen shows the results."),
        ("The system was restarted by the administrator.", "The administrator restarts the system."),
        ("The valve is closed by the pressure sensor.", "The pressure sensor closes the valve."),
        ("The data was collected by the monitoring tool.", "The monitoring tool collects the data."),
        ("The report will be generated by the application.", "The application generates the report."),
        ("The procedure was followed by the technician.", "The technician follows the procedure."),
        ("The output is verified by the test harness.", "The test harness verifies the output."),
    ],
    "Sentence Too Long (procedural)": [
        ("Remove the four screws that hold the cover in place and then lift the cover carefully from the assembly to access the filter.",
         "Remove the four screws that hold the cover in place. Lift the cover from the assembly. You can now access the filter."),
        ("Turn the power switch to the off position and wait for the indicator light to stop flashing before you open the service panel.",
         "Turn the power switch to OFF. Wait for the indicator light to stop flashing. Open the service panel."),
        ("Disconnect the cable from the rear of the unit and then remove the two screws that secure the mounting bracket to the wall plate.",
         "Disconnect the cable from the rear of the unit. Remove the two screws that secure the mounting bracket to the wall plate."),
        ("Press the reset button on the front panel and hold it for three seconds until the screen shows the calibration menu.",
         "Press the reset button on the front panel. Hold the button for three seconds. The screen shows the calibration menu."),
    ],
    "Sentence Too Long (descriptive)": [
        ("The hydraulic system operates the landing gear, the flaps, the brakes, and the nose wheel steering mechanism simultaneously for improved ground handling.",
         "The hydraulic system operates the landing gear, the flaps, the brakes, and the nose wheel steering mechanism. This gives improved ground handling."),
        ("The monitoring dashboard collects data from all connected sensors and displays the current status of each subsystem in a single view.",
         "The monitoring dashboard collects data from all connected sensors. It shows the current status of each subsystem."),
    ],
    "Semicolon Used": [
        ("Open the panel; remove the fuse.", "Open the panel. Remove the fuse."),
        ("The system is ready; start the test sequence.", "The system is ready. Start the test sequence."),
        ("Check the pressure gauge; it must show 120 psi.", "Check the pressure gauge. It must show 120 psi."),
        ("The error code is E-42; refer to the troubleshooting guide.", "The error code is E-42. Refer to the troubleshooting guide."),
        ("Set the timer to 30 seconds; press the start button.", "Set the timer to 30 seconds. Press the start button."),
    ],
    "Contraction Used": [
        ("Don't remove the screws.", "Do not remove the screws."),
        ("The system won't start without the key.", "The system will not start without the key."),
        ("You'll find the filter behind the access panel.", "You will find the filter behind the access panel."),
        ("It's necessary to calibrate the sensor.", "It is necessary to calibrate the sensor."),
        ("The valve won't close if the pressure is too high.", "The valve will not close if the pressure is too high."),
    ],
    "Nominalization": [
        ("The mechanic performs an analysis of the log.", "The mechanic analyzes the log."),
        ("The operator makes an adjustment to the temperature.", "The operator adjusts the temperature."),
        ("The technician carries out an inspection of the system.", "The technician inspects the system."),
        ("The application provides a description of the error.", "The application describes the error."),
        ("The engineer conducts a review of the design.", "The engineer reviews the design."),
        ("The operator does an installation of the new software.", "The operator installs the new software."),
    ],
    "Marketing Adjective": [
        ("Our robust, cutting-edge solution seamlessly integrates powerful features.", "The solution integrates the features."),
        ("This state-of-the-art system delivers a seamless user experience.", "The system gives the user a clear view of the data."),
        ("The next-generation platform empowers teams to unlock their full potential.", "The platform helps teams to analyze their data."),
        ("Our enterprise-grade solution is battle-tested in production.", "The solution is tested in production."),
        ("The revolutionary new algorithm supercharges performance.", "The new algorithm improves performance."),
    ],
    "Phrasal Verb": [
        ("Spin up the cluster before you deploy.", "Start the cluster before you deploy."),
        ("The installer will reach out to confirm the schedule.", "The installer will contact you to confirm the schedule."),
        ("Dive into the configuration settings to adjust the network.", "Open the configuration settings to adjust the network."),
        ("Kick off the build after the tests pass.", "Start the build after the tests pass."),
        ("Roll out the update to all production servers.", "Send the update to all production servers."),
        ("The administrator tore down the old environment.", "The administrator removed the old environment."),
    ],
    "Banned Synonym": [
        ("We will utilize this framework to facilitate the process.", "We will use this framework to help the process."),
        ("The technician will commence the test sequence.", "The technician will start the test sequence."),
        ("Prior to the installation, ensure the power is off.", "Before the installation, make sure the power is off."),
        ("The system leverages advanced algorithms to optimize performance.", "The system uses advanced algorithms to improve performance."),
        ("Subsequent to the calibration, initiate the measurement.", "After the calibration, start the measurement."),
        ("Additionally, the update includes security fixes.", "The update also includes security fixes."),
        ("There are numerous configuration options available.", "There are many configuration options."),
    ],
    "Modal Hedge": [
        ("It is important to note that the system may fail if you do not follow these steps.", "The system will fail if you do not follow these steps."),
        ("It should be noted that the filter needs regular replacement.", "Replace the filter every 30 days."),
        ("Please note that the access panel must be closed before operation.", "Close the access panel before operation."),
        ("As mentioned above, the sensor calibration is critical for accuracy.", "Calibrate the sensor for accuracy."),
        ("It is worth noting that the error log contains useful diagnostic information.", "Read the error log for diagnostic information."),
    ],
    "-ing Main Verb": [
        ("The system is showing the error message.", "The system shows the error message."),
        ("The pump is running at maximum speed.", "The pump runs at maximum speed."),
        ("The indicator light was flashing when the fault occurred.", "The indicator light flashed when the fault occurred."),
        ("The sensor is measuring the temperature continuously.", "The sensor measures the temperature continuously."),
        ("The application is generating the report.", "The application generates the report."),
    ],
    "Stacked Auxiliaries": [
        ("This may help to improve the stability of the system.", "This improves the stability of the system."),
        ("The new filter may be able to reduce the contamination level.", "The new filter reduces the contamination level."),
        ("This setting can help to reduce power consumption.", "This setting reduces power consumption."),
        ("The backup procedure may help to prevent data loss.", "The backup procedure prevents data loss."),
        ("The calibration routine may help to improve sensor accuracy.", "The calibration routine improves sensor accuracy."),
    ],
    "Missing Article": [
        ("Turn shaft assembly to access filter.", "Turn the shaft assembly to access the filter."),
        ("Remove cover before operating unit.", "Remove the cover before you operate the unit."),
        ("Install new gasket on flange.", "Install a new gasket on the flange."),
        ("Press reset button to clear error.", "Press the reset button to clear the error."),
        ("Set timer to 30 seconds.", "Set the timer to 30 seconds."),
        ("Open access panel.", "Open the access panel."),
    ],
    "Em-Dash Overuse": [
        ("The problem \u2014 and this is the part nobody talks about \u2014 is scale.", "The problem is scale. This is the part that nobody talks about."),
        ("The cache \u2014 which stores frequently-accessed data \u2014 reduces response time.", "The cache stores frequently-accessed data. It reduces response time."),
        ("The procedure \u2014 described in detail below \u2014 must be followed exactly.", "The procedure must be followed exactly. It is described in detail below."),
        ("The error \u2014 code E-42 \u2014 indicates a sensor failure.", "Error code E-42 indicates a sensor failure."),
        ("The sensor \u2014 a type K thermocouple \u2014 measures the exhaust temperature.", "The sensor is a type K thermocouple. It measures the exhaust temperature."),
    ],
    "Long Paragraph": [
        ("The first step is to open the access panel. The second step is to locate the filter. The third step is to remove the old filter. The fourth step is to install the new filter. The fifth step is to close the access panel. The sixth step is to test the system. The seventh step is to record the results.",
         "Open the access panel. Locate the filter. Remove the old filter. Install the new filter. Close the access panel. Test the system. Record the results."),
    ],
    "Unclear Instruction Order": [
        ("Remove the cover if the test fails.", "If the test fails, remove the cover."),
        ("Open the valve when the pressure reaches 100 psi.", "When the pressure reaches 100 psi, open the valve."),
        ("Press the reset button if the error light comes on.", "If the error light comes on, press the reset button."),
        ("Disconnect the power cable before you open the panel.", "Before you open the panel, disconnect the power cable."),
        ("Calibrate the sensor after the warm-up cycle completes.", "After the warm-up cycle completes, calibrate the sensor."),
    ],
    "Three+ Nouns in a Row": [
        ("The overhead panel battery section connector is damaged.", "The connector on the battery section of the overhead panel is damaged."),
        ("Check the engine oil filter housing assembly.", "Check the assembly that contains the oil filter in the engine."),
        ("The data transmission control protocol specification is out of date.", "The specification for the protocol that controls data transmission is out of date."),
        ("Replace the fuel pump pressure regulator valve.", "Replace the valve that regulates the pressure in the fuel pump."),
        ("The left wing leading edge slat actuator failed.", "The actuator of the slat on the leading edge of the left wing failed."),
    ],
    "Stacked Prepositional Phrases": [
        ("The data from the test of the system with the new software in the lab was sent to the engineering team for review.",
         "The engineering team received the data from the system test. The test used the new software. The test was done in the lab."),
        ("The results of the analysis of the samples from the engine at the test facility show contamination above the limit.",
         "The analysis of the engine samples shows contamination above the limit. The samples were taken at the test facility."),
        ("The report on the inspection of the valves in the hydraulic system on the aircraft was submitted to the maintenance manager.",
         "The maintenance manager received the report on the valve inspection. The inspection was done on the hydraulic system of the aircraft."),
    ],
    "Content Duplication": [
        ("The system requires a pressure of 120 psi. The system requires a pressure of 120 psi.", "The system requires a pressure of 120 psi."),
        ("Open the access panel. Remove the screws. Open the access panel. Remove the screws.", "Open the access panel. Remove the screws."),
    ],
    "Historical Analogy Stacking": [
        ("Apple didn't build the first smartphone. Netflix didn't invent streaming. Amazon didn't create online shopping.",
         "The lesson is clear. Each innovation was built on earlier work."),
        ("Ford didn't invent the automobile. Edison didn't invent the light bulb. Bell didn't invent the telephone.",
         "The pattern is the same. Each innovation was built on earlier work."),
    ],
    "Word Choice Appropriateness": [
        ("The pump 'falls' to deliver pressure.", "The pump does not deliver pressure."),
        ("The system 'gets' a temperature of 200 degrees.", "The system reaches a temperature of 200 degrees."),
        ("The valve 'starts' to open when the pressure drops.", "The valve opens when the pressure drops."),
        ("The error 'shows' a code of E-42.", "The error code is E-42."),
    ],
    "Safety-Critical Clarity": [
        ("The system may fail if you do not follow these steps.", "The system will fail if you do not follow these steps. Always follow these steps."),
        ("Improper installation could cause injury.", "Improper installation will cause injury. Do all installation steps correctly."),
        ("You might damage the sensor if you apply too much force.", "Too much force damages the sensor. Apply only light force."),
        ("The cover should be removed with caution.", "Remove the cover with caution. The cover can fall."),
    ],
    "Readability for Non-Native Speakers": [
        ("Subsequent to the cessation of the operational phase, the deactivation of the primary system is required.", "After the system stops, deactivate the system."),
        ("The utilization of the aforementioned methodology is recommended for the deployment task.", "Use the method described above for the deployment task."),
        ("Prior to the commencement of the installation procedure, the verification of the power supply status is necessary.", "Before you start the installation, check that the power supply is OFF."),
        ("The removal of the panel facilitates access to the internal components.", "Remove the panel to access the internal components."),
    ],
    "Technical Noun Consistency": [
        ("The valve is open. Then the regulator is closed. Then the flow controller moves to 50 percent.", "The valve is open. Then the valve is closed. Then the valve moves to 50 percent."),
        ("Install the bracket. Then attach the mounting plate to the frame. Then secure the support arm.", "Install the bracket. Then attach the bracket to the frame. Then secure the bracket."),
    ],
    "Sentence Logic (Makes Good Sense)": [
        ("To prevent damage, press the button.", "Press the button to stop the system. This prevents damage."),
        ("The system fails successfully.", "The system fails. This is the expected behavior."),
    ],
    "Appropriate Technical Verb": [
        ("The system facilitates data transfer.", "The system transfers data."),
        ("The pump utilizes the hydraulic fluid.", "The pump uses the hydraulic fluid."),
        ("The technician leverages the diagnostic tool.", "The technician uses the diagnostic tool."),
        ("The software leverages the database.", "The software reads the database."),
        ("The operator manipulates the control lever.", "The operator moves the control lever."),
    ],
    "Unambiguous Reference": [
        ("Install the bracket and the plate. Then paint it.", "Install the bracket and the plate. Then paint the bracket."),
        ("Connect the cable to the port. Make sure it is secure.", "Connect the cable to the port. Make sure the connection is secure."),
        ("Remove the sensor and the cover. Then clean it.", "Remove the sensor and the cover. Then clean the sensor."),
    ],
    "Excessive Abstraction": [
        ("Manipulate the fastening apparatus.", "Turn the screw."),
        ("Initiate the vertical displacement of the access panel.", "Open the access panel."),
        ("Execute the rotational motion of the control knob.", "Turn the knob."),
        ("Perform the removal of the safety mechanism.", "Remove the safety lock."),
        ("Deactivate the illumination source.", "Turn off the light."),
    ],
}

CLEAN_NEGATIVES = [
    "The parser reads the file.",
    "The operator adjusts the temperature.",
    "The sensor measures the temperature continuously.",
    "Open the access panel.",
    "Remove the cover from the unit.",
    "Press the reset button.",
    "The system is ready.",
    "Start the test sequence.",
    "Do not remove the screws.",
    "The system shows error code E-42.",
    "Before you open the panel, disconnect the power cable.",
    "The solution integrates the features.",
    "The new algorithm improves performance.",
    "We will use this framework.",
    "Make sure the power is off before the installation.",
    "The system will fail if you do not follow these steps.",
    "Replace the filter every 30 days.",
    "The pump runs at maximum speed.",
    "The calibration routine improves sensor accuracy.",
    "Turn the shaft assembly to access the filter.",
    "If the test fails, remove the cover.",
    "The connector on the battery section is damaged.",
    "The engineering team received the data from the system test.",
    "Close the access panel before operation.",
    "Read the error log for diagnostic information.",
]


def _sha256(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main():
    tropes_df = read_tropes().to_pandas()
    name_to_id = dict(zip(tropes_df.name, tropes_df.trope_id))

    doc_rows, sent_rows, label_rows, rewrite_rows = [], [], [], []

    for name, pairs in PAIRS.items():
        tid = name_to_id.get(name)
        if tid is None:
            print(f"  skipping: {name!r} not found in seeds/trope.parquet", file=sys.stderr)
            continue
        for src_text, tgt_text in pairs:
            doc_sha = _sha256(src_text)
            doc_id = str(uuid.uuid5(DOC_NS, doc_sha))
            doc_rows.append({
                "doc_id": doc_id, "source": "ste-synth", "url": None, "sha256": doc_sha,
                "fetched_at": datetime.now(timezone.utc).isoformat(),
                "is_ai_generated": True, "is_synthetic": True,
            })
            sent_id = str(uuid.uuid5(SENT_NS, f"{doc_id}:0"))
            sent_rows.append({
                "sentence_id": sent_id, "doc_id": doc_id, "ordinal": 0,
                "char_start": 0, "char_end": len(src_text), "text": src_text,
            })
            label_rows.append({
                "sentence_id": sent_id, "trope_id": tid,
                "label_source": "synthetic-ste", "confidence": 1.0,
            })
            rewrite_id = str(uuid.uuid5(REWRITE_NAMESPACE, sent_id))
            rewrite_rows.append({
                "rewrite_id": rewrite_id, "sentence_id": sent_id, "trope_id": tid,
                "rewritten_text": tgt_text, "source": "synthetic-ste",
            })

    for text in CLEAN_NEGATIVES:
        doc_sha = _sha256(text)
        doc_id = str(uuid.uuid5(DOC_NS, doc_sha))
        doc_rows.append({
            "doc_id": doc_id, "source": "ste-synth-clean", "url": None, "sha256": doc_sha,
            "fetched_at": datetime.now(timezone.utc).isoformat(),
            "is_ai_generated": False, "is_synthetic": True,
        })
        sent_id = str(uuid.uuid5(SENT_NS, f"{doc_id}:0"))
        sent_rows.append({
            "sentence_id": sent_id, "doc_id": doc_id, "ordinal": 0,
            "char_start": 0, "char_end": len(text), "text": text,
        })

    if doc_rows:
        append_rows(SOURCE_DOCUMENT_PATH, doc_rows)
        append_rows(SENTENCE_PATH, sent_rows)
        if label_rows:
            append_rows(SENTENCE_TROPE_LABEL_PATH, label_rows)
        if rewrite_rows:
            append_rows(SENTENCE_REWRITE_PATH, rewrite_rows)
        print(f"wrote {len(doc_rows)} docs, {len(sent_rows)} sents, {len(label_rows)} labels, {len(rewrite_rows)} rewrites", file=sys.stderr)
    else:
        print("no new pairs to insert", file=sys.stderr)


if __name__ == "__main__":
    main()