# SPDX-License-Identifier: MIT
# Copyright (c) 2026 K. S. Ernest (iFire) Lee
"""
Second hand-authored batch, additive to scripts/synth_seed_examples.py.
Written because no ANTHROPIC_API_KEY is available (now or in the near
future per explicit user direction), so scripts/synth_generate.py's
LLM-scaled generation path can't run -- this is the fallback for actually
growing per-trope coverage instead.

Targets the 25 tropes that were still under 100 positive examples after
round 1 (7 of them sitting at the bare floor of 10) with a fresh batch of
~15 more each, in different topic domains (healthcare, education, sports,
travel, cooking, finance, environment, civic life) than round 1's mostly
tech/business examples, plus a smaller top-up of rewrite pairs for the
handful of tropes round 1 already covered well via regex.

Safe to re-run: runtime.datalake.append_rows now drops exact-duplicate
rows, so this and synth_seed_examples.py can both run against the same
persistent data/ directory without double-inserting.
"""
import sys
import uuid

sys.path.insert(0, __file__.rsplit("scripts", 1)[0])
from runtime.datalake import (
    SENTENCE_PATH, SENTENCE_REWRITE_PATH, SENTENCE_TROPE_LABEL_PATH,
    SOURCE_DOCUMENT_PATH, append_rows, read_tropes,
)
from scripts.synth_generate import REWRITE_NAMESPACE, _insert_document

PAIRS = {
"Bold-First Bullets": [
    ("- **Cost:** the trip came in under budget.\n- **Weather:** three sunny days out of four.",
     "- The trip came in under budget.\n- There were three sunny days out of four."),
    ("- **Attendance:** the clinic saw a record number of patients.\n- **Wait times:** average wait dropped to nine minutes.",
     "- The clinic saw a record number of patients.\n- Average wait dropped to nine minutes."),
    ("- **Yield:** the orchard produced twice last year's harvest.\n- **Quality:** fewer fruit were damaged by frost.",
     "- The orchard produced twice last year's harvest.\n- Fewer fruit were damaged by frost."),
    ("- **Turnout:** more students joined the debate club this year.\n- **Results:** the team won two regional rounds.",
     "- More students joined the debate club this year.\n- The team won two regional rounds."),
    ("- **Savings:** the new furnace cut the heating bill by a third.\n- **Comfort:** the house stays warmer overnight.",
     "- The new furnace cut the heating bill by a third.\n- The house stays warmer overnight."),
    ("- **Speed:** the marathon route was faster this year.\n- **Safety:** fewer runners needed medical attention.",
     "- The marathon route was faster this year.\n- Fewer runners needed medical attention."),
    ("- **Freshness:** the market sources produce daily.\n- **Variety:** twelve new vendors joined this season.",
     "- The market sources produce daily.\n- Twelve new vendors joined this season."),
    ("- **Enrollment:** the class filled up in two days.\n- **Feedback:** most students rated it highly.",
     "- The class filled up in two days.\n- Most students rated it highly."),
    ("- **Recovery:** patients left the hospital a day earlier on average.\n- **Satisfaction:** survey scores rose.",
     "- Patients left the hospital a day earlier on average.\n- Survey scores rose."),
    ("- **Traffic:** the new signal cut wait times at the intersection.\n- **Safety:** accidents there dropped to zero.",
     "- The new signal cut wait times at the intersection.\n- Accidents there dropped to zero."),
    ("- **Yield:** the vineyard's harvest grew by 20 percent.\n- **Taste:** tasters preferred the new blend.",
     "- The vineyard's harvest grew by 20 percent.\n- Tasters preferred the new blend."),
    ("- **Turnaround:** repairs now take two days instead of five.\n- **Cost:** parts spending dropped.",
     "- Repairs now take two days instead of five.\n- Parts spending dropped."),
    ("- **Retention:** fewer employees left this quarter.\n- **Morale:** survey scores improved.",
     "- Fewer employees left this quarter.\n- Survey scores improved."),
    ("- **Accuracy:** the new scale weighs to the gram.\n- **Speed:** checkout lines moved faster.",
     "- The new scale weighs to the gram.\n- Checkout lines moved faster."),
    ("- **Coverage:** the trail map now includes every fork.\n- **Clarity:** hikers reported fewer wrong turns.",
     "- The trail map now includes every fork.\n- Hikers reported fewer wrong turns."),
],
"False Vulnerability": [
    ("I'll admit it, I was terrified before the first surgery I performed alone.",
     "I was nervous before the first surgery I performed alone."),
    ("I'm not too proud to say the recipe failed twice before I got it right.",
     "The recipe failed twice before I got it right."),
    ("Honestly, I doubted the team could hit the harvest deadline, and I was wrong.",
     "The team hit the harvest deadline despite my doubts."),
    ("I'll be the first to admit I underestimated how hard the trail would be.",
     "The trail was harder than expected."),
    ("Confession: I almost skipped the safety drill, and I'm glad I didn't.",
     "The safety drill turned out to be worthwhile."),
    ("I used to think the class was a waste of time, and I was completely wrong.",
     "The class turned out to be worthwhile."),
    ("I won't pretend the move was easy; it took months to feel settled.",
     "The move took months before it felt settled."),
    ("I'll admit, I cried during the graduation ceremony.",
     "I was emotional during the graduation ceremony."),
    ("I'm not ashamed to say the first draft of the grant was rejected.",
     "The first draft of the grant was rejected."),
    ("Honestly, I was skeptical of the diet at first, and the results changed my mind.",
     "The diet's results changed my initial skepticism."),
    ("I'll admit it: I nearly quit the training program in week two.",
     "I nearly quit the training program in week two."),
    ("I used to doubt remote clinics could work, and this one proved me wrong.",
     "This remote clinic proved effective despite early doubts."),
    ("I'm not too proud to admit the budget spreadsheet had an error for months.",
     "The budget spreadsheet had an error for months."),
    ("I'll be honest, I didn't expect the fundraiser to raise this much.",
     "The fundraiser raised more than expected."),
    ("I won't hide it: the first year of the restaurant nearly broke us.",
     "The first year of the restaurant was financially difficult."),
],
"Invented Concept Labels": [
    ("This is a case of what I'd call the harvest lag: yields improve years after the soil work is done.",
     "This shows how soil improvements take years to affect yields."),
    ("We're seeing the classroom drift, where attention fades the same time every afternoon.",
     "Attention tends to fade every afternoon in the classroom."),
    ("Call it the commute creep: each new road slightly lengthens the average trip.",
     "Each new road has slightly lengthened the average commute."),
    ("This is the recovery plateau every physical therapy patient eventually hits.",
     "This is the point where physical therapy progress slows for most patients."),
    ("We're witnessing the loyalty erosion effect after the price increase.",
     "Customer loyalty declined after the price increase."),
    ("This is a textbook demand echo: sales spike again a month after the sale ends.",
     "Sales tend to spike again about a month after a sale ends."),
    ("Call it the onboarding fog: new volunteers rarely retain the first-day training.",
     "New volunteers rarely retain what they learn on the first day."),
    ("This is the classic renovation spiral, where one fix reveals three more.",
     "One repair often reveals the need for several more."),
    ("We're in what I'd call the harvest window anxiety phase of the season.",
     "Farmers are anxious about the narrow harvest window this season."),
    ("This is the seasonal dip nearly every retailer sees after the holidays.",
     "Sales typically dip for most retailers after the holidays."),
    ("Call it the second-year slump every new teacher seems to hit.",
     "Many new teachers experience a difficult second year."),
    ("This is a clear case of the referral cliff after the campaign ended.",
     "Referrals dropped sharply after the campaign ended."),
    ("We're seeing the trust rebound now that the recall was resolved.",
     "Customer trust is recovering now that the recall was resolved."),
    ("This is the classic burnout curve among first-responders after a long shift season.",
     "Many first responders experience burnout after a long shift season."),
    ("Call it the attendance cliff schools see right before graduation.",
     "Schools typically see attendance drop right before graduation."),
],
"Grandiose Stakes Inflation": [
    ("This new bike lane will change the entire future of how our city moves.",
     "This new bike lane will make one commute route safer."),
    ("This school lunch program marks a turning point for the whole nation's health.",
     "This school lunch program improves meals for one district."),
    ("This is more than a bake sale; it's a movement that will redefine the neighborhood.",
     "This bake sale raised money for the neighborhood park."),
    ("This small clinic will transform healthcare as we know it.",
     "This clinic will improve access to care in this town."),
    ("This is the moment that changes everything for local farmers everywhere.",
     "This program will help several local farmers this season."),
    ("This one recipe will revolutionize how the world thinks about breakfast.",
     "This recipe offers a quicker breakfast option."),
    ("This library renovation isn't just a remodel; it's a rebirth for the entire town.",
     "This library renovation adds a new reading room and better lighting."),
    ("This youth program will shape the destiny of an entire generation.",
     "This youth program will mentor twenty students this year."),
    ("This trail expansion redefines what it means to be an outdoor city.",
     "This trail expansion adds two miles of new path."),
    ("This is the single decision that will determine the fate of the whole league.",
     "This decision affects next season's schedule."),
    ("This tutoring session isn't just help with math; it's a life-altering intervention.",
     "This tutoring session covers this week's math homework."),
    ("This community garden will change the course of the entire city's food system.",
     "This community garden supplies vegetables to a few nearby blocks."),
    ("This is bigger than a new stoplight; it's a revolution in public safety.",
     "This new stoplight improves safety at one intersection."),
    ("This volunteer drive will reshape the future of the whole shelter system.",
     "This volunteer drive adds ten more helpers to the shelter."),
    ("This single lecture will change how humanity understands the ocean forever.",
     "This lecture covers recent findings about coral reefs."),
],
"The Dead Metaphor": [
    ("The recipe is a journey, and every ingredient in the recipe continues that journey to the plate.",
     "The recipe combines several ingredients into a finished dish."),
    ("The classroom is a garden, and the garden's seeds sprout into the garden of the mind.",
     "The classroom helps students develop new ideas."),
    ("The trail is a story, and every step on the trail writes another line of that story.",
     "The trail offers scenic views along the way."),
    ("The team is an engine, and the engine's parts keep the engine of the season running.",
     "The team works well together this season."),
    ("The harvest is a symphony, and every crop plays its part in the symphony of the season.",
     "The harvest brings together several different crops this season."),
    ("The clinic is a lighthouse, guiding patients through the fog toward the lighthouse's light.",
     "The clinic helps guide patients toward better care."),
    ("The budget is a ship, and the ship's crew steers the budget-ship through rough seas.",
     "The finance team manages the budget carefully."),
    ("The library is a bridge, connecting readers across the bridge to new worlds.",
     "The library connects readers to new books and ideas."),
    ("The market is a river, and the river's current carries the market's flow of goods.",
     "The market brings a steady flow of goods to the town."),
    ("The season is a marathon, and every mile of the marathon tests the season's runners.",
     "The season is long and tests the team's endurance."),
    ("The orchard is a canvas, painted anew each spring by the orchard's blossoms.",
     "The orchard blooms freshly each spring."),
    ("The program is a ladder, and every rung of the ladder lifts participants up the ladder.",
     "The program helps participants advance step by step."),
    ("The festival is a tapestry, woven from threads that make up the festival's tapestry.",
     "The festival brings together many different local traditions."),
    ("The kitchen is a stage, and every dish performed on that stage tells the kitchen's story.",
     "The kitchen produces a variety of dishes each night."),
    ("The clinic is a compass, pointing patients toward the compass heading of good health.",
     "The clinic helps guide patients toward better health."),
],
"The Truth Is Simple": [
    ("The truth is simple: the clinic ran out of staff, not funding.",
     "The clinic ran out of staff, not funding."),
    ("The reality is simpler than people admit: the harvest failed because of late frost.",
     "The harvest failed because of late frost."),
    ("The truth is simple: most students skip the readings, not the lectures.",
     "Most students skip the readings, not the lectures."),
    ("The reality is simple: the trail closed because of erosion, not funding cuts.",
     "The trail closed because of erosion, not funding cuts."),
    ("The truth is simple: the team lost because of injuries, not effort.",
     "The team lost because of injuries, not effort."),
    ("The reality is simpler than the report suggests: the delay was a parts shortage.",
     "The delay was caused by a parts shortage."),
    ("The truth is simple: fewer volunteers signed up this year than last.",
     "Fewer volunteers signed up this year than last."),
    ("The reality is simple: the recipe failed because the oven ran cold.",
     "The recipe failed because the oven ran cold."),
    ("The truth is simple: attendance dropped because of the schedule change.",
     "Attendance dropped because of the schedule change."),
    ("The reality is simpler than it sounds: the bridge needs new bolts, not a redesign.",
     "The bridge needs new bolts, not a redesign."),
    ("The truth is simple: the garden struggled because of poor drainage.",
     "The garden struggled because of poor drainage."),
    ("The reality is simple: the clinic's wait times grew because two nurses left.",
     "The clinic's wait times grew because two nurses left."),
    ("The truth is simple: the team missed the grant deadline by one day.",
     "The team missed the grant deadline by one day."),
    ("The reality is simpler than the excuses: the shipment was late, not lost.",
     "The shipment was late, not lost."),
    ("The truth is simple: ticket sales dropped because of the weather forecast.",
     "Ticket sales dropped because of the weather forecast."),
],
"Superficial Analyses": [
    ("The bakery opened a second location, extending its role in the neighborhood's daily rhythm.",
     "The bakery opened a second location."),
    ("The nurse finished her shift early, reflecting her efficient approach to patient care.",
     "The nurse finished her shift early."),
    ("The farmer rotated the crops this season, deepening the soil's long-term fertility.",
     "The farmer rotated the crops this season."),
    ("The team practiced an extra hour, underscoring their dedication to the championship.",
     "The team practiced an extra hour."),
    ("The clinic added a new scanner, further advancing its commitment to modern care.",
     "The clinic added a new scanner."),
    ("The choir rehearsed on Sunday, reinforcing the community's shared love of music.",
     "The choir rehearsed on Sunday."),
    ("The shop extended its hours, reflecting a broader dedication to customer convenience.",
     "The shop extended its hours."),
    ("The runner logged an extra mile, showcasing her disciplined training regimen.",
     "The runner logged an extra mile."),
    ("The council repaved the road, signaling a renewed investment in local infrastructure.",
     "The council repaved the road."),
    ("The teacher stayed late, further demonstrating her commitment to her students.",
     "The teacher stayed late."),
    ("The orchard added beehives, enriching the ecosystem's natural pollination cycle.",
     "The orchard added beehives."),
    ("The clinic hired a translator, reflecting its broader mission of accessible care.",
     "The clinic hired a translator."),
    ("The library added a reading nook, deepening its role as a community gathering space.",
     "The library added a reading nook."),
    ("The chef sourced local eggs, tying the menu to the region's farming heritage.",
     "The chef sourced local eggs."),
    ("The team added a new drill, reflecting the coach's evolving philosophy.",
     "The team added a new drill."),
],
"Quietly and Other Magic Adverbs": [
    ("The new schedule is quietly easing the strain on the night shift.",
     "The new schedule eased the strain on the night shift."),
    ("Her mentorship deeply shaped how the interns approach patient care.",
     "Her mentorship shaped how the interns approach patient care."),
    ("The irrigation change is fundamentally improving the orchard's yield.",
     "The irrigation change improved the orchard's yield."),
    ("The new curriculum is quietly reshaping how students think about history.",
     "The new curriculum changed how students think about history."),
    ("This small grant is remarkably transforming the shelter's daily operations.",
     "This small grant changed the shelter's daily operations."),
    ("The revised route is quietly cutting commute times across the district.",
     "The revised route cut commute times across the district."),
    ("Her coaching style is deeply influencing how the team handles pressure.",
     "Her coaching style changed how the team handles pressure."),
    ("The new tool is fundamentally altering how the clinic schedules patients.",
     "The new tool changed how the clinic schedules patients."),
    ("This policy is quietly reducing food waste at the cafeteria.",
     "This policy reduced food waste at the cafeteria."),
    ("The renovation is deeply changing how visitors experience the museum.",
     "The renovation changed how visitors experience the museum."),
    ("The new fertilizer mix is remarkably boosting this season's yield.",
     "The new fertilizer mix boosted this season's yield."),
    ("Her leadership is quietly transforming the volunteer program's culture.",
     "Her leadership changed the volunteer program's culture."),
    ("The updated forms are fundamentally simplifying patient intake.",
     "The updated forms simplified patient intake."),
    ("This new lighting is quietly improving safety along the trail.",
     "This new lighting improved safety along the trail."),
    ("The pilot class is deeply reshaping how the school teaches reading.",
     "The pilot class changed how the school teaches reading."),
],
"Here's the Kicker": [
    ("Here's the kicker: the harvest was better after the drought than before it.",
     "The harvest was better after the drought than before it."),
    ("Here's the thing: the clinic's busiest day is actually a Wednesday.",
     "The clinic's busiest day is actually a Wednesday."),
    ("Here's where it gets interesting: the cheapest seats sold out first.",
     "The cheapest seats sold out first."),
    ("Here's the kicker: the youngest runner finished ahead of the favorites.",
     "The youngest runner finished ahead of the favorites."),
    ("Here's the thing about the budget: it came in under, not over.",
     "The budget came in under, not over."),
    ("Here's where it gets interesting: the smallest classroom had the best test scores.",
     "The smallest classroom had the best test scores."),
    ("Here's the kicker: the backup generator never even turned on.",
     "The backup generator never even turned on."),
    ("Here's the thing: the volunteers outnumbered the staff two to one.",
     "The volunteers outnumbered the staff two to one."),
    ("Here's where it gets interesting: the recipe works better without the extra sugar.",
     "The recipe works better without the extra sugar."),
    ("Here's the kicker: the delay actually improved the final design.",
     "The delay actually improved the final design."),
    ("Here's the thing about the trail: it's shorter than the map suggests.",
     "The trail is shorter than the map suggests."),
    ("Here's where it gets interesting: the oldest tractor was the most reliable one.",
     "The oldest tractor was the most reliable one."),
    ("Here's the kicker: the free clinic saw more patients than the paid one.",
     "The free clinic saw more patients than the paid one."),
    ("Here's the thing: the quietest student asked the best question.",
     "The quietest student asked the best question."),
    ("Here's where it gets interesting: the rain actually helped the festival turnout.",
     "The rain actually helped the festival turnout."),
],
"Let's Break This Down": [
    ("Let's break this down step by step, starting with the harvest schedule.",
     "Here is the harvest schedule."),
    ("Let's unpack this a bit: first the diagnosis, then the treatment plan.",
     "Here is the diagnosis, followed by the treatment plan."),
    ("Let's walk through the recipe together, one step at a time.",
     "Here are the recipe steps."),
    ("To make this simple, let's go through the budget slowly.",
     "Here is the budget."),
    ("Let's break this down so the trail directions are easier to follow.",
     "Here are the trail directions."),
    ("Let's take a moment to break down what caused the delay.",
     "Here is what caused the delay."),
    ("Let's break the lesson into smaller, easier pieces.",
     "Here is the lesson, broken into smaller pieces."),
    ("Let's simplify this and go through the schedule one step at a time.",
     "Here is the schedule."),
    ("Let's break down exactly why the crop yield was lower this year.",
     "Here is why the crop yield was lower this year."),
    ("Let's walk through the intake form together, section by section.",
     "Here is the intake form, section by section."),
    ("Let's break this down: first the symptoms, then the possible causes.",
     "Here are the symptoms and their possible causes."),
    ("Let's unpack the schedule change and what it means for the team.",
     "Here is the schedule change and what it means for the team."),
    ("Let's break this down slowly so nobody misses a step in the drill.",
     "Here are the drill steps."),
    ("Let's walk through the grant application requirements together.",
     "Here are the grant application requirements."),
    ("Let's break this down into the three phases of the renovation.",
     "Here are the three phases of the renovation."),
],
"Vague Attributions": [
    ("Experts say the drought will worsen before it improves.",
     "The National Weather Service says the drought will worsen before it improves."),
    ("Observers note attendance has fallen at town meetings this year.",
     "The town clerk notes attendance has fallen at town meetings this year."),
    ("Reports suggest the clinic may add weekend hours next year.",
     "A hospital board memo suggests the clinic may add weekend hours next year."),
    ("Some say the new bridge design is safer than the old one.",
     "The county engineer says the new bridge design is safer than the old one."),
    ("Critics argue the new zoning rules will raise rents.",
     "The local tenants' association argues the new zoning rules will raise rents."),
    ("It is widely believed that the harvest festival boosts local sales.",
     "A 2023 chamber of commerce survey found the harvest festival boosts local sales."),
    ("Many experts warn of a rough flu season this year.",
     "The state health department warns of a rough flu season this year."),
    ("Sources close to the team say the coach may retire after this season.",
     "Two players say the coach may retire after this season."),
    ("Analysts believe the orchard's yields will recover next year.",
     "The county agricultural extension believes the orchard's yields will recover next year."),
    ("Some researchers claim the new curriculum improves reading scores.",
     "A university study claims the new curriculum improves reading scores."),
    ("Officials say the road closure will last through the summer.",
     "The city's public works director says the road closure will last through the summer."),
    ("It's said that the clinic's new hours reduced emergency visits.",
     "The clinic's own records show the new hours reduced emergency visits."),
    ("People believe the market's prices are lower than the supermarket's.",
     "A price comparison by the local paper found the market's prices are lower."),
    ("Some claim the new bus route cut commute times significantly.",
     "Transit authority data shows the new bus route cut commute times significantly."),
    ("Experts suggest the reservoir levels will stabilize by fall.",
     "The water utility suggests the reservoir levels will stabilize by fall."),
],
"Imagine a World Where": [
    ("Imagine a world where every farm has real-time soil sensors.",
     "Real-time soil sensors could become common on farms."),
    ("Imagine a world where no patient waits more than ten minutes.",
     "Shorter clinic waits could become the norm."),
    ("Imagine a world where every classroom has enough books for every student.",
     "Every classroom could eventually have enough books for every student."),
    ("Imagine a world where flooding never closes the only road into town.",
     "Better infrastructure could prevent flooding from closing the only road."),
    ("Imagine a world where every recipe adjusts itself to what's in your fridge.",
     "Recipes could eventually adjust to available ingredients."),
    ("Imagine a world where every shelter has enough beds for winter.",
     "Shelters could eventually have enough beds for winter."),
    ("Imagine a world where public transit never runs late.",
     "More reliable scheduling could keep public transit on time."),
    ("Imagine a world where every farmer gets fair prices at market.",
     "Fairer pricing could become standard for farmers."),
    ("Imagine a world where no student falls behind for lack of tutoring.",
     "Wider tutoring access could help prevent students from falling behind."),
    ("Imagine a world where every small town has a working health clinic.",
     "Every small town could eventually have a working health clinic."),
    ("Imagine a world where harvest losses from pests were a thing of the past.",
     "Better pest management could reduce harvest losses."),
    ("Imagine a world where every library stays open on weekends.",
     "Weekend hours could become standard for libraries."),
],
"Content Duplication": [
    ("The clinic added weekend hours starting in March. The clinic added weekend hours starting in March.",
     "The clinic added weekend hours starting in March."),
    ("The harvest came in three weeks early this year. The harvest came in three weeks early this year.",
     "The harvest came in three weeks early this year."),
    ("The team won the regional tournament last weekend. The team won the regional tournament last weekend.",
     "The team won the regional tournament last weekend."),
    ("The library extended its hours during exam week. The library extended its hours during exam week.",
     "The library extended its hours during exam week."),
    ("The new bridge opens to traffic next month. The new bridge opens to traffic next month.",
     "The new bridge opens to traffic next month."),
    ("The clinic hired two new nurses this spring. The clinic hired two new nurses this spring.",
     "The clinic hired two new nurses this spring."),
    ("The festival raised more money than last year. The festival raised more money than last year.",
     "The festival raised more money than last year."),
    ("The trail reopened after the winter closure. The trail reopened after the winter closure.",
     "The trail reopened after the winter closure."),
    ("The bakery added gluten-free options this month. The bakery added gluten-free options this month.",
     "The bakery added gluten-free options this month."),
    ("The school added a new bus route this fall. The school added a new bus route this fall.",
     "The school added a new bus route this fall."),
    ("The orchard's apple crop was smaller this year. The orchard's apple crop was smaller this year.",
     "The orchard's apple crop was smaller this year."),
    ("The shelter took in more animals this winter. The shelter took in more animals this winter.",
     "The shelter took in more animals this winter."),
],
"Fractal Summaries": [
    ("This section covers the harvest schedule. As we've seen, the harvest schedule was covered above.",
     "This section covers the harvest schedule."),
    ("We'll review the clinic's new hours below. As reviewed above, the clinic added new hours.",
     "The clinic added new hours, reviewed below."),
    ("This chapter explains the trail's three loops. As explained, the trail has three loops as covered here.",
     "This chapter explains the trail's three loops."),
    ("The next part covers grant requirements. As covered next, grant requirements are detailed below.",
     "The next part covers grant requirements."),
    ("This guide explains the intake process in four steps. As we've just seen, intake takes four steps as explained.",
     "This guide explains the four-step intake process."),
    ("Below we summarize this year's yields. As summarized above, yields were strong this year.",
     "Yields were strong this year, summarized below."),
    ("This section outlines the new bus routes. As outlined above, three new routes were added.",
     "This section outlines the three new bus routes."),
    ("We will now review the festival timeline. As reviewed, the festival ran for three days as noted.",
     "The festival timeline, reviewed below, ran for three days."),
    ("This part covers volunteer shifts. As covered, shifts run in three-hour blocks as detailed here.",
     "This part covers the three-hour volunteer shifts."),
    ("The following section explains the vaccine schedule. As explained above, doses are spaced by a month.",
     "The following section explains the vaccine schedule, spaced a month apart."),
    ("This chapter introduces the clinic's referral process. As introduced, referrals go through the front desk.",
     "This chapter introduces the clinic's referral process, which goes through the front desk."),
    ("Below we cover the orchard's pruning schedule. As covered above, pruning happens each February.",
     "The orchard's pruning schedule, covered below, happens each February."),
],
"Negative Parallelism": [
    ("It's not a shortage. It's mismanagement.",
     "This is mismanagement, not a shortage."),
    ("It's not the weather. It's the drainage.",
     "The drainage caused this, not the weather."),
    ("It's not bad luck. It's poor planning.",
     "Poor planning caused this, not bad luck."),
    ("It's not a small fix. It's a full rebuild of the irrigation system.",
     "This is a full rebuild of the irrigation system."),
    ("It's not overcrowding. It's understaffing.",
     "Understaffing caused this, not overcrowding."),
    ("It's not a delay. It's a cancellation.",
     "This is a cancellation, not a delay."),
    ("It's not the recipe. It's the oven.",
     "The oven caused this, not the recipe."),
    ("It's not a coincidence that yields rose. It's the new fertilizer.",
     "The new fertilizer caused yields to rise."),
    ("It's not carelessness. It's an outdated manual.",
     "An outdated manual caused this, not carelessness."),
    ("It's not a minor issue. It's a structural crack.",
     "This is a structural crack."),
    ("It's not the schedule. It's the staffing.",
     "Staffing caused this, not the schedule."),
    ("It's not luck that the harvest held. It's the new irrigation line.",
     "The new irrigation line saved the harvest."),
],
"Listicle in a Trench Coat": [
    ("The first cause is soil depletion. The second cause is late frost.",
     "The causes are soil depletion and late frost."),
    ("The first symptom is fatigue. The second symptom is fever.",
     "The symptoms are fatigue and fever."),
    ("The first step is soaking the beans. The second step is simmering them.",
     "The recipe involves soaking then simmering the beans."),
    ("The first option is the morning shift. The second option is the evening shift.",
     "The options are the morning or evening shift."),
    ("The first obstacle is funding. The second obstacle is permits.",
     "The obstacles are funding and permits."),
    ("The first phase covers demolition. The second phase covers rebuilding.",
     "The project has a demolition phase and a rebuilding phase."),
    ("The first group meets on Mondays. The second group meets on Thursdays.",
     "The groups meet on Mondays and Thursdays."),
    ("The first reason is the drought. The second reason is the frost.",
     "The reasons are the drought and the frost."),
    ("The first stop is the visitor center. The second stop is the overlook.",
     "The trail passes the visitor center and the overlook."),
    ("The first requirement is a deposit. The second requirement is proof of insurance.",
     "The requirements are a deposit and proof of insurance."),
    ("The first sign was the cracked pipe. The second sign was low water pressure.",
     "The warning signs were the cracked pipe and low water pressure."),
    ("The first benefit is lower costs. The second benefit is faster delivery.",
     "The benefits are lower costs and faster delivery."),
],
"Historical Analogy Stacking": [
    ("The old mill closed. The cannery closed. The shipyard closed.",
     "Several local industries, including the mill, cannery, and shipyard, have closed over the years."),
    ("The 1990s brought the highway. The 2000s brought the mall. The 2010s brought the outlet stores.",
     "New commercial development arrived in each of the last three decades."),
    ("The drought hit in 1988. It hit again in 2002. It hit again in 2021.",
     "The region has faced drought roughly every decade."),
    ("The clinic started as a single room. It became a wing. It became a hospital.",
     "The clinic grew over time from a single room into a full hospital."),
    ("The farm started with wheat. It added dairy. It added orchards.",
     "The farm expanded from wheat into dairy and orchards over time."),
    ("The old bridge flooded in 1972. The new one flooded in 1996. This one hasn't yet.",
     "Earlier bridges at this site flooded in 1972 and 1996."),
    ("The union formed in the 1930s. It grew in the 1960s. It shrank in the 1990s.",
     "The union's membership has changed significantly since the 1930s."),
    ("The theater opened as a cinema. It became a music hall. It's now a community center.",
     "The theater has served several different purposes since it opened."),
    ("The school started with twenty students. Then a hundred. Now over a thousand.",
     "The school's enrollment grew from twenty students to over a thousand."),
    ("The market began as a single stall. Then a row of stalls. Now a full building.",
     "The market grew from a single stall into a full building."),
    ("The line began with rotary phones. Then push-button. Now none at all.",
     "The town's phone infrastructure changed significantly over the decades."),
    ("The orchard survived the freeze in '85. It survived the drought in '12. This year tested it again.",
     "The orchard has survived a freeze, a drought, and other challenges over the years."),
],
"Short Punchy Fragments": [
    ("The rain stopped. Suddenly. Without warning.",
     "The rain stopped suddenly, without warning."),
    ("The harvest failed. Completely. For the first time in years.",
     "The harvest failed completely, for the first time in years."),
    ("She left the clinic. Early. Without explanation.",
     "She left the clinic early, without explanation."),
    ("The bridge cracked. Overnight. Under the weight of the storm.",
     "The bridge cracked overnight under the weight of the storm."),
    ("He signed the lease. Quickly. Before the price changed.",
     "He signed the lease quickly, before the price changed."),
    ("The well ran dry. Suddenly. In the middle of summer.",
     "The well ran dry suddenly, in the middle of summer."),
    ("They canceled the festival. Reluctantly. Due to the storm warning.",
     "They reluctantly canceled the festival due to the storm warning."),
    ("The clinic closed. Temporarily. For renovations.",
     "The clinic closed temporarily for renovations."),
    ("She finished the marathon. Barely. In under five hours.",
     "She barely finished the marathon, in under five hours."),
    ("The crop recovered. Slowly. Over several weeks.",
     "The crop recovered slowly, over several weeks."),
    ("He retired. Suddenly. After thirty years.",
     "He retired suddenly, after thirty years."),
    ("The shelter filled up. Fast. Within a single week.",
     "The shelter filled up fast, within a single week."),
],
"Anaphora Abuse": [
    ("They assume the harvest will hold. They assume the rain will come. They assume the prices will stay flat.",
     "They assume the harvest will hold, the rain will come, and prices will stay flat."),
    ("We believe in fair pay. We believe in safe conditions. We believe in honest hours.",
     "We believe in fair pay, safe conditions, and honest hours."),
    ("This is a story about loss. This is a story about recovery. This is a story about rebuilding.",
     "This is a story about loss, recovery, and rebuilding."),
    ("Every clinic wants more staff. Every clinic wants more funding. Every clinic wants more space.",
     "Every clinic wants more staff, funding, and space."),
    ("She checked the levees alone. She reinforced them alone. She reported the damage alone.",
     "She checked, reinforced, and reported on the levees alone."),
    ("The report ignores the delays. The report ignores the shortages. The report ignores the complaints.",
     "The report ignores the delays, shortages, and complaints."),
    ("We need better roads. We need better drainage. We need better lighting.",
     "We need better roads, drainage, and lighting."),
    ("He checked the traps twice. He checked the traps three times. He still found nothing.",
     "He checked the traps several times and still found nothing."),
    ("The town promised faster repairs. The town promised lower fees. The town promised better service.",
     "The town promised faster repairs, lower fees, and better service."),
    ("This changes how we plant. This changes how we harvest. This changes how we sell.",
     "This changes how we plant, harvest, and sell."),
    ("They wanted more rain. They wanted less wind. They wanted a longer growing season.",
     "They wanted more rain, less wind, and a longer growing season."),
    ("She trained every morning. She trained every evening. She trained on weekends too.",
     "She trained every morning, evening, and weekend."),
],
"Not X. Not Y. Just Z.": [
    ("Not a delay. Not a setback. A complete cancellation.",
     "This is a complete cancellation."),
    ("Not slow service. Not understaffing. Just a broken reservation system.",
     "A broken reservation system caused this, not slow service or understaffing."),
    ("Not a fad. Not a trend. A lasting shift in how people farm.",
     "This is a lasting shift in how people farm."),
    ("Not neglect. Not carelessness. Just an outdated irrigation manual.",
     "An outdated irrigation manual caused this."),
    ("Not a suggestion. Not a guideline. A requirement for every clinic.",
     "This is a requirement for every clinic."),
    ("Not luck. Not timing. Just a decade of careful breeding.",
     "A decade of careful breeding explains this."),
    ("Not a maybe. Not a someday. A decision made this harvest season.",
     "This decision was made this harvest season."),
    ("Not an accident. Not a glitch. A deliberate change to the schedule.",
     "This was a deliberate change to the schedule."),
    ("Not optional. Not a nice-to-have. Core to passing inspection.",
     "This is core to passing inspection."),
    ("Not a rumor. Not speculation. Confirmed by the county records.",
     "This is confirmed by the county records."),
    ("Not exhaustion. Not overwork. Just dehydration.",
     "Dehydration caused this, not exhaustion or overwork."),
    ("Not a small crack. Not a cosmetic issue. A structural problem.",
     "This is a structural problem."),
],
"Despite Its Challenges": [
    ("Despite the drought, the orchard produced a full harvest.",
     "Despite the drought, the orchard's harvest was smaller than usual."),
    ("Despite the staffing shortage, the clinic kept its hours.",
     "The staffing shortage forced the clinic to reduce its hours."),
    ("Despite the budget cuts, the library expanded its programs.",
     "The budget cuts forced the library to scale back its programs."),
    ("Despite the delays, the bridge opened on schedule.",
     "The delays pushed the bridge's opening back by two months."),
    ("Despite the criticism, the new bus route has strong ridership.",
     "The criticism reflects real complaints from riders about the new bus route."),
    ("Despite the setbacks, the harvest festival drew a record crowd.",
     "The setbacks reduced turnout at the harvest festival."),
    ("Despite its cost, the new scanner improved patient outcomes.",
     "The new scanner's cost strained the clinic's budget."),
    ("Despite the frost, the vineyard's yield held steady.",
     "The frost reduced the vineyard's yield this year."),
    ("Despite early resistance, the recycling program is now widely used.",
     "Early resistance to the recycling program has kept participation low."),
    ("Despite the setback, the team qualified for the finals.",
     "The setback ended the team's chances of qualifying for the finals."),
    ("Despite the flooding, the market reopened within a week.",
     "The flooding kept the market closed for over a month."),
    ("Despite the shortage, the clinic managed to vaccinate everyone on schedule.",
     "The shortage delayed vaccinations at the clinic by several weeks."),
],
"One-Point Dilution": [
    ("The clinic was understaffed. There weren't enough nurses. Shifts went uncovered. People were stretched thin. Coverage gaps appeared weekly.",
     "The clinic was understaffed."),
    ("The harvest was late. The season ran long. Frost came early. Timing was off. Everything shifted back.",
     "The harvest was late."),
    ("Communication failed at the shelter. Nobody updated the roster. Shifts overlapped. Volunteers were confused. Nothing was tracked.",
     "Communication failed at the shelter."),
    ("The budget fell short. Funding was cut. Grants didn't come through. Donations dropped. Money ran out.",
     "The budget fell short."),
    ("The trail markers were confusing. Signs were missing. Paint faded. Maps were outdated. Hikers got lost.",
     "The trail markers were confusing."),
    ("Testing was rushed at the lab. Samples weren't logged properly. Results were delayed. Quality checks were skipped. Errors went unnoticed.",
     "Testing was rushed at the lab."),
    ("The onboarding at the farm was too long. New workers felt overwhelmed. There was too much to learn at once. The process dragged. People quit early.",
     "The onboarding at the farm was too long."),
    ("Expectations weren't clear for the volunteers. Nobody explained the goals. Priorities shifted daily. Direction was missing. Morale suffered.",
     "Expectations weren't clear for the volunteers."),
    ("The supplier was unreliable. Deliveries were late. Quality varied. Support was slow. Communication was poor.",
     "The supplier was unreliable."),
    ("The festival setup was chaotic. Timing slipped. Vendors weren't coordinated. Volunteers weren't briefed. Nothing ran on schedule.",
     "The festival setup was chaotic."),
    ("The irrigation system failed repeatedly. Pipes cracked. Pressure dropped. Valves stuck. Repairs kept piling up.",
     "The irrigation system failed repeatedly."),
    ("The clinic's intake process was slow. Forms were long. Staff were overwhelmed. Patients waited. Records got lost.",
     "The clinic's intake process was slow."),
],
"False Ranges": [
    ("The workshop covers everything from composting to conflict resolution.",
     "The workshop covers composting and conflict resolution."),
    ("Our services range from irrigation repair to grief counseling.",
     "We offer irrigation repair and grief counseling."),
    ("The exhibit spans from ancient farming tools to modern drone surveying.",
     "The exhibit includes ancient farming tools and a modern drone display."),
    ("The course goes from basic first aid to advanced diplomacy.",
     "The course covers basic first aid and, separately, negotiation skills."),
    ("Their offerings range from seed packets to financial planning.",
     "They sell seed packets and offer financial planning services."),
    ("The talk moved from soil chemistry to personal branding.",
     "The talk covered soil chemistry and, separately, personal branding."),
    ("The app handles everything from crop tracking to therapy sessions.",
     "The app tracks crops and connects users to therapists."),
    ("The curriculum spans from basic literacy to leadership philosophy.",
     "The curriculum covers basic literacy and, separately, leadership."),
    ("Solutions range from minor repairs to complete facility overhauls.",
     "Solutions include minor repairs and, in some cases, full facility overhauls."),
    ("The clinic's services range from vaccinations to career counseling.",
     "The clinic offers vaccinations and, separately, career counseling."),
    ("The festival covers everything from folk music to tax advice.",
     "The festival features folk music and, separately, a tax-advice booth."),
    ("The program spans from planting basics to estate planning.",
     "The program covers planting basics and, separately, estate planning."),
],
"The X? A Y.": [
    ("The cause? A cracked irrigation valve.",
     "A cracked irrigation valve caused it."),
    ("The verdict? Full recovery expected.",
     "Full recovery is expected."),
    ("The fix? A new gasket, nothing more.",
     "The fix was a new gasket, nothing more."),
    ("The outcome? A record harvest despite the frost.",
     "The harvest was a record despite the frost."),
    ("The reason? A missed inspection two years ago.",
     "A missed inspection two years ago explains it."),
    ("The plan? Rotate crops every other season.",
     "The plan is to rotate crops every other season."),
    ("The response? A quiet apology and a refund.",
     "The response was a quiet apology and a refund."),
    ("The upside? Water bills dropped by half.",
     "Water bills dropped by half."),
    ("The risk? A single failing pump for the whole system.",
     "A single failing pump risks the whole system."),
    ("The result? A clinic that finally has enough beds.",
     "The clinic finally has enough beds."),
    ("The delay? A shipment stuck at the border.",
     "A shipment stuck at the border caused the delay."),
    ("The surprise? The smallest farm had the best yield.",
     "The smallest farm had the best yield."),
],
"It's Worth Noting": [
    ("It's worth noting that the clinic's new hours only apply on weekdays.",
     "The clinic's new hours only apply on weekdays."),
    ("Importantly, the vaccine requires two doses a month apart.",
     "The vaccine requires two doses a month apart."),
    ("Interestingly, the smaller plots yielded more per acre.",
     "The smaller plots yielded more per acre."),
    ("Notably, none of the volunteers had prior experience.",
     "None of the volunteers had prior experience."),
    ("It's worth noting that the bridge repair is temporary.",
     "The bridge repair is temporary."),
    ("Importantly, this grant requires matching funds from the county.",
     "This grant requires matching funds from the county."),
    ("It's worth mentioning that the well was tested just last month.",
     "The well was tested just last month."),
    ("Interestingly, the two clinics reached the same diagnosis independently.",
     "The two clinics reached the same diagnosis independently."),
    ("Notably, the harvest finished faster than any year on record.",
     "The harvest finished faster than any year on record."),
    ("It's worth noting that the survey only reached half the residents.",
     "The survey only reached half the residents."),
    ("Importantly, the shelter's new intake form takes half the time.",
     "The shelter's new intake form takes half the time."),
    ("It's worth noting the trail closes early during hunting season.",
     "The trail closes early during hunting season."),
],
}

REWRITE_TOPUP = {
"Unicode Decoration": [
    ("The recipe goes Prep → Cook → Plate.", "The recipe has three steps: prep, cook, then plate."),
    ("Sales moved $1M → $3M this year.", "Sales moved from $1M to $3M this year."),
],
"Em-Dash Addiction": [
    ("The harvest -- against all odds -- came in strong this year.",
     "The harvest came in strong this year, against all odds."),
    ("The clinic -- short-staffed but determined -- kept its hours.",
     "The short-staffed clinic kept its hours."),
],
"Think of It As": [
    ("Think of the trail map as a cheat sheet for the whole park.",
     "The trail map summarizes the whole park."),
    ("Think of crop rotation as a rest schedule for the soil.",
     "Crop rotation gives the soil a rest."),
],
"The Signposted Conclusion": [
    ("In conclusion, the clinic's new hours reduced wait times.",
     "The clinic's new hours reduced wait times."),
    ("To sum up, the harvest exceeded expectations this year.",
     "The harvest exceeded expectations this year."),
],
"Delve and Friends": [
    ("Let's delve into why the trail closed early this year.",
     "Here's why the trail closed early this year."),
    ("The clinic will utilize the new scanner starting Monday.",
     "The clinic will use the new scanner starting Monday."),
],
"Tapestry and Landscape": [
    ("The rich tapestry of the harvest festival draws visitors from three counties.",
     "The harvest festival draws visitors from three counties."),
    ("Navigating the landscape of flu season requires an early vaccine push.",
     "Managing flu season requires an early vaccine push."),
],
"The Serves As Dodge": [
    ("The new wing serves as a symbol of the hospital's growth.",
     "The new wing is a symbol of the hospital's growth."),
    ("The scholarship serves as recognition of her research.",
     "The scholarship recognizes her research."),
],
"Tricolon Abuse": [
    ("The clinic heals, the clinic teaches, the clinic connects.",
     "The clinic heals, teaches, and connects the community."),
    ("Good soil feeds the roots; good soil holds the water; good soil grows the harvest.",
     "Good soil feeds the roots, holds water, and grows the harvest."),
],
}


def main():
    tropes = read_tropes()
    name_to_id = dict(zip(tropes.column("name").to_pylist(), tropes.column("trope_id").to_pylist()))

    doc_rows, sent_rows, label_rows, rewrite_rows = [], [], [], []

    for name, pairs in PAIRS.items():
        trope_id = name_to_id[name]
        for positive, rewrite in pairs:
            pos_ids = _insert_document(positive, True, True, doc_rows, sent_rows)
            rewrite_ids = _insert_document(rewrite, True, False, doc_rows, sent_rows)
            for sid in pos_ids:
                label_rows.append({
                    "sentence_id": sid, "trope_id": trope_id,
                    "label_source": "synthetic-gen", "confidence": 1.0,
                })
            if pos_ids and rewrite_ids:
                rewrite_rows.append({
                    "rewrite_id": str(uuid.uuid5(REWRITE_NAMESPACE, pos_ids[0])),
                    "sentence_id": pos_ids[0], "trope_id": trope_id,
                    "rewritten_text": rewrite.strip(), "source": "synthetic-gen",
                })

    for name, pairs in REWRITE_TOPUP.items():
        trope_id = name_to_id[name]
        for positive, rewrite in pairs:
            pos_ids = _insert_document(positive, True, True, doc_rows, sent_rows)
            rewrite_ids = _insert_document(rewrite, True, False, doc_rows, sent_rows)
            for sid in pos_ids:
                label_rows.append({
                    "sentence_id": sid, "trope_id": trope_id,
                    "label_source": "synthetic-gen", "confidence": 1.0,
                })
            if pos_ids and rewrite_ids:
                rewrite_rows.append({
                    "rewrite_id": str(uuid.uuid5(REWRITE_NAMESPACE, pos_ids[0])),
                    "sentence_id": pos_ids[0], "trope_id": trope_id,
                    "rewritten_text": rewrite.strip(), "source": "synthetic-gen",
                })

    append_rows(SOURCE_DOCUMENT_PATH, doc_rows)
    append_rows(SENTENCE_PATH, sent_rows)
    append_rows(SENTENCE_TROPE_LABEL_PATH, label_rows)
    append_rows(SENTENCE_REWRITE_PATH, rewrite_rows)
    print(f"round 2: {len(doc_rows)} docs, {len(label_rows)} labels, {len(rewrite_rows)} rewrite pairs")


if __name__ == "__main__":
    main()
